src/App.vue, src/BootstrapVue.ts, src/components/BAccordion.vue, src/components/BAccordionItem.vue, src/components/BAlert.vue, src/components/BBadge.vue, src/components/BBreadcrumb.vue, src/components/BButton.vue, src/components/BCarousel.vue, src/components/BDropdown.vue, src/components/BFormInput.vue, src/components/BListGroupItem.vue, src/components/BNavItemDropdown.vue, src/components/BProgress.vue, src/components/BProgressBar.vue, src/components/BSpinner.vue, src/components/BTabs.vue, src/composables/useBreadcrumb.ts, src/composables/useId.ts
Hello Carlos,
Using relative imports make this lib easier to use.
Feel free to merge this PR.
Cheers 
Geoffrey
=> remove usage of absolute paths

.eslintrc.js, src/App.vue, src/components/BIcon.vue, src/components/BLink.vue, src/components/BListGroup.vue, src/components/BListGroupItem.vue, src/components/BRow.vue, src/components/index.ts
Hello Carlos,
We implemented all the features for BRow, BListGroup and half of the props from BListGroupItem.
BListGroupItem probably needs to use BLink as in BootstrapVue 2, I'll work on this in the forthcoming days.
About BIcon, we made a quick fix by disabling eslint for the problematic line, at least until we find a better version for this.
Best regards
=> BRow, BListGroup & BListGroupItem (+ quick fix for BIcon)

package.json, src/App.vue, src/components/BCol.vue, src/components/BFormInput.vue, src/components/BRow.vue, src/components/index.ts, src/utils/getBreakpointProps.ts, src/utils/getClasses.ts
Hey,
I have done the BCol component &  fix attr binding on BFormInput.
I have also moved the "bootstrap-icons" dependency from "devDependencies" to "dependencies".
Cheers
Geoffrey
=> BCol component 

src/App.vue, src/components/BForm.vue, src/components/BFormText.vue, src/components/BTab.vue, src/components/BTabs.vue, src/components/index.ts
Add new b-form, b-form-text and b-tabs components, taking Bootstrap 5 migration changes into account.
=> BForm, BFormText & BTabs

src/App.vue, src/components/BFormInput.vue, src/components/BFormSelect.vue, src/components/BFormSelectOption.vue, src/components/BFormSelectOptionGroup.vue, src/components/BLink.vue, src/components/BTab.vue, src/components/BTabs.vue, src/components/index.ts
Hi!
This PR:
- fixes absolute path of BLink
- implements (first version) events on BFormInput
- adds some enhancements of BTabs (but some stuff still to be implemented)
- adds BFormSelect, BFormSelectOption & BFormSelectOptionGroup with an implementation pretty close to what we expect for these components
=> BFormInput, BTabs, BFormSelect, BFormSelectOption & BFormSelectOptionGroup + examples

src/App.vue, src/components/BCard.vue, src/components/BCardBody.vue, src/components/BCardFooter.vue, src/components/BCardHeader.vue, src/components/BCardImg.vue, src/components/BCardSubTitle.vue, src/components/BCardTitle.vue, src/components/BTabs.vue, src/components/index.ts
BCards & BCards components + examples
I have also disabled eslint rule in the file App.vue for:
- vue/max-attributes-per-line
- vue/singleline-html-element-content-newline
=> BCards & sub components

src/App.vue, src/components/BDropdown.vue, src/styles/styles.css
this can be used to use custom icon on dropdown
https://bootstrap-vue.org/docs/components/dropdown#hidden-caret
=> Dropdown hidden-caret

src/components/BTable.vue
As in bootstrap-vue, you can create a table caption by either setting the caption property or using the table-caption slot
=> table caption support with scope

docs/components/FormCheckbox.md, docs/reference/parityList.md, src/App.vue, src/components/BFormCheckbox/BFormCheckbox.vue, src/components/BFormCheckbox/form-checkbox.spec.js, src/components/BFormRadio/BFormRadio.vue, src/components/BFormRadio/form-radio.spec.js, src/composables/useFormCheck.ts
Fixes #46 
Also fixed for Form Radio
=> fix: Reverse behavior of Form checkbox plain property

docs/.vuepress/config.ts, docs/components/FormCheckbox.md
The examples are now backed by a working script.
(Love the vue3 script setup for this!!)
=> docs: Form Checkbox docs now with working examples

src/App.vue, src/components/BFormCheckbox/BFormCheckbox.vue, src/components/BFormRadio/BFormRadio.vue, src/composables/useFormCheck.ts
Fixes issue #65 
- value property must have default value true. Bug existed prior to #64 , but somehow the new code made this causing the simple checkbox failures
- #64 removed the ability to have an array as v-model.
- additional fixes for FormRadio 
Still open issues :
- input event is removed. We need to either update the docs or make input event working again
- lots of unittests fail due to the complete change of the inner working of the FormCheckbox
- fix unittests and remove tests no longer relevant
=> Fix formcheckbox and formradio. Fixes #65

docs/components/FormCheckbox.md, docs/reference/parityList.md
After the rewrite by @Geoffrey-D, the size property is now also implemented
Updated the docs for size and inline property
=> docs: Update to doc for BFormCheckbox

.gitignore, package.json
=> moved babel to dev deps, per https://babeljs.io/docs/en/babel-preset-env

src/components/BFormCheckbox/form-checkbox.spec.js, src/composables/useFormCheck.ts
=> fix : BFormCheckboxGroup should display checkboxes default inline in plain mode

docs/components/FormCheckbox.md, docs/reference/parityList.md, src/components/BFormCheckbox/BFormCheckbox.vue
docs for BFormCheckboxGroup
+ small fix for required property of BFormCheckbox (It needs name to be effective)
=> docs: Documentation for BFormCheckboxGroup

src/components/BFormRadio/form-radio.spec.js, src/composables/useFormCheck.ts
=> fix: BFormRadio prop size ignored when button style

docs/components/Dropdown.md, docs/reference/parityList.md
documentation for auto-close property with examples
=> docs : Update docs BDropdown auto-close

src/components/BDropdown.vue
solve https://github.com/cdmoro/bootstrap-vue-3/issues/91
=>  fix BDropdown split button in block mode + fix inverted variant usage

docs/.vuepress/config.ts, docs/components/Breadcrumb.md, docs/reference/parityList.md, src/components/BBreadcrumb.vue, src/components/BBreadcrumbItem.vue
Fixes :
- breadcrumb items can be an array of strings
- last breadcrumb item not automatically set active
- click event on breadcrumb item not implemented
- implement target property on breadcrumb item
=> fixes + docs BBreadcrumb

docs/.vuepress/config.ts, docs/components/Alert.md, docs/reference/parityList.md, src/App.vue, src/components/BAlert.vue
- v-model support
- auto dismiss functionality
- docs
=> Rework BAlert + docs

src/App.vue, src/components/BPagination.vue
Add Ellipsis Support and Start/End Number Support. 
Still more to go....
=> B pagination

src/App.vue, src/components/BTabs.vue
add ability to add custom content to tab title (like https://bootstrap-vue.org/docs/components/tabs#add-custom-content-to-tab-title)
=> BTabs - custom content in tab title

docs/components/Avatar.md, docs/reference/parityList.md, src/components/BAvatar/BAvatar.vue, src/components/BAvatar/BAvatarGroup.vue, src/components/index.ts, src/utils/math.ts
=> feat : BAvatarGroup + docs

docs/.vuepress/config.ts, docs/components/README.md, docs/reference/parityList.md, src/App.vue, src/components/BPagination/BPagination.vue, src/utils/bvEvent.ts, src/utils/object.ts
- implement all aria-... attributes
- preventable page-click event
- docs updates
=> BPagination updates

docs/.vuepress/config.ts, docs/components/ListGroup.md, docs/components/README.md, docs/reference/parityList.md, src/components/BListGroup/BListGroup.vue, src/components/BListGroup/BListGroupItem.vue, src/components/BListGroup/list-group-item.spec.js, src/components/BListGroup/list-group.spec.js
- implement numbered property
- Docs for BListGroup and BListGroupItem
=> BListGroup docs + implement numbered

src/components/BTabs.vue
- implement start, end and empty slots
- fix handling of current tab index
=> Various fixes for BTabs

src/App.vue
- Removed option Api remnants
- Removed unused variables
- Structured examples
=> Cleanup App.vue

src/components/BCard/BCardImg.vue
How this doesn't cause you guys errors?
My setup shouted error on import, so I thought this was a typo that was gonna get fixed in hours.
=> fix BCardImg

src/components/BTabs/BTabs.vue
Cleanup of console.log for b-tabs
=> Remove console.log on b-tabs @click event

src/App.vue, src/components/BPopover.vue
=> Feature [BPopover Component]: BPopover container prop can use an HTMLElement

package.json, stats.html, vite.config.ts
generate stats.html on build, to monitor  bundle size stats
=> add bundle size stats

src/components/BContainer.vue, src/components/BPopover.vue, src/main.ts
When we create a <b-popover /> without defining the delay value, we got an error because the undefined value is not allowed.
So, I keep the optimal parameter and I set a 0 value as default for delay.
=> Avoid error TypeError: TOOLTIP

src/App.vue, src/components/BDropdown/BDropdownItem.vue, src/main.ts
Regarding #272 
There is a typescript error on "About" component, but I don't know how to fix that, other than creating a "real" component file.
=> Add b-link to b-dropdown-item

package.json, src/App.vue, src/BootstrapVue.ts, src/components/BModal.vue, src/globalProperties/bvModal.ts, src/globalProperties/index.ts, src/shims-vue.d.ts, src/types/Modal.d.ts
Related to #120 
Hi ! This is my first contribution of an open source project, I hope it goes well!
I've made this implementation using mitt.js as global event bus. 
This could probably be replaced by a native solution, but this library is realy tiny and easy to use.
=> Implementation of $bvModal

src/components/BFormTags/form-tag.spec.js
adding a test for BFormTag component
=> BFormTag unit test

src/BootstrapVue.ts
=> Export individual directives

package.json, src/BootstrapVue.d.ts
Following this discussion in the last pull request : https://github.com/cdmoro/bootstrap-vue-3/pull/351
> Thanks! `BootstrapVue.d.ts` file is still empty though, I assume because we don't use vite in library mode? Would you send a PR for that too?
> Although I see this
> 
> ```
> [vite:dts] Start generate declaration files...
> [vite:dts] Declaration files built in 6897ms.
> ```
> 
> I don't know where are the generated declarations
The files are generated in the `dist` folder
```
ls -r dist/*
dist/shims-vue.d.ts         dist/index.html             dist/favicon.ico            dist/bootstrap-vue-3.umd.js dist/bootstrap-vue-3.es.js  dist/bootstrap-vue-3.css    dist/BootstrapVue.d.ts
dist/utils:
stringUtils.d.ts        props.d.ts              number.d.ts             mergeDeep.d.ts …
```
=> feat: generate dist/BootstrapVue.d.ts and update package.json

src/components/BTable/BTable.vue
=> Update Table to return 1 callable

src/components/BPopover.vue
I fixed the useless px on the last pull request
=> Issue #397 popover doesn't contain offset - resubmit

src/components/BCard/BCard.vue, src/components/BCard/BCardBody.vue, src/components/BCard/BCardFooter.vue, src/components/BCard/BCardHeader.vue, src/components/BDropdown/BDropdown.vue, src/components/BDropdown/BDropdownGroup.vue, src/components/BDropdown/BDropdownItem.vue, src/components/BDropdown/BDropdownItemButton.vue, src/types/components/BCard/BCard.d.ts, src/types/components/BCard/BCardBody.d.ts, src/types/components/BCard/BCardFooter.d.ts, src/types/components/BCard/BCardHeader.d.ts, src/types/components/BDropdown/BDropdownGroup.d.ts, src/types/components/BFormTags/BFormTags.d.ts, src/types/components/BToast/BToast.d.ts
Some are probably strings, but some may be not, so to avoid any issues I will temporarily set them to unknown. I'll return to them later to make them strongly typed.
=> Convert old Array<string> to unknown

docs/components/Dropdown.md, src/App.vue, src/components/BDropdown/BDropdown.vue
Hi!
It was pending to emit the click when we split the button for a dropdown like here:
https://bootstrap-vue.org/docs/components/dropdown#listening-to-dropdown-changes-via-root-events:~:text=is%20shown.%20Cancelable-,click,-event%20%2D%20Native
Regards
=> Emitting click for splitted  and toggle buttons

src/components/BDropdown/BDropdown.vue, src/components/BNavItemDropdown.vue
* Added prop **noCaret** component **BNavItemDropdown**
* Added class **dropdown-menu-right** in **dropdownMenuClasses** component **BDropdown**
=> Added prop and class in components (BNavItemDropdown, BDropdown)

src/components/BTable/BTable.vue, src/components/BTable/BTableSimple.vue, src/components/BTable/BTd.vue, src/components/BTable/BTh.vue
For now, it's just a direct conversion. But I am planning to split BTable into smaller components to make it more readable and avoid code duplication. Does this sound like a good idea?
=> Convert tables from render functions to templates.

src/components/BPopover.vue
Previous this code, it was not possible to keep one instance of BPopover to point dynamically to new target, in that case we needed to generate several BPopover instances to each target with similar content.
If we are watching for changes in target in the same instance of BPopover, we can move the element to point to a new target and free the previous instance generate.
I guess the warning doesn't make senses, if we allow undefined value, don't display a warning. And specially now that we have a watch to update the undefined value to the new target.
=> BPopover: Allow to update the new target

.github/workflows/release-please.yml
=> fix(workflow): fix package name.. again

docs/.vuepress/client.ts, docs/components/Toast.md, src/components/BToast/plugin.ts
Lets hopefully see if this builds and fixes toasts running on client side docs.
=> fix client side toasts

src/components/BCard/BCardBody.vue
https://github.com/cdmoro/bootstrap-vue-3/issues/469
=> Fix: subtitle should be undefined by default

src/App.vue
=> fix: test commit please ignore

package-lock.json, src/directives/BTooltip.ts
- Update `bootstrap` to `v5.2.0`
- Update `@types/bootstrap` to `v5.2.0`
- Re-enable disabled typescript checks
Closes #250
=> [BTooltip] Re-enable typescript

.github/workflows/release-please.yaml
=> chore: release 0.2.0

apps/docs/docs/README.md, apps/docs/docs/getting-started/README.md
This is also a test commit to ensure that the docs are getting updated after the major changes
=> docs: remove vuepress default text

packages/bootstrap-vue-3/src/components/BModal.vue, packages/bootstrap-vue-3/src/components/BTable/BTable.vue, packages/bootstrap-vue-3/src/components/BTable/BTableContainer.vue, packages/bootstrap-vue-3/src/components/BTable/_table.scss, packages/bootstrap-vue-3/src/components/BTable/itemHelper.ts
This is a basic addition of sortable and modal lazy
BModal lazy only renders it's content as lazy, and does not actually fetch anything lazily. [devhus](https://github.com/devhus), the original author, had made a <Suspense> addition, but from all of my testing, it didn't actually do anything. It may be possible in the future to further refine this as an async component, but at this time I'm unsure how.
=> BTable sortable and BModal lazy props

packages/bootstrap-vue-3/src/components/BTable/BTable.vue
fix(BTable): include prop field in slot cell
=> fix: include prop field in slot cell.

packages/bootstrap-vue-3/src/components/BModal.vue
_This can be a copy/paste of all **Conventional Commits** messages_
=> hide and show emits added

packages/bootstrap-vue-3/package.json, packages/bootstrap-vue-3/src/components/BImg.vue, packages/bootstrap-vue-3/src/components/img.spec.ts, packages/bootstrap-vue-3/tests/utils/getId.spec.ts, packages/bootstrap-vue-3/vite.config.ts, pnpm-lock.yaml
[test: remove vi from getId test](https://github.com/cdmoro/bootstrap-vue-3/commit/c02c98b25711a602afdbdbb4f187c4b65664a8c6)
[test: include coverage reporter](https://github.com/cdmoro/bootstrap-vue-3/commit/53ffdbb10cd32ec02bf04c7c1e6da099fc1dce2e)
=> refactor(BImg): decompose internal attrs method 

.github/workflows/ci.yaml
_This can be a copy/paste of all **Conventional Commits** messages_
=> ci: remove dead code use pnpm over npm

.github/workflows/ci.yaml
_This can be a copy/paste of all **Conventional Commits** messages_
=> cI: revert back to npm ig

.github/workflows/ci.yaml
=> ci: include test coverage and test unit to pnpm

packages/bootstrap-vue-3/src/components/BDropdown/BDropdownItem.vue
=> chore(b-dropdown-item): :bulb: Fix misspelling

packages/bootstrap-vue-3/src/components/BTable/BTable.vue, packages/bootstrap-vue-3/src/components/BTable/_table.scss, packages/bootstrap-vue-3/src/components/BTable/itemHelper.ts, packages/bootstrap-vue-3/src/components/BTabs/BTab.vue, packages/bootstrap-vue-3/src/utils/object.ts
BREAKING CHANGES: The content of BTable items prop will not be updated anymore! The table now uses an internal object for handling item manipulation when it is required in cases such as Table Sorting, Table Filtering, and Pagination. 
feat(BTab): added a new ``lazyOnce`` prop, The prop works similarly to the ``lazy`` prop but it mounts the child component only once.
feat(BTable): implemented per page prop functionality.
feat(BTable): added functionality to ``current-page prop``, The prop shows a specific page of the given items when the per-page prop is passed.
feat(BTable): added ``filter`` prop to filter the table content.
feat(BTable): added ``filterable`` prop to specify which fields should be filtered, this prop is known in bs-vue2 as ``filter-included-fields``. …
=> BTable Advanced Features implementations

packages/bootstrap-vue-3/src/components/BTable/BTable.vue
=> chore: lint BTable

apps/docs/docs/components/README.md
Just added it to the list of components in the index
=> Small fix related to #645

apps/docs/docs/component-references/Table.json, packages/bootstrap-vue-3/src/module.ts, pnpm-lock.yaml
=> feat: create Options object

packages/bootstrap-vue-3/src/components/BNav/BNavItemDropdown.vue
feat: add props toggleClass to BnavItemDropdown
=> feat: add props toggleClass to BnavItemDropdown

packages/bootstrap-vue-3/src/components/BOffcanvas.vue, packages/bootstrap-vue-3/src/types/components/BOffcanvas.d.ts
BOffcanvas:
added ```header``` and ```footer``` slots.
added ```noHeaderClose``` and ```noHeader``` properties
=> Offcanvas new slots

apps/playground/src/components/Directives/TVisible.vue, packages/bootstrap-vue-3/src/BootstrapVue.ts, packages/bootstrap-vue-3/src/components/BAccordion/BAccordionItem.vue, pnpm-lock.yaml
fix(directives): export proper naming schemes
chore: update pnpm-lock
=> fix(directives): export proper naming schemes

packages/bootstrap-vue-3/src/components/BTable/b-table.spec.ts, packages/bootstrap-vue-3/src/components/BTabs/BTabs.vue, packages/bootstrap-vue-3/src/components/BTabs/tabs.spec.ts
@devhus 
Your tests are at a good start, but need some work. So I'm going to use this to clear some misconceptions I think you may have in your tests. 
1. You are correct in that you are testing for the existence of a component. Your use of .exists() is correct. However, when you have already checked for the existence of a component, you should instead use `.get()` to get the component, rather than `.find()`..... `.get()` will throw an error when it does not exist, whereas a `.find()` will have a failing test. Basically, use `.find()` only when checking the existence, and `.get()` after you have tested the existence. 
2. In your first test, you had started testing the inner workings of the BTableContainer.vue file. You were checking that it's `tag is table by default`, `tag is div when …
=> test: tabs.spec.ts

packages/bootstrap-vue-3/src/components/BCarousel/BCarouselSlide.vue
=> chore: lint

packages/bootstrap-vue-3/src/components/BInputGroup/BInputGroupAddon.vue, packages/bootstrap-vue-3/src/components/BInputGroup/BInputGroupAppend.vue, packages/bootstrap-vue-3/src/components/BInputGroup/BInputGroupPrepend.vue, packages/bootstrap-vue-3/src/components/BInputGroup/_input-group.scss, packages/bootstrap-vue-3/src/components/BInputGroup/input-group-addon.spec.ts, packages/bootstrap-vue-3/src/components/BInputGroup/input-group-append.spec.ts, packages/bootstrap-vue-3/src/components/BInputGroup/input-group.prepend.spec.ts
@VividLemon  I don't know how to add the CSS to your PR so, I have replicated it with a fix dropdown 😆
=> replication of #703 PR with BDropdown rounded corners fix

package.json, pnpm-lock.yaml
=> chore: update pnpm-lock and pnpm version

packages/bootstrap-vue-3/src/components/BBreadcrumb/breadcrumb-item.spec.ts, packages/bootstrap-vue-3/src/components/BBreadcrumb/breadcrumb.spec.ts, packages/bootstrap-vue-3/src/components/BInputGroup/input-group-addon.spec.ts
test: breadcrumb
test: input-grou-addon
=> test: breadcrumb-item

packages/bootstrap-vue-3/src/components/BBreadcrumb/BBreadcrumbItem.vue
=> fix: dts build error on breadcrumbitem

packages/bootstrap-vue-3/src/components/BLink/BLink.vue, packages/bootstrap-vue-3/src/components/BNav/BNavItem.vue
fix(BLink): has class activeClass when prop active
fix(BLink): has class exactActiveClass when prop exact
=> fix(BLink): has class activeClass when prop active

apps/docs/docs/.vuepress/config.ts, apps/docs/docs/component-references/Card.json, apps/docs/docs/component-references/Placeholder.json, apps/docs/docs/components/Placeholder.md, apps/docs/docs/components/README.md, packages/bootstrap-vue-3/src/BootstrapVue.ts, packages/bootstrap-vue-3/src/components/BPlaceholder/BPlaceholderButton.vue, packages/bootstrap-vue-3/src/components/BPlaceholder/BPlaceholderCard.vue, packages/bootstrap-vue-3/src/components/BPlaceholder/BPlaceholderTable.vue, packages/bootstrap-vue-3/src/components/BPlaceholder/placeholder-button.spec.ts, packages/bootstrap-vue-3/src/components/BPlaceholder/placeholder-card.spec.ts, packages/bootstrap-vue-3/src/components/BPlaceholder/placeholder-table.spec.ts, packages/bootstrap-vue-3/src/components/index.ts, packages/bootstrap-vue-3/src/utils/number.ts
docs: add BPlaceholder elements 
feat(BPlaceholderButton): create BPlaceholderButton
refactor(BPlaceholder): use BPlaceholderButton when not prop noButton
feat(BPlaceholderTable): props columns and rows can now be string or number
test: for above changes
=> feat(BPlaceholderButton): create BPlaceholderButton

CODE_OF_CONDUCT.md
=> docs: contributor covenant v2.1 revision

packages/bootstrap-vue-3/src/components/BPlaceholder/BPlaceholder.vue, packages/bootstrap-vue-3/src/components/BPlaceholder/BPlaceholderCard.vue, packages/bootstrap-vue-3/src/components/BTransition/BTransition.vue, packages/bootstrap-vue-3/src/components/BTransition/transition.spec.ts, packages/bootstrap-vue-3/src/utils/cssEscape.ts, packages/bootstrap-vue-3/src/utils/inspect.ts, packages/bootstrap-vue-3/src/utils/props.ts, packages/bootstrap-vue-3/src/utils/stringUtils.ts
=> fix(BTransition): allowTransProps to work

packages/bootstrap-vue-3/src/components/BOverlay/BOverlay.vue, packages/bootstrap-vue-3/src/components/BOverlay/overlay.spec.ts, packages/bootstrap-vue-3/src/components/BPagination/pagination.spec.ts, packages/bootstrap-vue-3/src/components/BTransition/transition.spec.ts, packages/bootstrap-vue-3/src/composables/useAlignment.ts
refactor(useAlignment): strongly type output
test: add todo note to transition.spec.ts
test: partial pagination.spec.ts
test: overlay.spec.ts
fix(BOverlay): strongly type some props
refactor(BOverlay): convert to template and script setup syntax
=> refactor(BOverlay): convert to template and script setup syntax

apps/docs/docs/components/Skeleton.md
=> docs: change deprecation warning to 0.5 for skeleton

packages/shared/package.json, pnpm-lock.yaml
=> chore: add in shared workspace

packages/bootstrap-vue-3/src/components/BModal.vue
=> BModal fixes

apps/docs/docs/getting-started/README.md
=> docs: update installation page

packages/bootstrap-vue-3/src/components/BContainer.vue, packages/bootstrap-vue-3/src/components/BPagination/BPagination.vue, packages/bootstrap-vue-3/src/components/container.spec.ts
=> revert(BContainer): revert to fix usage with toast

packages/bootstrap-vue-3-icons/scripts/generate.ts
=> fix : Revert Changes causing issues

packages/bootstrap-vue-3/src/BootstrapVue.ts, packages/bootstrap-vue-3/src/components/BAlert/BAlert.vue, packages/bootstrap-vue-3/src/components/BAlert/alert.spec.ts, packages/bootstrap-vue-3/src/components/index.ts
Port over tests to verify count down on render.
Refs: #810 
=> fix: on balert create, start counter

apps/docs/docs/component-references/Modal.json, apps/docs/docs/components/Modal.md, apps/docs/docs/getting-started/README.md, packages/bootstrap-vue-3/src/components/BModal.vue, packages/bootstrap-vue-3/src/styles/styles.scss
fix(modal): maybe fix modal... if it was even broken
docs(modal): add static type to json file
=> docs: add modal usage

packages/bootstrap-vue-3-icons/package.json, packages/bootstrap-vue-3/package.json
=> fix(nuxt): include new files when packing

apps/docs/docs/component-references/Table.json
Update the "slots" for the table component, as some slots (like `custom-foot`) were missing - while working perfectly fine.
=> Update slots documentation for Table component

packages/bootstrap-vue-3/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-3/src/components/BFormGroup/BFormGroup.vue, packages/bootstrap-vue-3/src/components/BFormGroup/form-group.spec.ts, packages/bootstrap-vue-3/src/composables/exports/index.ts, packages/bootstrap-vue-3/src/composables/index.ts, packages/bootstrap-vue-3/src/composables/useAlignment.ts, packages/bootstrap-vue-3/src/composables/useBreadcrumb.ts, packages/bootstrap-vue-3/src/composables/useColorMode.ts, packages/bootstrap-vue-3/src/composables/useEventListener.ts, packages/bootstrap-vue-3/src/composables/useFormCheck.ts, packages/bootstrap-vue-3/src/directives/BColorMode.ts, packages/bootstrap-vue-3/src/directives/BFocus.ts, packages/bootstrap-vue-3/src/directives/BModal.ts, packages/bootstrap-vue-3/src/directives/BPopover.ts, packages/bootstrap-vue-3/src/directives/BToggle.ts, packages/bootstrap-vue-3/src/directives/BTooltip.ts, packages/bootstrap-vue-3/src/directives/BVisible.ts, packages/bootstrap-vue-3/src/directives/exports/index.ts, packages/bootstrap-vue-3/src/directives/focus.ts, packages/bootstrap-vue-3/src/directives/index.ts, packages/bootstrap-vue-3/tests/composables/useAlignment.spec.ts
=> feat: create useColorMode composable in anticipation of Bootstrap v5.3

apps/playground/vite.config.ts
=> chore: watch for dist changes in playground

packages/bootstrap-vue-3/src/composables/useColorMode.ts
=> fix: persistence in useColorMode

README.md
Add a section on how to build and browse docs locally to README
Partially addresses #866 
=> docs: add section on how to build and browse docs locally to README

apps/docs/docs/reference/parityList.md, packages/bootstrap-vue-next/nuxt.ts, packages/bootstrap-vue-next/src/components/BCollapse.vue, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
=> chore: fix tech debt

apps/playground/src/components/Comps/TTable.vue
Adds a quick sample  to the playground which shows how selectable table works (as i was struggling with hiding the selectable column).
=> feat(playground): Add "selectable" sample to playground

apps/docs/docs/components/Carousel.md, packages/bootstrap-vue-next/src/components/BCarousel/BCarousel.vue
=> docs: revamp carousel documentation

apps/docs/docs/components/Carousel.md
=> docs: autoplay reverse header

packages/bootstrap-vue-next/package.json, pnpm-lock.yaml
=> fix: move @vueuse/shared to dev dependency

apps/docs/docs/getting-started/README.md
=> docs: add installation info

packages/bootstrap-vue-next/src/components/BAlert/BAlert.vue, packages/bootstrap-vue-next/src/components/BAvatar/BAvatar.vue, packages/bootstrap-vue-next/src/components/BCard/BCard.vue, packages/bootstrap-vue-next/src/components/BCard/BCardBody.vue, packages/bootstrap-vue-next/src/components/BCarousel/BCarouselSlide.vue, packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue, packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue, packages/bootstrap-vue-next/src/components/BModal.vue, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue, packages/bootstrap-vue-next/src/components/BSpinner.vue, packages/bootstrap-vue-next/src/utils/dom.ts
=>  revert(debde21): add back in footer slot on Offcanvas 

packages/bootstrap-vue-next/src/components/BAlert/BAlert.vue, packages/bootstrap-vue-next/src/components/BAvatar/BAvatar.vue, packages/bootstrap-vue-next/src/components/BCard/BCard.vue, packages/bootstrap-vue-next/src/components/BCard/BCardBody.vue, packages/bootstrap-vue-next/src/components/BCarousel/BCarouselSlide.vue, packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue, packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue, packages/bootstrap-vue-next/src/components/BModal.vue, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue, packages/bootstrap-vue-next/src/components/BSpinner.vue, packages/bootstrap-vue-next/src/components/BTabs/BTabs.vue, packages/bootstrap-vue-next/src/utils/dom.ts, packages/bootstrap-vue-next/tests/utils/isEmptySlot.spec.ts
=> fix(isEmptySlot): fix checking for empty slots

package.json, packages/bootstrap-vue-next/src/components/BCarousel/BCarousel.vue, packages/bootstrap-vue-next/src/utils/classes/BvCarouselEvent.ts, packages/bootstrap-vue-next/src/utils/classes/BvEvent.ts, packages/bootstrap-vue-next/src/utils/classes/index.ts, packages/bootstrap-vue-next/src/utils/exports/index.ts, packages/bootstrap-vue-next/tests/utils/BvEvent.spec.ts
=> feat(BCarousel)!: emit events use BvCarouselEvent

apps/docs/docs/components/Table.md
=>  docs: remove warning

packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
=> feat(BDropdown): close on esc

apps/docs/docs/components/Dropdown.md, apps/docs/docs/components/Nav.md, packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue
=> docs: overhaul the bdropdown docs

packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
=> support boolean on BFormGroup cols

apps/docs/docs/components/Carousel.md, packages/bootstrap-vue-next/src/components/BCarousel/BCarousel.vue, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
=> feat(BCarousel): don't require v-model to function

packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckboxGroup.vue, packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadioGroup.vue, packages/bootstrap-vue-next/src/components/BModal.vue, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
fixes #951 
fix(BModal): hide.prevent not functioning correctly
chore(BFormCheckboxGroup): add note
chore(BFormRadioGroup): add note
=> fix(BModal): Modal not appearing when default value is true on mounted

packages/nuxt/package.json
=> chore: add blank nuxt package for the future

packages/nuxt/package.json
=> chore: nuxt package is public

packages/bootstrap-vue-next/src/components/BAlert/BAlert.vue, packages/bootstrap-vue-next/src/components/BButton/BButton.vue, packages/bootstrap-vue-next/src/components/BCollapse.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue, packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckboxGroup.vue, packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue, packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadioGroup.vue, packages/bootstrap-vue-next/src/components/BFormSelect/BFormSelect.vue, packages/bootstrap-vue-next/src/components/BFormSpinButton/BFormSpinButton.vue, packages/bootstrap-vue-next/src/components/BFormTags/BFormTags.vue, packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue, packages/bootstrap-vue-next/src/components/BPagination/BPagination.vue, packages/bootstrap-vue-next/src/components/BTabs/BTabs.vue, packages/nuxt/package.json
=> refactor: useVModel from vueuse change

packages/bootstrap-vue-next/src/components/BModal.vue
feat(BModal): add prop autoFocusButton
fix(BModal): correctly assign focus to element after transition has stopped fixes #964
=> feat(BModal)!: rename prop noFocus to prop autoFocus

packages/bootstrap-vue-next/src/components/BPopover.vue
=> fix the modelValue Booleanish

packages/bootstrap-vue-next/src/components/BPopover.vue
fix, watchEffect was running the code on changes on showState also.
=> fix watcheffect causing double animation / changes

.npmrc, apps/docs/package.json, packages/bootstrap-vue-next/src/App.vue, packages/bootstrap-vue-next/src/components/BAlert/BAlert.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-next/src/components/BPlaceholder/BPlaceholderTable.vue, packages/nuxt/.eslintrc, packages/nuxt/.gitignore, packages/nuxt/.nuxtrc, packages/nuxt/README.md, packages/nuxt/package.json, packages/nuxt/playground/nuxt.config.ts, packages/nuxt/playground/package.json, packages/nuxt/src/module.ts, packages/nuxt/src/runtime/plugin.ts, packages/nuxt/tsconfig.json, pnpm-lock.yaml
=> fix: build issues

packages/bootstrap-vue-next/src/App.vue, todo.md
=> chore: revert app.vue

pnpm-lock.yaml
=> chore: fix pnpm lock

.github/workflows/ci.yaml, .github/workflows/docs-github-pages-deploy.yaml, .github/workflows/npm-publish.yaml, .github/workflows/release-dev.yaml, .github/workflows/release-main.yaml, apps/docs/docs/getting-started/README.md, apps/docs/package.json, package.json, packages/bootstrap-vue-next/package.json, packages/nuxt/playground/app.vue, packages/nuxt/playground/nuxt.config.ts, packages/nuxt/playground/package.json, packages/nuxt/src/module.ts, packages/nuxt/src/types/ModuleOptions.ts, packages/nuxt/src/utils/parseActiveImports.ts, pnpm-lock.yaml
=> nuxt stuff

packages/nuxt/playground/app.vue, packages/nuxt/src/module.ts, packages/nuxt/src/runtime/composables.ts, packages/nuxt/src/runtime/directives.ts, packages/nuxt/src/types/ModuleOptions.ts, packages/nuxt/src/utils/parseActiveImports.ts
=> feat: finalize nuxt module

apps/playground/src/components/Comps/TTable.vue
Small fix to type error in TTable (playground)
=> Fix type problem in playground

apps/playground/src/components/Comps/TFormCheckboxGroup.vue, packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue, packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue, packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadioGroup.vue, packages/bootstrap-vue-next/src/components/RenderComponentOrSkip.vue, packages/bootstrap-vue-next/src/utils/keys.ts
=> if group is buttons, remove wrapping div.

apps/playground/src/Views/HomePage.vue, apps/playground/src/components/Comps/TNavbar.vue, packages/bootstrap-vue-next/src/components/BCollapse.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue, packages/bootstrap-vue-next/src/components/BDropdown/dropdown.spec.ts, packages/bootstrap-vue-next/src/components/BLink/BLink.vue, packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue, packages/bootstrap-vue-next/src/utils/keys.ts
Add inject/provide to collapse
in dropdown-item and b-link close the collapse if collapse isNav is true
fixes #721
fixes #1018
=> Navbar dropdown and collapse fix

package.json, pnpm-lock.yaml
=> chore: update pnpm lock

apps/playground/src/Views/HomePage.vue, apps/playground/src/components/Comps/TFormTags.vue, packages/bootstrap-vue-next/src/components/BFormTags/BFormTag.vue, packages/bootstrap-vue-next/src/components/BFormTags/BFormTags.vue, packages/bootstrap-vue-next/src/components/BFormTags/form-tags.spec.ts, packages/bootstrap-vue-next/src/constants/regex.ts, packages/bootstrap-vue-next/src/utils/stringUtils.ts
fix(BFormTags): split on separator before adding tag fixes #953
=> fix(BFormTags): split on separator before adding tag

packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue
=> fix(BDropdownItem): add attrs when no to props is present

apps/playground/src/components/Comps/TPopover.vue, packages/bootstrap-vue-next/src/components/BCollapse.vue, packages/bootstrap-vue-next/src/components/BPopover.vue, packages/bootstrap-vue-next/src/components/RenderComponentOrSkip.vue, packages/bootstrap-vue-next/src/components/popover.spec.ts, packages/bootstrap-vue-next/src/utils/dom.ts
works with overflow: scroll + container="body"
fixes #1044 problem that @aki77 has.
also use the RenderOrSkip component for popover.
=> fix(BPopover): remove hidden element from dom

apps/playground/src/components/Comps/TModal.vue, packages/bootstrap-vue-next/src/components/BModal.vue, packages/bootstrap-vue-next/src/composables/index.ts, packages/bootstrap-vue-next/src/composables/useModalManager.ts
=> fix(BModal): multiple open modals and performance issues

apps/docs/.vitepress/config.ts
=> docs: fix base path

apps/docs/.vitepress/theme/keys.ts
=> docs: strong type

apps/docs/.vitepress/config.ts, apps/docs/.vitepress/theme/Layout.vue, apps/docs/package.json, apps/docs/src/components/ComponentReference.vue, apps/docs/src/data/foo.data.ts, apps/docs/src/getting-started.md, apps/docs/src/reference/components.md, apps/docs/src/reference/components/alert.md, apps/docs/src/reference/composables.md, apps/docs/tsconfig.app.json
=> docs: components links

.github/workflows/ci.yaml, .github/workflows/docs-deploy.yaml, .github/workflows/npm-publish.yaml, .github/workflows/release-dev.yaml, .github/workflows/release-main.yaml, apps/docs/src/reference/components/alert.md, apps/docs/src/reference/components/form-textarea.md
=> docs: kebab case some props

apps/docs/src/reference/types.md
=> docs: fix path of module typings

packages/bootstrap-vue-next/src/components/BTable/table-simple.spec.ts
=> test: fix test

README.md, packages/bootstrap-vue-next/src/App.vue
=> docs: fix readme logo path

apps/docs/.vitepress/theme/Layout.vue, apps/docs/src/getting-started.md, apps/docs/src/reference/icons.md
=> docs: fix hydration issues

CONTRIBUTING.md, README.md, apps/docs/.vitepress/theme/index.ts, apps/docs/src/getting-started.md, packages/bootstrap-vue-next/index.html, packages/bootstrap-vue-next/package.json, packages/nuxt/package.json
=> docs: fix links

.github/workflows/release-main.yaml
=> fix: ci permissions

.github/workflows/release-main.yaml
=> ci: fix ci

release-please-config.json
=> chore: manually set release-as

packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
expose methods to close, open and toggle programmatically.
(It was included previous from here https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/117/files#diff-b75ac8fc50ce4627b6d238b4de8baa36a497ce934b0dc55bbd80f09f782b0727R172, and removed here https://github.com/bootstrap-vue-next/bootstrap-vue-next/commit/2c3da403#diff-8fb2aa4b9e64fcfc83279f6f83dc799c8ca5b33e3673d8723f5d223647dd47deL226)
=> feat(BDropdown): expose methods to close, open and toggle programmatically

apps/docs/src/components/MigrationWrapper.vue, apps/docs/src/migration-guide.md, apps/docs/src/reference/migrate.md
=> docs: migration wrapper

apps/docs/src/getting-started.md, packages/nuxt/src/module.ts, packages/nuxt/src/runtime/directives.ts, packages/nuxt/src/types/ModuleOptions.ts
=> docs: add section to nuxt installation about directives

apps/docs/src/getting-started.md, apps/docs/src/reference/icons.md
=> docs: useSessionStorage > useLocalStorage

apps/docs/src/getting-started.md, apps/docs/src/reference/icons.md
This reverts commit 4a438bded9c17d35f0c326eb11dcb2e117437686.
=> docs: revert useSessionStorage > useLocalStorage

apps/docs/src/reference/composables/useBreadcrumb.md
=> docs: add a clear button to usebreadcrumb.md

packages/bootstrap-vue-next/src/composables/useCountdown.ts, packages/bootstrap-vue-next/src/composables/useFormCheck.ts, packages/bootstrap-vue-next/src/composables/useId.ts
=> refactor: simplify composables toRef logic

packages/bootstrap-vue-next/src/components/BPopover.vue
Zero value is a valid configuration for offset property, we should use it
=> fix(BPopover): zero value is a valid configuration for offset property

packages/bootstrap-vue-next/package.json, packages/nuxt/package.json
=> chore: add funding & other meta to package.json

packages/bootstrap-vue-next/package.json, packages/nuxt/package.json
=> chore: fix repository property in package.jsons

.github/workflows/npm-publish-main.yaml, .github/workflows/npm-publish-nuxt.yaml, .github/workflows/release-main.yaml, package.json
=> chore: update pnpm

packages/bootstrap-vue-next/src/utils/booleanish.ts
=> refactor: simplify resolveBooleanish logic

apps/docs/.vitepress/theme/Layout.vue, apps/docs/src/components/TableOfContentsNav.vue
Thought this was ready for a PR:
1. Uses offcanvas and toggle
2. On collapse it adds extra nav links
3. Add a nav link component to create all the links
4. Works as designed for desktop and small screen sizes
Note: not sure the best way to hide offcanvas on router nav click. Right now you can click through to everything but you need to manually close the offcanvas.
I think this adds a much improved UI experience.
Looking forward to your feedback.
=> Offcanvas TOC nav

apps/docs/.vitepress/theme/Layout.vue, packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue, packages/bootstrap-vue-next/src/components/BTabs/BTabs.vue, packages/nuxt/src/utils/parseActiveImports.ts
=> docs: minor fixes and improvements

apps/docs/.vitepress/theme/Layout.vue
=> docs: client only offcanvas

apps/docs/.vitepress/theme/Layout.vue
=> Made the toc nav links and offcanvas smaller

apps/docs/.vitepress/theme/Layout.vue, apps/docs/src/index.md
=> Removed Nuxt3 from intro

apps/playground/src/components/Comps/TOffcanvas.vue, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
This PR adds the props below:
* header-class
* footer-class
* body-class
* shadow
* bg-variant
* text-variant
=> added b-offcanvas props

packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
Fix toggle offcanvas with `v-b-toggle` directive.
```html
<b-offcanvas id="main-menu">
...
</b-offcanvas>
<b-link v-b-toggle.main-menu>
...
</b-link>
```
=> fix(BOffcanvas): toggle offcanvas with toggle directive.

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
=> fixed BTable provider pagination

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
Fixed slot data of BTable for #391
=> Fixed BTable slot data

apps/docs/.vitepress/theme/Layout.vue
Moved 'on this page' to an off canvas for better usability.
Also removed the toggle to use v-b-toggle instead.
=> Added sidebar right for 'on this page'

packages/bootstrap-vue-next/src/components/BLink/BLink.vue
Additionally to route navigation and collapse event, fire click event on e.g. `BListGroupItem` for additional custom event handling.
```vue
<BListGroup>
<BListGroupItem @click="handleClick" :to="{ name: 'my-route' }">
My List Group Item
</BListGroupItem>
</BListGroup>
```
=> feat(BLink): adds clicked to click event.

packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue, packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckboxGroup.vue, packages/bootstrap-vue-next/src/components/BFormFile/BFormFile.vue, packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue, packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue, packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadioGroup.vue, packages/bootstrap-vue-next/src/components/BFormSelect/BFormSelect.vue, packages/bootstrap-vue-next/src/components/BFormTags/BFormTags.vue, packages/bootstrap-vue-next/src/components/BFormTextarea/BFormTextarea.vue
=> fix: defineExpose focus and blur on Input items

README.md, apps/docs/README.md, apps/docs/src/data/components/accordion.data.ts, apps/docs/src/docs/components/accordion.md, apps/docs/src/docs/components/button.md, apps/docs/src/docs/components/card.md, apps/docs/src/docs/components/form-group.md, apps/docs/src/docs/components/form.md, apps/docs/src/docs/components/link.md, apps/docs/src/docs/components/spinner.md, apps/docs/src/docs/composables.md, apps/docs/src/docs/composables/useBreadcrumb.md
=> docs: PascalCase

packages/bootstrap-vue-next/src/composables/useFormCheck.ts
=> refactor(useFormCheck): toValue instead of toRef

apps/docs/.vitepress/theme/Layout.vue, apps/docs/src/docs/components/collapse.md, apps/docs/src/docs/components/form-group.md, apps/docs/src/docs/components/form-input.md, apps/docs/src/docs/components/form-radio.md, apps/docs/src/docs/components/form-select.md, apps/docs/src/docs/components/form-tags.md, apps/docs/src/docs/components/form-textarea.md, apps/docs/src/docs/components/form.md, apps/docs/src/docs/components/image.md, apps/docs/src/docs/components/input-group.md, apps/docs/src/docs/components/navbar.md, apps/docs/src/docs/components/offcanvas.md, apps/docs/src/docs/components/overlay.md, apps/docs/src/docs/components/pagination.md, apps/docs/src/docs/components/progress.md, apps/docs/src/docs/components/spin-button.md, apps/docs/src/docs/components/spinner.md, apps/docs/src/docs/reference/color-variants.md, apps/docs/src/docs/reference/router-links.md, apps/playground/src/components/Comps/TBLink.vue, apps/playground/src/components/Comps/TNavbar.vue, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue, packages/bootstrap-vue-next/src/composables/useSafeScrollLock.ts
=> docs: fix bprogress documentation replaced with bplaceholder fixes #1238 

apps/docs/src/docs/composables/useColorMode.md
=> docs: fix hydration issue

packages/bootstrap-vue-next/src/components/BPopover.vue, packages/bootstrap-vue-next/src/components/BTooltip.vue
Programmatically open, close and toggle `BPopover` component.
```
<BPopover
ref="popover"
:click="true"
target="popover-button"
title="popover"
>
Hello
<BButton @click="handleClose">Close</BButton>
</BPopover>
.
.
.
const popover = ref()
const handleClose = (event: Event) => popover.value.hideFn(event)
```
Solves #1242 
=> feat(BPopover): expose hide, show and toggle methods

packages/bootstrap-vue-next/src/components/BPopover.vue, packages/bootstrap-vue-next/src/components/BTooltip.vue
=> fix: build issue

packages/bootstrap-vue-next/package.json
=> fix(package): EXPORTS_TYPES_SHOULD_BE_FIRST

packages/bootstrap-vue-next/src/components/BAvatar/BAvatar.vue
Add normal link `href` and router `to` support based on `BLink`.
See #1249.
Using property `href`:
```vue
<BAvatar
src="https://placekitten.com/300/300"
size="5rem"
href="/my-link"
/>
```
Using router property `to`:
```vue
<BAvatar
src="https://placekitten.com/300/300"
size="5rem"
:to="{ path: '/my-link', query: { l: 'en' } }"
/>
```
=> feat(BAvatar): link and router support.

apps/docs/.vitepress/config.ts
=> docs: SEO meta tags

apps/docs/.vitepress/theme/Layout.vue, apps/docs/src/index.md
=> docs: ul list did not only contain li children

apps/docs/.vitepress/config.ts, apps/docs/package.json, pnpm-lock.yaml
=> docs: add sitemap functionality

apps/docs/.vitepress/config.ts, pnpm-lock.yaml
=> docs: fix hostname for sitemap

packages/bootstrap-vue-next/src/composables/useTableItems.ts
=> chore: code standardization

packages/bootstrap-vue-next/src/composables/useTableItems.ts, packages/bootstrap-vue-next/src/utils/object.ts
=> refactor: simplify some toString logic

packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
fixes https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1291
https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31940190/70cdc4dd-f18d-42b7-8a4c-f4721a7c61e6
=> fix(BDropdown): dropdown not automatically flipping

apps/docs/.vitepress/theme/Layout.vue
- Fixed the initial breakout issue
- Tightened the padding for icons as there was way too much
- On the page is now on a new line where it should have been to begin with, better logic
=> Better UI for smaller devices for otp

apps/docs/src/components/TableOfContentsNav.vue
=> b-link to was missing from TOC

apps/playground/src/components/Comps/TForm.vue, packages/bootstrap-vue-next/src/App.vue, packages/bootstrap-vue-next/src/components/BAvatar/BAvatarGroup.vue, packages/bootstrap-vue-next/src/components/BCarousel/BCarousel.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-next/src/components/BForm/BForm.vue, packages/bootstrap-vue-next/src/components/BForm/BFormInvalidFeedback.vue, packages/bootstrap-vue-next/src/components/BForm/BFormValidFeedback.vue, packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckboxGroup.vue, packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadioGroup.vue, packages/bootstrap-vue-next/src/components/BFormTags/BFormTag.vue, packages/bootstrap-vue-next/src/components/BInputGroup/BInputGroupAddon.vue, packages/bootstrap-vue-next/src/components/BInputGroup/BInputGroupAppend.vue, packages/bootstrap-vue-next/src/components/BInputGroup/BInputGroupPrepend.vue, packages/bootstrap-vue-next/src/components/BModal.vue, packages/bootstrap-vue-next/src/components/BNav/BNavForm.vue, packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue, packages/bootstrap-vue-next/src/components/BNavbar/BNavbar.vue, packages/bootstrap-vue-next/src/components/BPopover.vue, packages/bootstrap-vue-next/src/components/BProgress/BProgress.vue, packages/bootstrap-vue-next/src/components/BProgress/BProgressBar.vue, packages/bootstrap-vue-next/src/components/BTable/BTable.vue, packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue, packages/bootstrap-vue-next/src/components/BTable/BTableSimple.vue, packages/bootstrap-vue-next/src/directives/BPopover.ts, packages/bootstrap-vue-next/src/directives/BTooltip.ts, packages/bootstrap-vue-next/src/types/ComponentProps.ts, packages/bootstrap-vue-next/src/utils/floatingUi.ts
=> multiple changes

packages/bootstrap-vue-next/src/components/BModal.vue
=> feat(BModal): passify modelValue

packages/bootstrap-vue-next/src/components/BImg.vue, packages/bootstrap-vue-next/src/components/BProgress/BProgressBar.vue
=> refactor: useToNumber

packages/bootstrap-vue-next/src/components/BPopover.vue
close #1352 
align with bootstrap.js functionality.
=> fix(BPopover): check if focus is on trigger #1352

packages/bootstrap-vue-next/src/directives/BToggle.ts, packages/bootstrap-vue-next/src/directives/toggle.spec.ts
=> feat(BToggle): Add collapsed/not-collapsed classes (#1353)

packages/bootstrap-vue-next/src/components/BModal.vue, packages/bootstrap-vue-next/src/components/BOverlay/BOverlay.vue
=> Adiantek patch 1

packages/bootstrap-vue-next/src/composables/useFormInput.ts
=>  fix(useFormInput): event issues not working as intended fixes #1089 

packages/bootstrap-vue-next/src/components/BCarousel/BCarouselSlide.vue
=> feat(BCarouselSlide): add prop imgSrcset

packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue, packages/bootstrap-vue-next/src/components/BFormFile/BFormFile.vue, packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue, packages/bootstrap-vue-next/src/components/BFormSelect/BFormSelect.vue, packages/bootstrap-vue-next/src/components/BFormTags/BFormTags.vue, packages/bootstrap-vue-next/src/components/BFormTextarea/BFormTextarea.vue
Add input to defineExpose on the other elements also
closes #1363
=> Add input to expose on all form elements

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
This PR fixes a type in BTable
=> fixed BTable table-classes typo

packages/bootstrap-vue-next/src/components/BAvatar/BAvatar.vue, packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue, packages/bootstrap-vue-next/src/components/BFormTextarea/BFormTextarea.vue, packages/bootstrap-vue-next/src/components/BOverlay/BOverlay.vue, packages/bootstrap-vue-next/src/components/BTable/helpers/filter-event.ts, packages/bootstrap-vue-next/src/utils/event.ts, packages/bootstrap-vue-next/src/utils/sanitizer.ts, release-please-config.json
=> feat: link versions of nuxt and main package

packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue
add menuitem role to BDropdownItem.vue
Fix #1412
=> Add role to BDropdownItem.vue

packages/bootstrap-vue-next/src/directives/BToggle.ts, packages/bootstrap-vue-next/src/directives/toggle.spec.ts, packages/bootstrap-vue-next/tests/utils.ts
Implements support for reactively updated targets, matching bootstrap-vue's behavior.
See unit test.
=> feat(BToggle): Reactive targets

apps/playground/.eslintrc.cjs, apps/playground/src/components/Comps/TFormRadio.vue, apps/playground/src/components/Comps/TFormRadioGroup.vue, packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue, packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckboxGroup.vue, packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue
closes #1382 
closes #1278 
The unchecked value caused a little headache, but hopefully this is ok.
=> Fix checkbox array and radio primitives

packages/bootstrap-vue-next/src/components/BModal.vue, packages/bootstrap-vue-next/src/components/BNav/BNavForm.vue, packages/bootstrap-vue-next/src/components/BNav/nav-form.spec.ts
=> fix(BNavForm): incorrect grid classes causing issues fixes #1410  fix(BModal): scoped slots fixes #1418

packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue, packages/bootstrap-vue-next/src/components/BCollapse.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue, packages/bootstrap-vue-next/src/components/BLink/BLink.vue, packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue, packages/bootstrap-vue-next/src/components/BNavbar/BNavbar.vue, packages/bootstrap-vue-next/src/types/ComponentProps.ts, packages/bootstrap-vue-next/src/utils/keys.ts
fix(BNavItemDropdown): all props and emits from dropdown
closes #1393 
feat(BNavbar): add auto-close to disable collapse closing
closes #1283
=> Navbar fixes

packages/bootstrap-vue-next/src/components/BModal.vue, packages/bootstrap-vue-next/src/types/SharedSlotsData.ts
=> Revert "chore: try changes"

apps/docs/src/docs/components/dropdown.md
Correct `BDropdown` align start & end props.
=> docs: Correct Dropdown start & end props

packages/bootstrap-vue-next/.eslintrc.cjs, packages/bootstrap-vue-next/src/components/BTable/BTable.vue, packages/bootstrap-vue-next/src/composables/useModalManager.ts
chore: outlaw forbidden null assertion
chore: lint
=> refactor: return void on some functions

apps/playground/src/components/Comps/TTable.vue, packages/bootstrap-vue-next/src/components/BFormSpinbutton/BFormSpinbutton.vue, packages/bootstrap-vue-next/src/composables/useModal.ts, packages/bootstrap-vue-next/src/composables/useModalManager.ts
=> refactor: function => arrow function

packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue, packages/bootstrap-vue-next/src/components/BPopover.vue
=> fix: use 'floatingStyles' over manual styles

apps/playground/src/components/Comps/TPopover.vue, packages/bootstrap-vue-next/src/components/BPopover.vue
Add noninteractive prop to close directly on pointerleave and blur.
=> feat(BPopover): add noninteractive prop

apps/docs/src/docs/components/toast.md
=> docs: grammar

apps/docs/src/docs/components/dropdown.md, packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-next/src/components/BDropdown/dropdown.spec.ts, packages/bootstrap-vue-next/src/types/ComponentProps.ts
Add ability to "move" dropdown to a container, like tooltip and popover.
=> feat(BDropdown): Add container prop to dropdown

packages/bootstrap-vue-next/package.json
I think we should export the whole src directory.
=> package.json export src

apps/docs/src/components/TableOfContentsNav.vue, apps/docs/src/docs.md, apps/docs/src/docs/components/toast.md, apps/docs/src/docs/composables.md, apps/docs/src/docs/composables/useToast.md, apps/docs/src/docs/icons.md, package.json, packages/bootstrap-vue-next/src/components/BPopover.vue, packages/bootstrap-vue-next/src/components/BTooltip.vue, packages/bootstrap-vue-next/src/composables/useToast.ts, packages/bootstrap-vue-next/src/types/ComponentProps.ts
=> feat(BTooltip): add type interfaces for BPopover props

packages/bootstrap-vue-next/src/components/BTable/BTable.vue, packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue, packages/bootstrap-vue-next/src/components/BTable/BTableSimple.vue, packages/bootstrap-vue-next/src/types/ComponentProps.ts
=> feat(BTable): striped columns

apps/docs/src/docs/composables/useToast.md, packages/bootstrap-vue-next/src/composables/useToast.ts
=> fix: toast global sharing

apps/playground/src/App.vue, packages/bootstrap-vue-next/src/components/BTable/BTable.vue
=> fix(BTable): fix reactivity when using mapping

apps/docs/src/docs/composables/useToast.md
fix: correct useToast doc title
not needed
- [ x] Documentation update - `docs(...)`
- [ x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**
=> fix: correct useToast doc title

packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
=> feat(BDropdown): add keyboard navigation

packages/bootstrap-vue-next/src/components/BModal.vue, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
=> fixed BOffcanvas and BModal hide event

apps/docs/.vitepress/theme/Layout.vue, packages/bootstrap-vue-next/.eslintrc.cjs, packages/bootstrap-vue-next/src/components/BModal.vue, packages/bootstrap-vue-next/src/components/BPopover.vue
chore(eslint): no-console turned to error
docs(layout.vue): toRef => computed
fix(BM0dal): defineExpose of id not reactive
=> refactor(BPopover): code cleanup

packages/bootstrap-vue-next/src/components/BAvatar/BAvatar.vue, packages/bootstrap-vue-next/src/components/BBadge/BBadge.vue, packages/bootstrap-vue-next/src/components/BBreadcrumb/BBreadcrumbItem.vue, packages/bootstrap-vue-next/src/components/BButton/BButton.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue, packages/bootstrap-vue-next/src/components/BLink/BLink.vue, packages/bootstrap-vue-next/src/components/BListGroup/BListGroupItem.vue, packages/bootstrap-vue-next/src/components/BNav/BNavItem.vue, packages/bootstrap-vue-next/src/components/BNavbar/BNavbarBrand.vue, packages/bootstrap-vue-next/src/components/BPopover.vue, packages/bootstrap-vue-next/src/components/BToast/BToast.vue, packages/bootstrap-vue-next/src/types/ComponentProps.ts
=> fix(BLink): missing prop, bad class inheritance, other minor changes

apps/docs/src/docs.md
Only remove dead link in get started page
=> docs: remove dead link in get started page

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
=> perf(BTable): use Array.some instead of filter().length

packages/bootstrap-vue-next/src/components/BModal.vue, packages/bootstrap-vue-next/src/composables/useModalManager.ts
=> fix(BModal): active position when prop id changed not working

packages/bootstrap-vue-next/src/components/BCollapse.vue, packages/bootstrap-vue-next/src/directives/BToggle.ts
=> Collapse animation fix

apps/playground/index.html, packages/bootstrap-vue-next/index.html
=> chore: remove runtime message in dev about missing favicon

apps/docs/src/data/components/modal.data.ts
I filled out the slots section of the BModal documentation, which is now visible thanks to @dploc96's work.  I based this on the original bsv documentation, but checked it against the code and did some light testing to validate that the documentation is correct.
N/A
=> docs(BModal): complete slots section of component reference

packages/nuxt/package.json, pnpm-lock.yaml
=> chore: package update

packages/bootstrap-vue-next/.eslintrc.cjs
=> chore: make eslint stricter for ts any & alerting

packages/bootstrap-vue-next/src/components/BPlaceholder/BPlaceholderButton.vue, packages/bootstrap-vue-next/src/components/BPlaceholder/BPlaceholderCard.vue, packages/bootstrap-vue-next/src/components/BTable/BTable.vue
fix(BPlaceholderCard): pointer: wait for img
=> fix(BPlaceholderButton): pointwer: wait fixes #1602

packages/bootstrap-vue-next/src/types/exports/index.ts
=> feat: expose toast type

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
=> fix(BTable): current page not working causing no pagination fixes #1613

packages/bootstrap-vue-next/src/components/BImg.vue
=> perf(BImg): improve blank img resolution

packages/bootstrap-vue-next/src/components/BDropdown/BDropdownForm.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdownText.vue, packages/bootstrap-vue-next/src/components/BDropdown/dropdown-form.spec.ts, packages/bootstrap-vue-next/src/components/BDropdown/dropdown-text.spec.ts
remove custom padding, margins and align with bootstrap
bind $attrs to inner element
set item variant default to null
closes #1616 
=> BDropdown: cleanup items

packages/bootstrap-vue-next/src/types/ComponentProps.ts
=> chore: remove dead code

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
=> fix(BTable): double fetch of provider when using filter fixes #1635

packages/bootstrap-vue-next/src/components/BButton/BButton.vue
=> Fixed BButton useBLinkHelper propeties

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
=> fix table filter without filterable

packages/bootstrap-vue-next/src/components/BFormSelect/BFormSelect.vue, packages/bootstrap-vue-next/src/components/BFormTextarea/BFormTextarea.vue, packages/bootstrap-vue-next/src/composables/useFormInput.ts
=> allow null in inputs

apps/docs/src/data/components/accordion.data.ts
Updated BAccoridion documentation.
=> docs(BAccordion): update component reference

apps/docs/src/data/components/modal.data.ts
Change the description for shown event
fix #1677
https://stackblitz.com/edit/github-vf39ah?file=src%2FApp.vue
=> docs(BModal): Shown event has incorrect timing

packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue
Fixes #1716 
As old BV the PR writes an hidden row when a detail row is opened in order to preserve table striped color
=> fixed table detail row color when striped

apps/docs/src/docs/components/toast.md, apps/docs/src/docs/composables/useModalController.md, apps/docs/src/docs/composables/useToast.md
Wrapping the `setInterval` in the SFC setup in a `inBrowser` check solves the infinite loop, see [this comment](https://github.com/vuejs/vitepress/issues/562#issuecomment-1106061640) in the vitepress issue queue. I was able to build the docs successfully locally without an infinite loop. 
Fixes #1702.
=> fix(docs): build infinite loop

apps/docs/src/docs.md
=> fix docs mismatch

packages/nuxt/playground/app.vue, packages/nuxt/src/runtime/plugins/createBootstrap.ts
=> fix(nuxt): defineNuxtPlugin is not defined fixes #1741

apps/docs/src/docs/reference.md, apps/docs/src/docs/reference/color-variants.md, apps/docs/src/docs/reference/form-validation.md, apps/docs/src/docs/reference/settings.md, apps/docs/src/docs/reference/size-props-and-classes.md, apps/docs/src/docs/reference/spacing-classes.md, apps/docs/src/docs/reference/starter-templates.md, apps/docs/src/docs/reference/theming-bootstrap.md, apps/docs/src/docs/reference/third-party-libraries.md, apps/docs/src/docs/reference/utility-classes.md
Add pages (without content) for the dead links
fix #1173
=> docs: remove dead links

.github/workflows/docs-deploy.yaml
=> ci: have docs deploy on release, not any push fixes #1735

packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
=> fix(BDropdown): calculate size after displaying the dropdown.

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
- Fixes asc/desc local sorting
- ```no-local-sorting``` props added
=> fixed btable local sort and added no-local-sorting prop

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
Fix BTable selection single mode
=> fixed BTable single selection

packages/bootstrap-vue-next/src/composables/useFormSelect.ts
Allow arrays of numbers or dates to BFormSelect
fixes #1838
=> fix(BFormSelect): array of numbers or dates

.github/workflows/docs-deploy.yaml
=> ci: add workflow dispatch to docs deploy

packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadioGroup.vue
=> fix(BFormRadioGroup) fix reverse

packages/bootstrap-vue-next/src/components/BTable/BTable.vue, packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue, packages/bootstrap-vue-next/src/components/BTable/table-lite.spec.ts, packages/bootstrap-vue-next/src/components/BTable/table.spec.ts, packages/bootstrap-vue-next/src/utils/object.ts
=> table fixes

packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue
=> fixed BTableLite item _showDetails

packages/bootstrap-vue-next/src/types/exports/index.ts, packages/nuxt/playground/app.vue, packages/nuxt/playground/nuxt.config.ts, packages/nuxt/src/module.ts, packages/nuxt/src/runtime/createBootstrap.ts, packages/nuxt/src/types/ModuleOptions.ts
=> feat(nuxt): allow passthrough options to createBootstrap plugin

packages/bootstrap-vue-next/src/components/BTabs/BTab.vue
=> fix(BTab): use correct buttonId

packages/bootstrap-vue-next/src/types/ComponentProps.ts
=> chore: fix type issue

apps/docs/src/docs/directives/BTooltip.md
Improved English and clarity of explanation
Improved the English of the explanation
=> docs(BTooltip): Improve English

packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-next/src/components/BDropdown/dropdown.spec.ts, packages/bootstrap-vue-next/src/components/BInputGroup/BInputGroup.vue, packages/bootstrap-vue-next/src/components/RenderComponentOrSkip.vue, packages/bootstrap-vue-next/src/types/ComponentProps.ts, packages/bootstrap-vue-next/src/utils/keys.ts
fixes #1907 
fix(BDropdown): fix wrapper class, skip wrapper in input-group
feat(BDropdown): add skipWrapper and wrapperClass props
=> Dropdown input group fixes

packages/bootstrap-vue-next/src/components/BOverlay/BOverlay.vue
=> fix(BOverlay): fix noWrap

package.json, packages/bootstrap-vue-next/package.json, packages/bootstrap-vue-next/src/components/BModal/BModal.vue, packages/bootstrap-vue-next/src/components/BModal/modal.spec.ts, pnpm-lock.yaml
=> fix(BMOdal): append transition behavior fixes #1943

packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue
=> fix(BTableLite): value slot scope not using formatItem fixes #1805

packages/bootstrap-vue-next/src/components/BTable/BTable.vue, packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue
=> feat(BTable)!: remove selected event -- use @update:selectedItems

packages/bootstrap-vue-next/src/components/BAvatar/BAvatar.vue
=> fix(BAvatar): use parentData.square for computedSquare fixes #1923

packages/bootstrap-vue-next/src/BootstrapVue.ts
Add missing plugins exports from main BootstrapVue.ts
- [ x] Feature - `feat(...)`
- [ x] Pull request title and all commits follow the [**Conventional Commits**](https://www.conventionalcommits.org/) convention or has an [**override**](https://github.com/googleapis/release-please#how-can-i-fix-release-notes) in this pull request body **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type. Pull requests that do not follow conventional commits or do not have an override will be denied**
=> feat: export plugins from main module

packages/bootstrap-vue-next/src/components/BToast/BToast.vue
Using the headerClass property in a BToast, fixes #1977.
=> fix(BToast): use headerClass

apps/docs/src/docs/components/offcanvas.md, packages/bootstrap-vue-next/package.json, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue, packages/bootstrap-vue-next/src/types/ComponentProps.ts, packages/bootstrap-vue-next/vite.config.mts, pnpm-lock.yaml
feat(dist): dont include src files
feat(package): move vueuse integrations and focus trap to dev dependencies
feat(BOffcanvas): add prop responsive
=> fix(types): mjs masquerading as cjs -- export mts copy

packages/bootstrap-vue-next/src/components/BTabs/BTab.vue
Fixes: #1984
https://stackblitz.com/edit/bootstrap-vue-next-bug-b-tab
=> fix(b-tab): broken computed classes

packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue
=>  feat(BTableLite): add class to bottom row tr fixes #1908 

apps/docs/src/data/components/form.data.ts, apps/docs/src/docs/components/form.md, apps/docs/src/docs/migration-guide.md, apps/playground/src/components/Comps/TForm.vue
- Add a section for BForm to migration-guide
- Fix bugs in the inline form example
- Add an example for single control form with `floating` applied
- Add in component documentation for `floating` property
Docs
=> docs(BForm): Add migration section and fix some bugs

apps/docs/src/data/components/modal.data.ts
- Set the initial value to `bootstrap-vue`
[A clear and concise description of what the pull request does.](https://bootstrap-vue.org/docs/components/modal)
=> fix(BModal): change the initial value of okTitle to OK

apps/docs/src/data/components/accordion.data.ts, apps/docs/src/data/components/alert.data.ts, apps/docs/src/data/components/avatar.data.ts, apps/docs/src/data/components/badge.data.ts, apps/docs/src/data/components/breadcrumb.data.ts, apps/docs/src/data/components/button.data.ts, apps/docs/src/data/components/card.data.ts, apps/docs/src/data/components/carousel.data.ts, apps/docs/src/data/components/collapse.data.ts, apps/docs/src/data/components/dropdown.data.ts
Attempts to update the component reference information of a small number of components to align with the specified prop types and defaults.
=> docs: Update component reference information

apps/docs/src/data/components/formSpinbutton.data.ts, apps/docs/src/docs/migration-guide.md, apps/docs/src/utils/common-props.ts
Fill out the component reference for spinbutton. In the process I validated the existing docs (did not find any issues) and updated the parity report.
N/A
=> doc(BFormSpinbutton): Fill out component reference and validate docs

CONTRIBUTING.md, apps/docs/src/data/components/formCheckbox.data.ts, apps/docs/src/data/components/formFile.data.ts, apps/docs/src/data/components/formInput.data.ts, apps/docs/src/data/components/formRadio.data.ts, apps/docs/src/data/components/formSelect.data.ts, apps/docs/src/data/components/formSpinbutton.data.ts, apps/docs/src/data/components/formTags.data.ts, apps/docs/src/data/components/formTextarea.data.ts, apps/docs/src/data/components/gridSystem.data.ts, apps/docs/src/data/components/image.data.ts, apps/docs/src/data/components/link.data.ts, apps/docs/src/data/components/listGroup.data.ts, apps/docs/src/data/components/modal.data.ts, apps/docs/src/data/components/nav.data.ts, apps/docs/src/data/components/navbar.data.ts, apps/docs/src/data/components/offcanvas.data.ts, apps/docs/src/data/components/overlay.data.ts, apps/docs/src/data/components/pagination.data.ts, apps/docs/src/data/components/placeholder.data.ts, apps/docs/src/data/components/popover.data.ts, apps/docs/src/data/components/progress.data.ts, apps/docs/src/data/components/table.data.ts, apps/docs/src/data/components/tabs.data.ts, apps/docs/src/data/components/toast.data.ts
Update component references to try and bring documentation for prop availability + types into line with the prop typing & components.
=> docs: Update component references

packages/bootstrap-vue-next/src/components/BModal/BModal.vue, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue, packages/bootstrap-vue-next/src/composables/useActivatedFocusTrap.ts
=> fix(focus-trap): focus trap issues with modal and offcanvas fixes #2064

packages/bootstrap-vue-next/src/App.vue, packages/bootstrap-vue-next/src/components/BFormFile/BFormFile.vue, packages/bootstrap-vue-next/src/components/BTable/BTable.vue, packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue, packages/bootstrap-vue-next/src/types/ComponentProps.ts, packages/bootstrap-vue-next/src/types/TableTypes.ts
=> fix(Table): various functional syntaxes in attrs & classes fixes #2083

apps/docs/src/data/components/alert.data.ts, apps/docs/src/docs/components/alert.md, apps/docs/src/docs/migration-guide.md, apps/playground/src/components/Comps/TAlert.vue
Update the docs to be consistent with the code.
Write the migration section for `BAlert`
Update the parity spreadsheet
N/A
=> doc(BAlert): Parity and cleanup pass

apps/docs/src/data/components/inputGroup.data.ts, apps/docs/src/docs/components/input-group.md, apps/docs/src/docs/migration-guide.md
Clean up and verify documentation for BInputGroup. Fix a number of bugs in the docs. Write the migration guide. Update the Parity Spreadsheet.
N/A
- [] Bugfix :bug: - `fix(...)`
=> docs(BInputGroup): Clean up docs and fill out component reference

apps/docs/src/data/components/accordion.data.ts, apps/docs/src/docs/components/accordion.md
Updated docs for BAccordian and component references for BAccordian and BAccordianItem.
Also updated the parity spreadsheet.
N/A
=> doc(BAccordian): Update docs and component reference

packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue
add prop class to row details!
=> fix(BTable): add prop class to row details

packages/bootstrap-vue-next/src/components/BModal/BModal.vue, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue, packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue, packages/bootstrap-vue-next/src/composables/useActivatedFocusTrap.ts
=>  feat(useActivatedFocusTrap): set better fallback options fixes #2095 

apps/docs/src/components/ComponentReference.vue, apps/docs/src/data/components/avatar.data.ts, apps/docs/src/types/index.ts, apps/docs/src/utils/link-props.ts
=> docs: add optional link to extended component references

apps/docs/src/data/components/link.data.ts, apps/docs/src/docs/components/link.md, apps/docs/src/docs/migration-guide.md, apps/docs/src/docs/reference/router-links.md, apps/docs/src/utils/link-props.ts
- Updated component reference
- Fixed bugs in documentation
- Added documentation for the new styling props
- Updated migration guide
- Updated parity spreadsheet
N/A
=> docs(BLink): Update docs and component reference for parity pass

packages/nuxt/src/module.ts
=> chore: indicate compatibility with nuxt v4

apps/docs/src/data/components/breadcrumb.data.ts, apps/docs/src/docs/components/breadcrumb.md, apps/docs/src/docs/migration-guide.md
- Clean up pass on docs
- Fill out component reference for BBreadcrumb and BBreadcrumbItem
- Update the migration guide
- Update the parity spreadsheet
N/A
=> doc(BBreadcrumb): Parity pass

apps/docs/src/data/components/buttonGroup.data.ts, apps/docs/src/docs/components/button-group.md
- Fill out component reference
- Small tweaks to the docs
- Update the parity report
N/A
=> doc(BButtonGroup): Fill out component reference

apps/docs/src/docs/migration-guide.md, apps/docs/src/index.md
=> docs: fix typo of composible

apps/docs/src/data/components/buttonToolbar.data.ts, apps/docs/src/docs/migration-guide.md
- Check docs (no errors found)
- Update component reference
- Update parity spreadsheet
N/A
=> doc(BButtonToolbar): Parity pass

apps/docs/src/data/components/pagination.data.ts, apps/docs/src/docs/components/demo/PaginationAlignment.vue, apps/docs/src/docs/components/demo/PaginationButtonContent.vue, apps/docs/src/docs/components/demo/PaginationButtonSize.vue, apps/docs/src/docs/components/demo/PaginationFirstLast.vue, apps/docs/src/docs/components/demo/PaginationOverview.vue, apps/docs/src/docs/components/demo/PaginationPillStyle.vue, apps/docs/src/docs/components/pagination.md, apps/docs/src/docs/migration-guide.md, apps/docs/src/docs/types.md
This is the parity pass for the BPagination component
- Went through docs and cleaned them up
- Refactored examples into the demo directory
- Updated types
- Update migration guide
- Updated the parity spreadsheet
- Added bugs for missing features
N/A
=> docs(BPagination): Update Component refs & clean up documentation

packages/bootstrap-vue-next/src/components/BTabs/BTab.vue, packages/bootstrap-vue-next/src/components/BTabs/BTabs.vue, packages/bootstrap-vue-next/src/types/Tab.ts
=> fix(BTabs): fix recursion on titleLinkAttrs

packages/bootstrap-vue-next/src/components/BNav/BNavItem.vue
Passes the `exactActiveClass` prop to the router  component
=> fix(BNavItem): pass prop exactActiveClass to router component

packages/bootstrap-vue-next/src/components/BCarousel/BCarousel.vue, packages/bootstrap-vue-next/src/types/ComponentProps.ts
=> feat(BCarousel): add noAnimation prop

packages/bootstrap-vue-next/src/types/TableTypes.ts
=> fix(BTable): Type check failed for prop tbodyTrClass fixes #2197

apps/docs/src/data/components/accordion.data.ts, apps/docs/src/data/components/button.data.ts, apps/docs/src/data/components/card.data.ts, apps/docs/src/docs/composables/useBreadcrumb.md, apps/docs/src/docs/composables/useColorMode.md, apps/docs/src/docs/composables/useModal.md, apps/docs/src/docs/composables/useModalController.md, apps/docs/src/docs/composables/useToast.md, apps/docs/src/docs/directives/BColorMode.md, apps/docs/src/docs/directives/BModal.md, apps/docs/src/docs/directives/BPopover.md, apps/docs/src/docs/directives/BToggle.md, apps/docs/src/docs/directives/BTooltip.md, packages/bootstrap-vue-next/src/composables/useRadiusElementClasses.ts, packages/nuxt/src/runtime/createBootstrap.ts
refactor(useRadiusElementClasses): better type
refactor(nuxt): correct import path, remove unused import
=> docs: fix paths

packages/bootstrap-vue-next/src/components/ConditionalWrapper.vue
=> fix(ConditionalWrapper): don't inherit attrs

packages/bootstrap-vue-next/src/directives/BPopover/index.ts, packages/bootstrap-vue-next/src/directives/BTooltip/index.ts
=> fix(vBPopover): fix vue error with floating directives.

packages/bootstrap-vue-next/src/components/BFormFile/BFormFile.vue, packages/bootstrap-vue-next/src/components/BFormFile/form-file.spec.ts
=> fix(BFormFile): remove capture attrs from dom if not defined.

packages/bootstrap-vue-next/src/composables/useId.ts, packages/bootstrap-vue-next/src/utils/bvnPrefix.ts, packages/bootstrap-vue-next/src/utils/keys.ts
=>  fix(nuxt): make injection keys static strings fixes #2209 

packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue, packages/bootstrap-vue-next/src/composables/useActivatedFocusTrap.ts
=>  fix(useFocusTrap): dont deactivate focus on esc fixes #2144 

packages/bootstrap-vue-next/src/components/BModal/modal.spec.ts, packages/bootstrap-vue-next/src/composables/useSafeScrollLock.ts
I added a "lockRegistry" so that if we have multible locks, lifting one doesn't "lift" all.
closes #1953
=> fix(BModal): fix jumping when scrollbars are present

packages/bootstrap-vue-next/src/components/BTable/BTable.vue, packages/bootstrap-vue-next/src/components/BTable/table.spec.ts
=> fix(BTable): select mode range when table is sorted fixes #2229

apps/docs/src/data/components/collapse.data.ts, apps/docs/src/docs/components/collapse.md, apps/docs/src/docs/components/demo/CollapseContent.vue, apps/docs/src/docs/components/demo/CollapseExpose.vue, apps/docs/src/docs/components/demo/CollapseInitial.vue, apps/docs/src/docs/components/demo/CollapseModel.vue, apps/docs/src/docs/components/demo/CollapseMultiple.vue, apps/docs/src/docs/components/demo/CollapseOverview.vue, apps/docs/src/docs/components/demo/CollapseUsage.vue, apps/docs/src/docs/migration-guide.md
- Parity pass on the documents
- Write migration guide section
- Refactor example components
- Update parity spreadsheet
N/A
=> docs(BCollapse): Parity pass

packages/bootstrap-vue-next/src/components/BTable/BTable.vue, packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue, packages/bootstrap-vue-next/src/types/TableTypes.ts
feat(BTable): add row-contextmenu event fixes #2238
feat(BTable): add row-middle-clicked event
refactor(BTable): remove duplicate emit definitions
=> fix(BTable)!: rename event row-dbl-clicked to row-dblclicked

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
=>  fix(BTable): cast formatted items to string fixes #2227 

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
=>  fix(BTable): busy slot behavior to match bootstrap-vue fixes #1636 

packages/bootstrap-vue-next/src/utils/floatingUi.ts
=> fix(vBPopover): revert #2234

packages/bootstrap-vue-next/src/components/BPopover/BPopover.vue, packages/bootstrap-vue-next/src/composables/useMouse.ts, packages/bootstrap-vue-next/src/types/ComponentProps.ts
feat(BPopover): add prop hideMargin
=> fix(BPopover): calculate mouse and element positions in a performant way

packages/bootstrap-vue-next/src/components/BModal/BModal.vue
=> fix(BModal): fix backdrop click prevention, fix flickering when no-fade

packages/bootstrap-vue-next/src/components/BDropdown/BDropdownDivider.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdownForm.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdownHeader.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdownText.vue, packages/bootstrap-vue-next/src/components/BDropdown/dropdown-form.spec.ts, packages/bootstrap-vue-next/src/components/BDropdown/dropdown-header.spec.ts, packages/bootstrap-vue-next/src/components/BDropdown/dropdown-text.spec.ts, packages/bootstrap-vue-next/src/types/ComponentProps.ts
=> feat(BDropdown): add variant, classes and correct attrs to text sub components

apps/docs/src/data/components/dropdown.data.ts, apps/docs/src/docs/components/demo/DropdownForm.vue, apps/docs/src/docs/components/demo/DropdownInlineForm.vue, apps/docs/src/docs/components/dropdown.md, apps/docs/src/docs/demo/DropdownHeader.html, apps/docs/src/docs/demo/DropdownHeader.vue, apps/docs/src/docs/migration-guide.md
Update the docs & migration guide based on the changes in #2258
Also updated the parity spreadsheet to keep it in sync.
N/A
=> docs(BDropdown): Fill out component references for subcomponents

apps/docs/src/data/components/dropdown.data.ts, apps/docs/src/data/components/modal.data.ts, apps/docs/src/docs/components/form-group.md, apps/docs/src/docs/components/navbar.md, apps/docs/src/docs/components/table.md, apps/playground/src/components/Comps/TTable.vue, packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue, packages/bootstrap-vue-next/src/components/BFormInput/_form-input.scss, packages/bootstrap-vue-next/src/components/BInputGroup/_input-group.scss, packages/bootstrap-vue-next/src/components/BModal/BModal.vue, packages/bootstrap-vue-next/src/types/ComponentProps.ts
=> clean classes and scss

packages/bootstrap-vue-next/src/components/BModal/BModal.vue, packages/bootstrap-vue-next/src/composables/useSafeScrollLock.ts, packages/bootstrap-vue-next/src/composables/useScrollLock.ts
=> fix(BModal): multiple modals backdrop fix

packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue, packages/bootstrap-vue-next/src/components/BFormTextarea/BFormTextarea.vue, packages/bootstrap-vue-next/src/composables/useFormInput.ts, packages/bootstrap-vue-next/src/utils/normalizeInput.ts
=> fix(BFormInput): bad model modifier trim behavior fixes #2253

packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue
=> fix(BFormCheckbox): indeterminate state fixes #2271

packages/bootstrap-vue-next/src/composables/useSafeScrollLock.ts
=> fix(BModal): remove scrolllock on unmount

packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue, packages/bootstrap-vue-next/src/components/BFormCheckbox/form-checkbox.spec.ts
=> test: form checkbox indeterminate behavior

packages/bootstrap-vue-next/src/components/BAvatar/BAvatar.vue
=> fix(BAvatar): failback on image load error

apps/docs/src/data/components/listGroup.data.ts, apps/docs/src/docs/components/demo/ListGroupActionable.vue, apps/docs/src/docs/components/demo/ListGroupActionableButton.vue, apps/docs/src/docs/components/demo/ListGroupActionableVariants.vue, apps/docs/src/docs/components/demo/ListGroupActive.vue, apps/docs/src/docs/components/demo/ListGroupBadges.vue, apps/docs/src/docs/components/demo/ListGroupCard.vue, apps/docs/src/docs/components/demo/ListGroupCheckbox.vue, apps/docs/src/docs/components/demo/ListGroupCustom.vue, apps/docs/src/docs/components/demo/ListGroupDisabled.vue, apps/docs/src/docs/components/demo/ListGroupHorizontal.vue, apps/docs/src/docs/components/demo/ListGroupHorizontalMd.vue, apps/docs/src/docs/components/demo/ListGroupNumbered.vue, apps/docs/src/docs/components/demo/ListGroupNumberedCustom.vue, apps/docs/src/docs/components/demo/ListGroupOverview.vue, apps/docs/src/docs/components/demo/ListGroupRadio.vue, apps/docs/src/docs/components/demo/ListGroupVariants.vue, apps/docs/src/docs/components/list-group.md, apps/docs/src/docs/migration-guide.md
- Refactored examples
- Filled out component reference
- Added documentation for the new feature checkboxes & radios in ListGroup
- Filled out parity spreadsheet
N/A
=> docs(BFormListGroup): Parity pass

apps/docs/src/data/components/gridSystem.data.ts, apps/docs/src/docs/components/demo/ColBreakpoints.vue, apps/docs/src/docs/components/demo/ColEqualMultiline.vue, apps/docs/src/docs/components/demo/ColEqualWidth.vue, apps/docs/src/docs/components/demo/ColMixed.vue, apps/docs/src/docs/components/demo/ColNesting.vue, apps/docs/src/docs/components/demo/ColOffset.vue, apps/docs/src/docs/components/demo/ColOffsetClear.vue, apps/docs/src/docs/components/demo/ColOneWidth.vue, apps/docs/src/docs/components/demo/ColOrder.vue, apps/docs/src/docs/components/demo/ColSpacing.vue, apps/docs/src/docs/components/demo/ColStackedToHorizontal.vue, apps/docs/src/docs/components/demo/ColVariableWidth.vue, apps/docs/src/docs/components/demo/ContainerCellAlignment.vue, apps/docs/src/docs/components/demo/ContainerDefault.vue, apps/docs/src/docs/components/demo/ContainerFluid.vue, apps/docs/src/docs/components/demo/ContainerHorizontalAlignment.vue, apps/docs/src/docs/components/demo/ContainerResponsive.vue, apps/docs/src/docs/components/demo/ContainerVerticalAlignment.vue, apps/docs/src/docs/components/demo/GridOverview.vue, apps/docs/src/docs/components/demo/RowCol.vue, apps/docs/src/docs/components/demo/RowColResponsive.vue, apps/docs/src/docs/components/grid-system.md, apps/docs/src/docs/migration-guide.md
Parity pass for the grid system:  `BContainer`, `BRow`, `BCol`
- Completed the documentation
- Updated the migration guide
- Filled out the component reference
- Updated the parity report
N/A
=> docs(grid): Parity pass

packages/bootstrap-vue-next/src/components/BCarousel/BCarousel.vue, packages/bootstrap-vue-next/src/components/BCarousel/BCarouselSlide.vue, packages/bootstrap-vue-next/src/components/BCarousel/carousel-slide.spec.ts, packages/bootstrap-vue-next/src/components/BCarousel/carousel.spec.ts, packages/bootstrap-vue-next/src/types/ComponentProps.ts
=> feat(BCarousel): add aria attributes, add prop labelIndicators

packages/bootstrap-vue-next/src/components/BTable/BTable.vue, packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue, packages/bootstrap-vue-next/src/types/ComponentProps.ts
=> feat(BTable): add defineSlots types

packages/bootstrap-vue-next/src/composables/useSafeScrollLock.ts
=> fix useSafeScrollLock in docs/ssr/ssg

apps/docs/src/docs/components/demo/TextareaAutoHeight.vue, apps/docs/src/docs/components/demo/TextareaDebounce.vue, apps/docs/src/docs/components/demo/TextareaDisplayedRows.vue, apps/docs/src/docs/components/demo/TextareaFloatingLabels.vue, apps/docs/src/docs/components/demo/TextareaFormatter.vue, apps/docs/src/docs/components/demo/TextareaOverview.vue, apps/docs/src/docs/components/demo/TextareaProperties.vue, apps/docs/src/docs/components/demo/TextareaReadonly.vue, apps/docs/src/docs/components/demo/TextareaResizeHandle.vue, apps/docs/src/docs/components/demo/TextareaSizing.vue, apps/docs/src/docs/components/demo/TextareaStates.vue, apps/docs/src/docs/components/form-textarea.md, apps/docs/src/utils/common-props.ts
- Added in the Auto Height Section
- Refactored the examples
N/A
=> docs(BFormTextarea): Update auto height section + refactor

apps/docs/src/docs/components/pagination.md, packages/bootstrap-vue-next/src/components/BPagination/BPagination.vue, packages/bootstrap-vue-next/src/styles/styles.scss
Resolve https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2154. Related to the changes of `media-breakpoint-down` in bootstrap 5 (https://getbootstrap.com/docs/5.3/migration/#sass)
=> feat(BPagination): add small screen support

packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
fix https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2312
=> fix(BFormGroup): fix layout problem when label-for is not used

apps/docs/src/docs/components/pagination.md, packages/bootstrap-vue-next/src/components/BFormSpinbutton/BFormSpinbutton.vue, packages/bootstrap-vue-next/src/components/BPagination/BPagination.vue, packages/bootstrap-vue-next/src/utils/constants.ts, packages/bootstrap-vue-next/src/utils/dom.ts, packages/bootstrap-vue-next/src/utils/event.ts
resolve https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2153
=> feat(BPagination): add keyboard shortcuts

packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
=> fix(BDropdown): fix infinite loop on keyboard navigation

packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue, packages/bootstrap-vue-next/src/components/BImg/BImg.vue
feat(BDropdown): id for split and menu elements
feat(BFromGroup): add class b-form-group
feat(BImg): add class b-img
@dwgray @VividLemon think of any other elements that would require a class or id for sub elements?
=> add some classes and ids for components

packages/bootstrap-vue-next/src/components/BPagination/BPagination.vue
fixed a small merge error from previous pr's
=> fix merge error

apps/docs/.vitepress/theme/Layout.vue, apps/docs/package.json, apps/docs/src/index.md, packages/bootstrap-vue-next/src/components/BModal/BModal.vue, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue, packages/bootstrap-vue-next/src/components/BPopover/BPopover.vue, packages/bootstrap-vue-next/src/composables/useShowHide.ts, pnpm-lock.yaml
=> Fix-backdrop-flicker

packages/bootstrap-vue-next/src/components/BCollapse/BCollapse.vue, packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-next/src/components/BModal/BModal.vue, packages/bootstrap-vue-next/src/components/BModal/modal.spec.ts, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue, packages/bootstrap-vue-next/src/components/BPopover/BPopover.vue, packages/bootstrap-vue-next/src/components/BToast/BToast.vue, packages/bootstrap-vue-next/src/composables/useShowHide.ts
=> fix(useShowHide): fix visible prop, better initial render

packages/bootstrap-vue-next/src/composables/useModal/index.ts
=> fix useModal for lazy modals

packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItemButton.vue
=> fix(BDropdownItemButton): prevent click on disabled button

packages/bootstrap-vue-next/src/components/BPagination/BPagination.vue
The issue here was that we had two watches, one on `modelValueNumber` and one on `pagination` that both set the model value to keep it within the constraints of pagination. The watch on `pagination` was firing first and causing the `modelValueNumber` to be run twice within one update cycle, yielding incorrect results.
Instead, I'm handling the model invariant by making a computed model rather than using a watch.
See #2414 
=> bug(BPagination): Correct reactivity of model when pagination changes - addresses #2414 

apps/docs/src/docs/components/badge.md
Fix two links in the Badge documentation
n/a
=> docs: fix links in Badge documentation

apps/docs/src/data/components/spinner.data.ts, apps/docs/src/docs/components/demo/SpinnerBorder.vue, apps/docs/src/docs/components/demo/SpinnerButtons.vue, apps/docs/src/docs/components/demo/SpinnerColors.vue, apps/docs/src/docs/components/demo/SpinnerFlex.vue, apps/docs/src/docs/components/demo/SpinnerFloats.vue, apps/docs/src/docs/components/demo/SpinnerGrowButtons.vue, apps/docs/src/docs/components/demo/SpinnerGrowing.vue, apps/docs/src/docs/components/demo/SpinnerMargin.vue, apps/docs/src/docs/components/demo/SpinnerOverview.vue, apps/docs/src/docs/components/demo/SpinnerSize.vue, apps/docs/src/docs/components/demo/SpinnerSmall.vue, apps/docs/src/docs/components/demo/SpinnerTextAlign.vue, apps/docs/src/docs/components/spinner.md
- Complete the docs
- Refactor the examples
- Fill out Component Reference
- Fill out the parity report
- 
N/A
=> docs(BSpinner): Parity pass

apps/docs/src/data/components/offcanvas.data.ts, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
=> feat(BOffcanvas): add opened to breakpoint event

apps/docs/src/components/HighlightCard.vue, apps/docs/src/data/components/formCheckbox.data.ts, apps/docs/src/docs/components/demo/CheckboxArray.ts, apps/docs/src/docs/components/demo/CheckboxButton.vue, apps/docs/src/docs/components/demo/CheckboxButtonGroup.vue, apps/docs/src/docs/components/demo/CheckboxCustomFields.vue, apps/docs/src/docs/components/demo/CheckboxExample1.vue, apps/docs/src/docs/components/demo/CheckboxExample2.vue, apps/docs/src/docs/components/demo/CheckboxIndeterminate.vue, apps/docs/src/docs/components/demo/CheckboxInline.vue, apps/docs/src/docs/components/demo/CheckboxModel.vue, apps/docs/src/docs/components/demo/CheckboxNoLabel.vue, apps/docs/src/docs/components/demo/CheckboxObjectArray.ts, apps/docs/src/docs/components/demo/CheckboxObjectArrayNormalized.ts, apps/docs/src/docs/components/demo/CheckboxObjectArrayRaw.ts, apps/docs/src/docs/components/demo/CheckboxPlain.vue, apps/docs/src/docs/components/demo/CheckboxReverse.vue, apps/docs/src/docs/components/demo/CheckboxSize.vue, apps/docs/src/docs/components/demo/CheckboxSwitch.vue, apps/docs/src/docs/components/demo/CheckboxSwitchGroup.vue, apps/docs/src/docs/components/demo/CheckboxSwitchSize.vue, apps/docs/src/docs/components/demo/CheckboxTriState.vue, apps/docs/src/docs/components/demo/CheckboxValidation.vue, apps/docs/src/docs/components/form-checkbox.md
- refactor the examples
- small tweak to HighlightCard to make code fragments cleaner
- clean up warnings/errors that showed up with linting turned on
- remove references to the `html` prop and add a pointer to the migration guide
- remove empty scope arrays from component reference
N/A
=> docs(BFormCheckbox): Refactor examples

apps/docs/src/data/components/offcanvas.data.ts, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
=> feat(BOffcanvas): fire breakpoint on mounted & add ref into defineExp

packages/bootstrap-vue-next/src/components/BLink/BLink.vue, packages/bootstrap-vue-next/src/composables/useBLinkHelper.ts, packages/bootstrap-vue-next/src/utils/stringUtils.ts, packages/nuxt/playground/nuxt.config.ts
=> fix(BLink): nuxt should do full page reloads on to prop fixes #2445

apps/docs/src/components/ComponentReference.vue, apps/docs/tsconfig.node.json
Chipping away at typescript errors in docs
=> docs: Fix typescript errors in ComponentRef

packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
=> fix(BFormGroup): floating labels not working fixes #2452

packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
=> fix: last commit label issue

apps/docs/src/docs.md, packages/bootstrap-vue-next/package.json, packages/nuxt/playground/app.vue
=> chore: optional peer dependencies note #fixes #2442

apps/docs/src/data/components/tabs.data.ts, apps/docs/src/docs/migration-guide.md
- Fill out component reference
- Update parity report
- Updated #2383 with a couple of more small issues that I found while doing the above
N/A
=> docs(BTabs): Complete Component Reference

apps/docs/package.json, apps/playground/package.json, packages/bootstrap-vue-next/package.json, pnpm-lock.yaml
=> feat: use vueuse 12 fixes #2469

apps/docs/src/docs/components/badge.md, apps/docs/src/docs/components/demo/BadgeActionable.vue, apps/docs/src/docs/components/demo/BadgeBackgroundColors.vue, apps/docs/src/docs/components/demo/BadgeButtons.vue, apps/docs/src/docs/components/demo/BadgeDotIndicator.vue, apps/docs/src/docs/components/demo/BadgeHeadings.vue, apps/docs/src/docs/components/demo/BadgePill.vue, apps/docs/src/docs/components/demo/BadgePositioned.vue
- Refactor examples into their own files
- Fix issues that showed when linting is enabled
N/A
=> docs(BBadge): Refactor examples

apps/docs/src/docs/components/form-group.md, packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue, packages/bootstrap-vue-next/src/components/BFormGroup/form-group.spec.ts, packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue, packages/bootstrap-vue-next/src/components/BFormTextarea/BFormTextarea.vue, packages/bootstrap-vue-next/src/composables/useFormCheck.ts, packages/bootstrap-vue-next/src/composables/useFormInput.ts, packages/bootstrap-vue-next/src/types/FormCommonInputProps.ts, packages/bootstrap-vue-next/src/utils/keys.ts
=> feat(BFormGroup): automatically add state to child element fixes #2476

apps/docs/src/docs/migration-guide.md
Add the migration guide for slots related to the BModal component (#2486)
You can check it with this URL, docs/migration-guide.html#bmodal
=> docs(migration-guide): added slots migration for BModal

apps/docs/src/docs/components/demo/FormGroupFloatingLabels.vue, apps/docs/src/docs/components/demo/FormGroupHorizontalLayout.vue, apps/docs/src/docs/components/demo/FormGroupId.vue, apps/docs/src/docs/components/demo/FormGroupLabelSize.vue, apps/docs/src/docs/components/demo/FormGroupNested.vue, apps/docs/src/docs/components/demo/FormGroupOverview.vue, apps/docs/src/docs/components/demo/FormGroupState.vue, apps/docs/src/docs/components/form-group.md
- Refactor examples into their own files
- Fix up issues revealed when linting is enabled
- Add some padding to improve the appearance
- Fix a broken link
N/A
=> docs(BFormGroup): Refactor form-group examples into separate files

apps/docs/src/data/components/toast.data.ts, apps/docs/src/docs/components/demo/TableSort.vue, apps/docs/src/docs/components/demo/TableSortBy.vue, apps/docs/src/docs/components/demo/TableSortByMulti.vue, packages/bootstrap-vue-next/src/types/index.ts
- BTable Examples
- I introduced these in #2492 - for some reason VSCode wasn't showing me the errors, restarting seemed to solve it though
- I am exporting `LiteralUnion` rather than redefining it in the example as per #2484 
- BToast data  - I'm correctly referencing the link properties
N/A
=> doc: Fix more typescript errors

apps/docs/src/docs/components/demo/FormInputDatalist.vue, apps/docs/src/docs/components/demo/FormInputDebounce.vue, apps/docs/src/docs/components/demo/FormInputFormatter.vue, apps/docs/src/docs/components/demo/FormInputMethods.vue, apps/docs/src/docs/components/demo/FormInputOverview.vue, apps/docs/src/docs/components/demo/FormInputRange.vue, apps/docs/src/docs/components/demo/FormInputRangeStep.vue, apps/docs/src/docs/components/demo/FormInputSize.vue, apps/docs/src/docs/components/demo/FormInputState.vue, apps/docs/src/docs/components/demo/FormInputStateLive.vue, apps/docs/src/docs/components/demo/FormInputTypes.vue, apps/docs/src/docs/components/form-input.md
- Refactor examples into their own files
- Fix up issues revealed when linting is enabled
N/A
=> docs(BFormInput): refactor examples

apps/docs/src/data/components/table.data.ts
- update the comment reference
- update the parity spreadsheet
N/A
=> docs(BTableSimple): fill out component reference

apps/docs/src/docs/components/demo/FormDataHelper.vue, apps/docs/src/docs/components/demo/FormFeedbackHelper.vue, apps/docs/src/docs/components/demo/FormFloatingLabels.vue, apps/docs/src/docs/components/demo/FormInline.vue, apps/docs/src/docs/components/demo/FormInlineSelect.vue, apps/docs/src/docs/components/demo/FormOverview.vue, apps/docs/src/docs/components/demo/FormSingleFloat.vue, apps/docs/src/docs/components/demo/FormTextHelper.vue, apps/docs/src/docs/components/form.md
- Refactor the examples
- Fix issues that came up with linting enabled
- Small tweaks to formatting
=> docs(BForm): Refactor examples

apps/docs/src/docs/components/demo/TableCellVariants.vue, apps/docs/src/docs/components/demo/TableFieldArray.vue, apps/docs/src/docs/components/demo/TableFieldObjects.vue, apps/docs/src/docs/components/demo/TableFields.ts, apps/docs/src/docs/components/demo/TableItems.ts, apps/docs/src/docs/components/demo/TableOverview.vue, apps/docs/src/docs/components/table.md, apps/docs/src/docs/migration-guide.md, apps/docs/src/docs/types.md
- Fill out these sections of the Table docs.
- Continue to build the outline of the doc so we don't have hanging references
- Update migration guide with issues found
- Create bugs for issues found
N/A
=> docs(BTable): Overview, Items, Fields, Primary Key

apps/docs/src/docs/icons.md
=> fix: update dead link

apps/playground/src/components/Comps/TTable.vue, packages/bootstrap-vue-next/src/components/BTable/BTable.vue
- fix typescript errors in BTable
- fix typescript error in TTable
N/A
=> fix(BTable): Fix typescript errors

apps/docs/src/docs/components/demo/InputGroupCheckboxSize.vue, apps/docs/src/docs/components/demo/InputGroupCustomCheckbox.vue, apps/docs/src/docs/components/demo/InputGroupDropdown.vue, apps/docs/src/docs/components/demo/InputGroupMultipleAddons.vue, apps/docs/src/docs/components/demo/InputGroupMultipleInputs.vue, apps/docs/src/docs/components/demo/InputGroupNativeCheckbox.vue, apps/docs/src/docs/components/demo/InputGroupOverview.vue, apps/docs/src/docs/components/demo/InputGroupSizing.vue, apps/docs/src/docs/components/demo/InputGroupSlots.vue, apps/docs/src/docs/components/demo/InputGroupText.vue, apps/docs/src/docs/components/demo/InputGroupXPend.vue, apps/docs/src/docs/components/input-group.md
- move examples to their own files
- fix issues that came up with linting & typescript
- cleaned up notes sections
N/A
=> docs(BInputGroup): Refactor examples

packages/bootstrap-vue-next/src/composables/useModalManager.ts
=> fix(useModalManager): use correct value in comparison

packages/bootstrap-vue-next/src/components/BPopover/BPopover.vue
=> fix(BPopover): popover breaks flex layouts

packages/bootstrap-vue-next/src/components/BAvatar/_avatar.scss
Add "!default" to $b-avatar-border-color, so its can be overwritten.
=> fix(b-avatar): Add "!default" to $b-avatar-border-color

apps/docs/src/docs/components/demo/FormTagsBasic.vue, apps/docs/src/docs/components/demo/FormTagsCustom.vue, apps/docs/src/docs/components/demo/FormTagsDropdown.vue, apps/docs/src/docs/components/demo/FormTagsEvents.vue, apps/docs/src/docs/components/demo/FormTagsLimit.vue, apps/docs/src/docs/components/demo/FormTagsNative.vue, apps/docs/src/docs/components/demo/FormTagsRemoval.vue, apps/docs/src/docs/components/demo/FormTagsScopedSlot.vue, apps/docs/src/docs/components/demo/FormTagsSelect.vue, apps/docs/src/docs/components/demo/FormTagsSeparators.vue, apps/docs/src/docs/components/demo/FormTagsState.vue, apps/docs/src/docs/components/demo/FormTagsStyle.vue, apps/docs/src/docs/components/demo/FormTagsValidation.vue, apps/docs/src/docs/components/demo/FormTagsWrapper.vue, apps/docs/src/docs/components/form-tags.md, apps/docs/src/docs/migration-guide.md
- Refactor examples into their own files
- Fix several of the advanced examples (addresses #2505 and the first part of #2049)
- Update the migration guide
N/A
=> docs(BFormTags): Refactor and fix examples

apps/docs/src/docs/components/demo/TableEmpty.vue, apps/docs/src/docs/components/table.md, apps/docs/src/docs/migration-guide.md
Document the `empty-text` and `empty-filtered-text` slots.
N/A
=> docs(BTable): Document the empty slots

apps/docs/src/docs/components/overlay.md
=> docs: remove deprecated number prop and use model modifier instead

.github/workflows/ci.yaml, .github/workflows/docs-deploy.yaml, .github/workflows/npm-publish-main.yaml, .github/workflows/npm-publish-nuxt.yaml, .github/workflows/release-main.yaml
=> ci: update ci

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
=> fix(BTable): multi sort wiping comparer function

packages/bootstrap-vue-next/src/components/BPopover/BPopover.vue
=> fix(BPopover): don't calculate the position when popover is not shown.

packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue, packages/bootstrap-vue-next/src/utils/floatingUi.ts
=> fix(BDropdown): point caret the right way

apps/playground/src/components/Comps/TCarousel.vue, apps/playground/src/components/Comps/TTable.vue, packages/bootstrap-vue-next/package.json, packages/bootstrap-vue-next/src/main.ts, packages/bootstrap-vue-next/src/plugins/createBootstrap/index.ts, packages/bootstrap-vue-next/src/types/BootstrapVueOptions.ts, packages/bootstrap-vue-next/vite.config.mts
=> fix: augment global components for IDE inferences fixes #2534

apps/docs/src/docs/components/table.md, apps/docs/src/docs/migration-guide.md
- add the `filtering` section to the docs
- update the migration guide
- add unimplemented props to #2521
N/A
=> docs(BTable): Add the filtering section

packages/bootstrap-vue-next/src/composables/useShowHide.ts
=> fix(useShowHide): render based on initialState, fixes ssr on showhide components

CONTRIBUTING.md, README.md, apps/docs/src/docs.md, apps/docs/src/docs/migration-guide.md
=> docs: fix bootstrap-vue links

packages/bootstrap-vue-next/src/components/BPopover/BPopover.vue, packages/bootstrap-vue-next/src/composables/useShowHide.ts
=> fix(BPopover): cancel show/hide during delay

apps/docs/src/docs/components/table.md, apps/docs/src/docs/migration-guide.md
- fill out several sections of the docs
- update the migration guide
- create bugs for missing features
N/A
=> doc(BTable): Fill out light-weight, helper component and accessibility sections

apps/docs/src/docs/components/button.md, apps/docs/src/docs/components/demo/ButtonOutlineVariants.vue
When investigating #2637 I realized that I left an inline example in `button.md`, this PR fixes that.
N/A
=> docs(BButton): Outline variant example

apps/docs/src/docs/components/demo/TableComplete.vue, apps/docs/src/docs/components/demo/TableSortByCustom.vue, apps/docs/src/docs/components/demo/TableSortCompareDefault.ts, apps/docs/src/docs/components/table.md, apps/docs/src/docs/migration-guide.md, packages/bootstrap-vue-next/src/components/BTable/BTable.vue
- Expose `getStringValue` and `displayedItems`
- Document the above + all the other exposed functions
- Create examples
- Update the migration guide
N/A
=> feat(BTable): Expose additional functions and document them

apps/docs/src/data/components/modal.data.ts, apps/docs/src/data/components/offcanvas.data.ts, packages/bootstrap-vue-next/src/components/BModal/BModal.vue, packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue, packages/bootstrap-vue-next/src/composables/useActivatedFocusTrap.ts, packages/bootstrap-vue-next/src/types/ComponentProps.ts, packages/bootstrap-vue-next/src/utils/getElement.ts
feat(BModal)!: remove autofocus and autofocusButton props and add mor…e versitile focus prop
feat(BOffcanvas)!: remove nofocus prop and add more versitile focus prop
feat(BModal): return focus to previous element on close
feat(BOffcanvas): return focus to previous element on close
fix(BModal): set focus only once
closes #2540
=> Better focus for trapped components.
