bootstrap-vue-next/bootstrap-vue-next

src/composables/useFormCheck.ts

fixes #41 by preventing the togle on the label when disabled

Fixes #41 : disabled BFormCheckbox can still be toggled

---

src/components/BFormCheckbox/BFormCheckbox.vue
src/components/BFormCheckbox/form-checkbox.spec.js

Fixes #43
I fixed it by forcing an id attribute on the input and using a for attribute on the label.
By using the for attribute, events on the label (click, focus, blur) can be removed because when the label receives focus, it passes the focus to it's associated control.

Fix #43 : BFormCheckbox does't emit the change event when label clicked

---

docs/.vuepress/config.ts
docs/.vuepress/styles/index.scss
docs/components/FormCheckbox.md
docs/components/README.md
docs/reference/parityList.md

Preliminary documentation for BFormCheckbox
Remarks :
- v-model does not seem to work, so this is not mentioned yet
- as stated in #46 , the plain property seems to work opposite of bootstrap-vue. Documentation reflects the behavior of bootstrap-vue-3
- size property is available, but not implemented. So documented as strike-through. Can be removed if this project is not going to implement the size property
Request :
- Can anybody show me how to implement script in markdown. I would like to include display of the current checked value like the doc of bootstrap-vue.

Documentation for BFormCheckbox

---

docs/.vuepress/clientAppEnhance.js
package.json
public/index.html
scripts/deploy.sh
vite.config.ts

`yarn run build` builds the lib using vite now
If really needed, `common.js` could also be built: https://vitejs.dev/config/#build-lib

remove vue-cli support; fix #33

---

src/App.vue
src/components/BFormCheckbox/BFormCheckbox.vue
src/components/BFormRadio/BFormRadio.vue
src/components/BFormRadio/form-radio.spec.js
src/composables/useFormCheck.ts

v-model support for form radio
Does not work well in grouping, but that's expected when multiple component change the same model.
I think a grouping component like b-form-group or b-form-radio-group is needed

fix: v-model support for form radio

---

src/components/BFormRadio/form-radio.spec.js

This fixes 3 of the 4 failing unit-tests
The tests are failing because vue-test-utils cannot handle v-model. See [#279](https://github.com/vuejs/vue-test-utils-next/discussions/279)
The fix implements a workaround by handling the update:modelValue event.
Note : 1 test is still failing, but this is an implementation issue. I've created an issue for it. See #72

Fix: Fixes for unittest BFormRadio

---

src/components/BFormCheckbox/form-checkbox.spec.js
src/components/BFormCheckboxGroup.vue
src/components/BFormRadio/BFormRadio.vue
src/components/BFormRadio/form-radio.spec.js

The former implementation gave the ability for BFormRadio bound to an array to select multiple value, which did not comply with the "standard" bootstrap-vue behaviour.
This PR fix this issue (https://github.com/cdmoro/bootstrap-vue-3/issues/73)

fix BFormRadio bound to an array + handle BFormChexboxGroup required property + fix BFormRadio warning when bound to an object

---

src/components/index.ts

BDropdownGroup and BDropdownItemButton are not available because they are not exported

BDropdownGroup and BDropdownItemButton not exported

---

src/App.vue
src/components/BDropdown.vue
src/components/BFormRadio/index.ts
src/components/BIcon.vue
src/components/BTable/itemHelper.ts
src/components/BTabs.vue
src/utils/stringUtils.ts

Those fixes are required to be able to use `bootstrap-vue-3` in a typescript project.
NB: I had to remove the "autoClose" feature of the dropdown for now

fix typescript compilation errors

---

src/components/BDropdown.vue

Always set class btn-group on wrapper div
Removed the dropdown class because it only set position relative and class btn-group already sets position relative

By default BDropdown should display inline instead of stacked

---

package.json

Execute the "build" task (which generate the `/dist` folder) when the project is installed directly from github (ex: `npm i https://github.com/cdmoro/bootstrap-vue-3`)
Currently it is only executed when the project is installed from the npm registry (ex: `npm i bootstrap-vue-3`)

always execute the "build" task on post install

---

src/BootstrapVue.d.ts
src/components/BTabs.vue

support for "mixed" tabs, ex:
```
<b-tabs>
<b-tab title="First" active><p>First</p></b-tab>
<b-tab title="Second"><p>Second</p></b-tab>
<b-tab v-for="(tabName, tabIndex) in ['Third', 'Fourth']" :title="tabName" :key="tabIndex">{{ tabName }}</b-tab>
<b-tab title="Fifth"><p>Fifth</p></b-tab>
</b-tabs>
```

add support for "mixed" tabs in BTabs default slots

---

src/App.vue

After previous PR App.vue doesn't run anymore because BDropdown files are moved
This fixes this

fix for app.vue after folder cleanup

---

src/App.vue
src/components/BPopover.vue

I implemented the correction needed by the component to work properly with a ref element.
close  #225

Feature [BPopover component]: Can use a ref instead of a string id for the target

---

src/components/BAccordion.vue
src/components/BAccordionItem.vue

Problem: Accordion default behaviour (without free property) was not collapsing when other accordion buttons are clicked. 
i.e. it is behaving like it has the free property 
Fix: Minor fix to binding properties in BAccordionItem. v-binding to "accordion" instead of "parent", 
removal of extra "#" during injection

Fix: Accordion default behaviour not collapsing when clicking on other accordion header

---

src/components/BPopover.vue

- It does now work with basic HTMLElements like buttons or divs
closes #237

Fix [BPopover Component]: Target didn't accept basic HTMLElements

---

src/components/BDropdown/BDropdown.vue
src/components/BModal.vue

The following error occurs when you try to import and use individual components.
```
[Vue warn]: Failed to resolve component: b-button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```
Related Issue: #188 #194

Reduce dependence on global components

---

src/directives/BTooltip.ts

Hi, first of all thanks for making this project. I just made a basic implementation to add the `delay` option to the tooltip directive so by using something like : `v-b-tooltip="{ delay: 100 }"` or `v-b-tooltip="{ delay:  { "show": 500, "hide": 100 }  }` the delay options works.
This implementations is really basic, it **doesn't** implement mods like `d###` or `ds###` to use them like `v-b-tooltip.d100` for example.
I need this option implemented for one of my projects so if i have to change something please let me know.

Added basic tooltip-directive delay feature

---

src/components/BFormSelect/BFormSelectOption.vue

When values in the :value of the option element contain null or undefined, it doesn't create value="", instead, it ignores the attribute. Thus causing incorrect reading of null values when switching to a value with null, and mounting with null as default value. Simply null-checking the value prop and assigning an empty string safely adds in an empty value attribute for correct targeting.

Issue#124 incorrect values when using null value

---

docs/components/Card.md
src/App.vue

no-gutters was changed to g-0 in the bootstrap v4 -> v5 change.
https://getbootstrap.com/docs/5.1/layout/gutters/
This PR addresses this change.
Note: Prettier also found some extra spaces.

no-gutters changed to class="g-0" as per BSv5

---

src/components/BContainer.vue

Hi,
When we try to use a BContainer with fluid, the css class "container-fluid" is reading the padding right/left from --v-gutter-x, so It's applying a default padding that sometimes I want to avoid.
So, we can allow this padding with the parameters like we are doing for BRow.vue component.

Add missing gx-x and gy-x classes for BContainer

---

src/components/BAlert.vue
src/components/BCarousel/BCarousel.vue
src/components/BCollapse.vue
src/components/BDropdown/BDropdown.vue
src/components/BModal.vue
src/components/BOffcanvas.vue
src/components/BPopover.vue
src/directives/BPopover.ts
src/directives/BTooltip.ts
src/main.ts

So, on import bootstrap.js install evenlisteners on every class, data-api, document etc. for every component. So if I import only Modal and use my own Dropdown (but bootstrap style/classes) it still install the events on it.
This just changes the imports to individual components so it doesn't pollute the dom for every component.
also required step if we want to start converting the components to vue components. see #243 and #310

remove import on bootstrap.js, only direct components

---

vite.config.ts

Didn't notice that now the bootstrap js is included in the components:
this fixes that:

add bootstrap js to external

---

src/components/BTabs/BTabs.vue

Clicking on tab scrolls the page to the top.
also I think button is better default for tab. can use slot if you need it to a link.

Remove link on tab, prevent default action

---

docs/components/Tabs.md

There is an issue about this https://github.com/cdmoro/bootstrap-vue-3/issues/339 
The Tabs page was broken in this commit : https://github.com/cdmoro/bootstrap-vue-3/commit/659db8c3d8e282b93b0fc63421ecaf20ce978653#diff-a95a8475083ab01b12bfb1eee84ac3d482c8d0f9c1d01fc190bb733bd7936627 
I reverted to the old version.

docs: fix the tabs reference section

---

package.json
vite.config.ts

Hello, 
I saw an issue https://github.com/cdmoro/bootstrap-vue-3/issues/326 about d.ts file missing.
There is a nice plugin https://github.com/qmhc/vite-plugin-dts that generates declaration files (*.d.ts) from .ts or .vue source files when using vite in [library mode](https://vitejs.dev/guide/build.html#library-mode)
It's very simple, as vite developer experience.
May be we can use it.
Mathieu

feat: generates *.d.ts files from .ts or .vue source

---

src/utils/dom.ts

SSR was broken here https://github.com/cdmoro/bootstrap-vue-3/commit/4ec314f778bf48db161cf33618dd5359acc0473f#diff-22661bb30bb26ab73ab4ec6375682479d6635ce978aaa6b8a3f2ae02e68a9db0R110
Add `HAS_WINDOW_SUPPORT` check

Fix broken ssr

---

src/App.vue
src/components/BFormCheckbox/BFormCheckbox.vue
src/components/BFormCheckbox/BFormCheckboxGroup.vue
src/components/BFormCheckbox/form-checkbox-group.spec.js
src/components/BFormCheckbox/form-checkbox.spec.js
src/components/BFormInput/form-input.spec.js
src/components/BFormRadio/BFormRadio.vue
src/components/BFormRadio/BFormRadioGroup.vue
src/components/BFormRadio/form-radio-group.spec.js
src/components/BFormRadio/form-radio.spec.js
src/components/BFormSelect/BFormSelect.vue
src/components/BFormSelect/form-select.spec.js
src/components/BFormTextarea/form-textarea.spec.js
src/components/BLink/BLink.vue
src/components/BLink/link.spec.js

Using objects in select/checkbox/radio was completely broken. It always matched the first object. I removed some weird hacky stuff and used vue:s native v-model binding for those inputs.
Can you please release this and ssr fix soon, so I don't have to run a fork in production.

Fix select/checkbox/radio with object

---

src/App.vue
src/components/BNavItemDropdown.vue

Hello,
When we use `BNavItemDropdown` it's not possible to pass slot to the `BDropdown`.
I added the possibility to pass slots through from `BNavItemDropdown` to `BDropdown`.
Regards
Mathieu

feat(BNavItemDropdown): pass slots to the child BDropdown

---

docs/getting-started/README.md
nuxt.js
package.json

Implements [support for library authors for nuxt3](https://v3.nuxtjs.org/guide/directory-structure/components/#library-authors)
```
npx nuxi init nuxt-app
cd nuxt-app
npm install
npm run dev -- -o
```
```
npm install bootstrap bootstrap-vue-3
```
Open your `nuxt.config.ts` or `nuxt.config.js` file and configure your application to use `bootstrap-vue-3`. The components will be imported automatically as needed.
```javascript
import {defineNuxtConfig} from 'nuxt3'
export default defineNuxtConfig({
modules: ['bootstrap-vue-3/nuxt'],
css: ['bootstrap/dist/css/bootstrap.css'],
})
```
```vue
<template>
<div>
<BButton variant="primary">Primary</BButton>
<BBadge variant="danger">Danger</BBadge>
</div>
</template>
```

feat: support for library authors for nuxt3

---

src/components/BModal.vue

First PR on this, so apologies if I miss something.
`b-modal` has `ok-variant` and `cancel-variant` to set the button variants.  These aren't working because we have explicit `btn-primary`/`btn-secondary` classes in there.  That means you get both classes inserted, and the primary wins.  We don't need these classes (I think) because `variant` will already ensure the correct one is inserted.

fix: remove variant classes from OK/Cancel buttons

---

docs/components/Alert.md
docs/components/Avatar.md
docs/components/Breadcrumb.md
docs/components/Button.md
docs/components/Collapse.md
docs/components/Form.md
docs/components/FormCheckbox.md
docs/components/Pagination.md
docs/components/Toast.md

Hello,
I saw in the documentation the use of the use of `<ClientOnly>` component around the `<script setup>`, it is confusing.
As explained in the vuepress documentation: https://v2.vuepress.vuejs.org/advanced/cookbook/markdown-and-vue-sfc.html
> Each Markdown file is first compiled into HTML, then converted into a Vue SFC. 
This means that `<ClientOnly>` has no effect on the setup script
A .md like this one would be : 
```md
<ClientOnly>
<BButton :variant="variant"><BButton>
</ClientOnly>
<ClientOnly>
<script setup>
const variant = ref('primary')
</script>
</ClientOnly>
```
to SFC: 
```vue
<template>
<h1>a test page</h1>
<ClientOnly>
<BButton :variant="variant"><BButton>
</ClientOnly>
<ClientOnly></ClientOnly>
</template>
<script setup>
const variant = ref('primary')
</script>
```
To fix …

refactor: remove <ClientOnly> around script setup in .md

---

src/directives/BTooltip.ts

Correct bootstrap implementation is not yet available.
In the meantime this PR is a quick fix for #250 
While it fixes the issue of disappearing tooltip, it is not a perfect fix as the tooltip will fade out and in as opposed to remaining in view throughout

fix: retain tooltip visibility on title update

---

src/components/BAvatar/BAvatarGroup.vue
src/components/BCard/BCardText.vue

- Simplify computeOverlap function to remove redundant local variable.
- Generate script part in BCardText. In other projects, if I use the tag <b-card-text>xx</b-card-text> is not detected.
I'm using IntelliJ 2022.1, I guess the problem should be with the script part (maybe).
Other components are detected well:

Add script component for BCardText in order to help an IDE to detect by naming tags

---

docs/components/README.md

In order to easily manage the progress of the documentation, I coded the list of components to easily add a status todo, work in progress, ...
```js
Modal: {
name: 'Modal',
description: `Add dialogs to your site for lightboxes, user notifications, or completely custom content.`,
status: 'todo'
},
```
it will display a todo badge on the documentation to do

refactor(docs): build the toc with a componentList object

---

.eslintrc.js
package.json
tsconfig.json

The prettier plugin hasn't worked for awhile. A fix in the eslintrc file to include prettier as a plugin, and as a rule fixes prettier not working.
tsconfig file was changed to temporarily fix these two issues revolving around volar plugin: https://github.com/johnsoncodehk/volar/issues/1405 && https://github.com/johnsoncodehk/volar/discussions/592 
The prepare script was causing too many issues. It was preventing packages from being installed and hurting the development process. It should be added later when not so many breaking "vite build" options cause npm install to not install the required packages to actually develop. 
vue-tsc was added for the build command. I'm not sure why this was not already included. But to my understanding it's required for a Vite app using TS to build. In …

Fixed issues revolving around broken packages.

---

tsconfig.json
vite.config.ts

I have been using src/ syntax to import files consistently when building interfaces. As it turns out, TS is able to get all of the information just fine. This worked fine in some interfaces I was building. Tried to use it when building with Vite, and it could not resolve the path. I figured it would be nice to just sidestep all of that and make a handy alias to the src dir.

Add a simple src/ utility alias with @

---

package.json
src/types/components/BFormCheckbox/BFormCheckbox.d.ts
src/types/components/BFormCheckbox/BFormCheckboxGroup.d.ts
src/types/components/BFormRadio/BFormRadio.d.ts
src/types/components/BFormRadio/BFormRadioGroup.d.ts
src/types/components/BFormTags/BFormTag.d.ts

The main reason for the PR was to update package and state some intentions. It also contains some minor fixes in some unused types files. 
I'm going to need to change some tests in the next script setup conversions. BFormCheckbox has contained an error where input v-model cannot be assigned to null. Instead, I opt to use undefined since it's valid and behaves the same. Just the types checks expecting it toBe(null) will always issue out. 
I'm also going to opt to moving the `Array<string>`'s that I have been using to `Array<unknown>` (and retroactively fix the previous ones) as I have encountered some issues with them, and they're usually unknown to _me_. The unknowns will provide a better search ability to make them more explicit in the future as they were basically not strongly typed …

Update vue test utils package

---

src/components/BFormTags/BFormTags.vue
src/types/components/BFormTags/BFormTags.d.ts

BFormTags does not need generic type for tagValidator

---

src/components/BFormCheckbox/BFormCheckbox.vue
src/components/BFormTags/BFormTags.vue

Tag validator now explicit that it takes t?: string instead of unknown -- it was causing an error. I'm still slightly confused about why the error was happening...
The emits interface is now strongly typed to be `Array<string>` instead of unknowns. 
BFormCheckbox value/unchecked value not includes string, records, and number... I presented that they be removed before, but for some reason it seems to properly work now without any errors and allows "any" values just fine. Instead of explicitly using "any", I figured all those explicit types for _value_ are sufficient enough.

BFormCheckbox & BFormTags fixes

---

src/App.vue

Any changes were the result of missing features. If anything seems like it should be included, we will need to add it. 
b-skeleton does not have a boolean value allowed for animation. 
b-form-checkbox (or more <input type="checkbox" />) cannot v-model directly to a string, so that line of examples was removed.
b-row align-h does not have md-center in Alignments.horizontal type
B-table Breakpoints type does not include xs -- I think it just uses boolean value instead.
Items wanted to be a TableItem[]
objectTableDefinitions was erroring out when using = ref<...>, but didn't have an error when using objectTableDefinitions: Ref<> = ... This has to be a bug
tag validator type is string | undefined, 
If anything seems out of place, we can add it.

Fixed app.vue after global component types change

---

.github/workflows/release-please.yml
babel.config.js
package.json

A list of changes and reasoning behind --
standard-version was deprecated and recommended https://github.com/googleapis/release-please for github users instead.
As such, the release script was replaced with a github action demonstrated here https://github.com/marketplace/actions/release-please-action
@vue/compiler-sfc is registered as a direct dependency to Vue , meaning it is no longer required.
Following a brand new "create vite" project, vue was moved as a main dependency. 
Babel and it's surrounding packages was removed. It was causing a bunch of issues with trying to compile Vue code. Babel is not included in a new create vite project, so I figured it could be removed. If one wants to add it back, I believe the best option would be to configure it better - I believe there's a direct …

Removed unnecessary -- and breaking packages

---

src/App.vue
src/components/BFormTags/BFormTags.vue
src/components/BSkeleton/BSkeleton.vue
src/types/SkeletonAnimation.d.ts
src/types/components/BFormTags/BFormTags.d.ts

@VividLemon I have seen your fixes in App.vue (finally it compiles!), but some errors are easy enough to fix in components:
1. It can be seen from the implementation of BFormTags that the parameter passed to tagValidator cannot be null. So it's probably better to reflect this in the types and not force the user of the library to handle such case.
2. In bootstrap-vue "animation" property of BSkeleton component without value corresponds to no animation https://bootstrap-vue.org/docs/components/skeleton#skeleton-animations. I changed the component and type to reflect this behavior.
Do this changes look good to you?

Alternative fixes to App.vue

---

docs/.vuepress/PluginComponentReference/client.ts
docs/.vuepress/PluginComponentReference/client/clientAppEnhance.ts
docs/.vuepress/PluginComponentReference/index.ts
docs/.vuepress/client.ts

I created a client config for the client, to load the component, it's linked to 
https://github.com/vuepress/vuepress-next/blob/eb962a057a91142a46a071896de418bc9903c388/CHANGELOG.md#breaking-changes-1
> core: clientAppEnhanceFiles, clientAppRootComponentFiles and clientAppSetupFiles hooks are removed, use clientConfigFile hook instead

fix(docs): load the component reference inside the plugin

---

.github/workflows/release-please.yml

This is basically a direct copy of https://github.com/google-github-actions/release-please-action#automating-publication-to-npm . It should work since both this and npm-publish workflow both use ${{secrets.NPM_TOKEN}}.

ci(workflow): release please bot to update npm

---

src/App.vue
src/components/BAvatar/BAvatar.vue
src/components/BDropdown/BDropdown.vue
src/components/BFormCheckbox/BFormCheckbox.vue
src/components/BFormRadio/form-radio.spec.js
src/components/BFormSelect/BFormSelect.vue
src/components/BFormSelect/form-select-option.spec.js
src/components/BFormTags/form-tag.spec.js
src/components/BLink/link.spec.js
src/components/BListGroup/list-group-item.spec.js
src/components/BListGroup/list-group.spec.js
src/components/BPagination/BPagination.vue
src/components/BToast/BToast.vue
src/components/BToast/b-toast.spec.js

Hi all,
I review the warnings reported by eslint, and I found that we transform some templates into script setup and we didn't expose some methods.
And also I clean up the rest of warnings.
In src/components/BFormCheckbox/BFormCheckbox.vue I guess the modelValue should have the same values as value, before the script setup tranformation was equal. I guess it was removed some because the <input type="checkbox"> was complaining about using string type, that's why I put a manual casting and return type definition for localValue  computed.
Last point, I review the warnings from test running (there it's where I found the warning from BFormCheckbox.ue) and the test are giving a false positive warning:
```
stderr | src/components/BListGroup/list-group.spec.js > list-group > should have class …
```

Fix: Missing exposed methods using script setup

---

src/components/BCard/BCardBody.vue

The previous #471 was supposed to be subTitleTag, rather than removed outright

fix(BCardBody): subTitleTag typo fix

---

.github/workflows/release-please.yml

Bot was failing to use npm ci due to docs repo inside.

ci(workflow): runs npm i instead of ci

---

src/components/BToast/BToast.vue
src/components/BToast/BToaster.vue

- Make `delay` accessible to the `BToast` component as a prop
- Return the minimum delay to 1000ms (the default delay is still 5000ms)

Make BToast receive `delay` as prop

---

src/directives/BTooltip.ts

Dear community, dear @cdmoro 
I hope you are all well :)
This pull request will add support for Bootstrap 5.2's new Tooltip API using the `Tooltip.setContent()` method for updating the Tooltip.
As a side effect it will also fix a bug with previous versions of `bootstrap-vue-3` using Bootstrap 5.2, which caused an unshown tooltip to flash up when setting its content via the old way on initialization.
Question remains whether we should keep support for Bootstrap 5.1 and lower?
Best regards
Markus

Fix BTooltip updates for Bootstrap 5.2

---

docs/package.json
package.json

This was also fixed in the dev branch, but I might as well add it here. This fix should allow workflows to properly install peerDependencies and close https://github.com/cdmoro/bootstrap-vue-3/issues/467 (This could have also been fixed by having the bot use Node 16, rather than Node 12)

fix: allow workflow bot to use peerDep

---

.github/workflows/npm-publish.yml
.github/workflows/release-please.yml
package.json

All of the substrings of publish were taken, pub, pu, publ, everything was taken so I couldn't just rename the script. Doing "npm publish --tag develop" isn't that hard to remember so I just removed it instead. It can be added back, just pick a different name that isn't already builtin to npm.

fix: remove publish script to stop duplication

---

apps/playground/package.json
packages/bootstrap-vue-3/package.json
packages/bootstrap-vue-3/vite.config.ts

to avoid conflict with vuepress running on 8080.

chore(bootstrap-vue-3): update dev port from 8080 to 5174

---

.github/workflows/release-please.yaml

Not sure why filtering by path didn't work, works fine when running on local machine. Must be something weird with Windows vs I assume actions are using Linux.

ci: fix filter to use package name instead of glob

---

packages/bootstrap-vue-3/src/components/BAccordion/BAccordion.vue
packages/bootstrap-vue-3/src/components/BAccordion/BAccordionItem.vue
packages/bootstrap-vue-3/src/components/BAvatar/BAvatar.vue
packages/bootstrap-vue-3/src/components/BAvatar/BAvatarGroup.vue
packages/bootstrap-vue-3/src/components/BBadge/BBadge.vue
packages/bootstrap-vue-3/src/components/BButton/BButton.vue
packages/bootstrap-vue-3/src/components/BNav/BNavbarNav.vue
packages/bootstrap-vue-3/src/components/BNav/navbar-brand.spec.js
packages/bootstrap-vue-3/src/types/Booleanish.d.ts
packages/bootstrap-vue-3/src/types/index.ts
packages/bootstrap-vue-3/src/utils/index.ts
packages/bootstrap-vue-3/src/utils/isLink.ts
packages/bootstrap-vue-3/src/utils/resolveBooleanish.ts
packages/bootstrap-vue-3/src/utils/router.ts
pnpm-lock.yaml

This is to assist in user choice. At this time, it only applies to simple boolean types, not complex i.e boolean | any. It may go through some changes. A user would be able to do prop="true" vs requiring :prop="true". At this time, I'm unsure if there's a better, less boilerplatish method of converting the Booleanish prop to boolean.
refactor(BNavbarNav): clean code
test(NavbarBrand): remove console.log
refactor(router.ts): name change and strongly typ
The name change was because 'router.ts' is confusing when an app uses createRouter, such as in the playground. It only contains one function, so it was made to export default.
chore: add note about bbutton
BButton has many assignments that are not computed values. I'm not sure why this is. It seems that if someone intentionally v-bind to an …

feat: begin adding booleanish option

---

packages/bootstrap-vue-3/src/types/Booleanish.d.ts
packages/bootstrap-vue-3/src/utils/booleanish.ts

Kind of not the perfect solution to allow empty strings as Booleanish, but it works how it should.

fix: #540 prop w/ no value empty string is true

---

.npmrc
package.json
packages/bootstrap-vue-3/src/components/BAccordion/accordion-item.spec.ts
packages/bootstrap-vue-3/src/components/BAccordion/accordion.spec.ts
packages/bootstrap-vue-3/src/components/BAvatar/avatar-group.spec.ts
packages/bootstrap-vue-3/src/components/BAvatar/avatar.spec.ts
packages/bootstrap-vue-3/src/components/BBadge/badge.spec.ts
packages/bootstrap-vue-3/src/components/BBreadcrumb/breadcrum.spec.ts
packages/bootstrap-vue-3/src/components/BNav/BNavItemDropdown.vue
packages/bootstrap-vue-3/src/components/BNavbar/navbar-toggle.spec.ts
pnpm-lock.yaml

dropup dropleft and dropright are replaced with dropUp dropLeft and dropRight
chore: update deps and extend .x.x removal 
improved-yarn-audit was also removed. When you trying to run it, it will actually break because it detects using pnpm. Pretty sure an audit script could be created using pnpm to ignore dev deps, and min-security moderate. However, both are pretty useless since 'audit' itself is broken by design. Best to just remove the script we can't run. 
All breaking semver versions have been reviewed, and are generally a removal of node 12 support. Since release-please updated their dependencies, the "strict-peer-dependencies=false" can be removed warn us again.

fix: drop{type} props are camelCase and chore: update deps

---

packages/bootstrap-vue-3/src/components/BAccordion/accordion-item.spec.ts
packages/bootstrap-vue-3/src/components/BAlert.vue
packages/bootstrap-vue-3/src/components/BBreadcrumb/breadcrum.spec.ts
packages/bootstrap-vue-3/src/components/BCol.vue
packages/bootstrap-vue-3/src/components/BCollapse.vue
packages/bootstrap-vue-3/src/components/BFormCheckbox/form-checkbox.spec.js
packages/bootstrap-vue-3/src/components/BFormInput/form-input.spec.js
packages/bootstrap-vue-3/src/components/BFormRadio/form-radio.spec.js
packages/bootstrap-vue-3/src/components/BFormSelect/form-select-option.spec.js
packages/bootstrap-vue-3/src/components/BFormTextarea/form-textarea.spec.js
packages/bootstrap-vue-3/src/components/BImg.vue
packages/bootstrap-vue-3/src/components/BLink/link.spec.js
packages/bootstrap-vue-3/src/components/BNavbar/navbar.spec.ts
packages/bootstrap-vue-3/src/components/BOffcanvas.vue
packages/bootstrap-vue-3/src/components/BPopover.vue
packages/bootstrap-vue-3/src/components/BRow.vue
packages/bootstrap-vue-3/src/components/BSpinner.vue
packages/bootstrap-vue-3/src/components/BToast/b-toast.spec.js
packages/bootstrap-vue-3/src/components/alert.spec.ts
packages/bootstrap-vue-3/src/components/col.spec.ts
packages/bootstrap-vue-3/src/components/collapse.spec.ts
packages/bootstrap-vue-3/src/components/container.spec.ts
packages/bootstrap-vue-3/src/components/img.spec.ts
packages/bootstrap-vue-3/src/components/modal.spec.ts
packages/bootstrap-vue-3/src/components/offcanvas.spec.ts
packages/bootstrap-vue-3/src/components/popover.spec.ts
packages/bootstrap-vue-3/src/components/row.spec.ts
packages/bootstrap-vue-3/src/components/spinner.spec.ts

These tests may not include all coverage of various files and some are not fully finished. Read todos.
Actual changes of vue files include 
fix: BCol classes persisting after prop change
refactor: BImg computed classes contained business logic. 
refactor: explicit render checks in dynamic classes (ie `'someClass': !!prop.someProp` => `'someClass': prop.someProp !== undefined`.. Depending on the case  
Some other tests were refactored to use .get() instead of .find(). Based on the docs from vue-test-utils. .get() should be preferred and .find() should be used to test the existence of a component. As .get() will throw an error at it's spot if the component does not exist... For example
```ts
const $comp = wrapper.find('div')
expect($comp.classes()) // <- will throw error here about calling …
```

test: various components

---

packages/bootstrap-vue-3/src/components/BModal.vue
packages/bootstrap-vue-3/src/components/BTable/BTable.vue
packages/bootstrap-vue-3/src/components/BTable/BTableContainer.vue
packages/bootstrap-vue-3/src/components/BTable/_table.scss
packages/bootstrap-vue-3/src/components/BTable/itemHelper.ts

supported props from vue-bootstrap:
- sort-by
- sort-desc
new props: 
-sort-internal{boolean} = a boolean to determine if you want the table to sort the given rows or not, it can be disabled when using an external API request for sorting your table
working example:
```vue
<template>
<b-container>
<div>
<b-table
:items="items"
:fields="fields"
v-model:sort-by="sortBy"
v-model:sort-desc="sortDesc"
:sort-internal="true"
></b-table>
<div>
Sorting By: <b>{{ sortBy }}</b>, Sort Direction:
<b>{{ sortDesc ? 'Descending' : 'Ascending' }}</b>
</div>
</div>
</b-container>
</template>
<script  lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
data() {
return {
sortBy: 'age',
sortDesc: false,
fields: [
{ key: 'last_name', label: 'last_name', sortable: true },
{ key: …
```

BTable Sorting

---

packages/bootstrap-vue-3/src/components/BContainer.vue
packages/bootstrap-vue-3/src/components/BTable/BTable.vue
packages/bootstrap-vue-3/src/components/BTable/_table.scss
packages/bootstrap-vue-3/src/components/BTable/itemHelper.ts
packages/bootstrap-vue-3/src/styles/styles.scss
packages/bootstrap-vue-3/src/types/components/BTable/BTable.d.ts

BREAKING CHANGES: .container & .container-fluid CSS classes now have a default 'block' display to behave as a 'div' element when the BContainer tag is changed
BREAKING CHANGE: BTable 'sorted' event output value was changed to an object with keys [sort(string), desc(boolean)] for better ts type support.
BREAKING CHANGES: BTable sortInternal prop default value is now 'false'
fix: added a few missing props to the BTable.d.ts file
fix: replaced BTable emits definition array with a typescript interface for better type support
fix: update the data type of a few of BTable props
feat: Added 'tag' prop to BContainer component
feat: Added BTable selectable prop that adds the selection functionality to the table
feat: Added BTable select-mode prop with a value of [multi, single, range] to expand how …

BContainer tag prop, BTable items/rows selection

---

packages/bootstrap-vue-3/src/components/BTable/BTable.vue
packages/bootstrap-vue-3/src/components/BTable/_table.scss
packages/bootstrap-vue-3/src/composables/index.ts
packages/bootstrap-vue-3/src/composables/useTitleCase.ts
packages/bootstrap-vue-3/src/utils/stringUtils.ts

BREAKING CHANGES: updated BTable sorted event output from an object to standalone args
fix(BTable): fixes 'sorted' event not emitted with fully synced values
feat(BTable): The field key now appears in the header when the given field has no ``label``.
feat(BTable): added ``selectAllRows`` method that selects all of the given items when ``selectable`` prop is 'true'
feat(BTable): added ``clearSelected`` method that unselects all of the selected items and notifies the updates through rowUnselectedand selection events
feat(BTable): added ``selectRow`` and unselectRow methods, both methods take a number input which is the index of the item to either select or unselect its row.
feat(BTable): added ``head-clicked`` event functionality, according to the docs of vue2-bootstrap
feat(BTable): added …

BTable selection handling methods along with a few fixes

---

README.md
packages/bootstrap-vue-3/src/components/BCarousel/BCarousel.vue
packages/bootstrap-vue-3/src/components/BCarousel/BCarouselSlide.vue
packages/bootstrap-vue-3/src/components/BCarousel/carousel-slide.spec.ts
packages/bootstrap-vue-3/src/components/BCarousel/carousel.spec.ts
packages/bootstrap-vue-3/src/components/BDropdown/BDropdownItemButton.vue
packages/bootstrap-vue-3/src/components/BDropdown/dropdown-item-button.spec.ts
packages/bootstrap-vue-3/src/components/BDropdown/dropdown-text.spec.ts
packages/bootstrap-vue-3/src/components/BTabs/tab.spec.ts

[feat(BCarousel): prop ariaLabel on indicator butto](https://github.com/cdmoro/bootstrap-vue-3/commit/1c03c707390b5852641871ef394a244cffec5299) 
feat(BCarouselSlide): imgHeight can be number
feat(BCarouselSlide): imgWidth can be number
refactor(BCarouselSlide): showCaptionHtml computed replaced
refactor(BCarouselSlide): showTextAsHtml computed replaced
test: carousel-slide.spec.ts
test: carousel.spec.ts
refactor(BDropdownItemButton): explicit undefined check on class
refactor(BDropdownItemButton move static attrs to template
test: dropdown-item-button.spec.ts
test: dropdown-text.spec.ts
test(tab.spec.ts): @ts-ignore injectionKey import

feat: ariaLabel on indicator button and tests

---

packages/bootstrap-vue-3/src/components/BTable/BTable.vue
packages/bootstrap-vue-3/src/components/BTable/_table.scss

feat(BTable): completed the ``TableItem.sticky-column`` prop logic, according to bootstrap-vue2 docs
feat(BTable): added ``sticky-header`` prop feature, according to bootstrap-vue2 docs
feat(BTable): new ``sticky-select`` prop was added, the prop converts the selection column to the sticky mode when the selectable prop is passed as true to the table
feat(BTable): row's ``_showDetails`` prop logic was completed
feat(BTable): added ``busy`` prop logic, the prop shows a spinner and message that can be replaced through a slot template ``#table-busy``

BTable sticky header, columns, and selection. Along with a few fixes/additions

---

packages/bootstrap-vue-3/src/components/BAvatar/BAvatar.vue
packages/bootstrap-vue-3/src/components/BCard/BCard.vue
packages/bootstrap-vue-3/src/components/BCard/card.spec.ts
packages/bootstrap-vue-3/src/components/BDropdown/BDropdownGroup.vue
packages/bootstrap-vue-3/src/components/BDropdown/dropdown-group.spec.ts
packages/bootstrap-vue-3/src/components/BImg.vue
packages/bootstrap-vue-3/src/components/BTable/BTableContainer.vue
packages/bootstrap-vue-3/src/composables/useBooleanish.ts

[revert(](https://github.com/cdmoro/bootstrap-vue-3/commit/3c721260160970fe3898b196ae6365a67745828e)https://github.com/cdmoro/bootstrap-vue-3/commit/83f5e53bbd5686fc426681523105c0252986bc62[): rename to remove 'es' at end](https://github.com/cdmoro/bootstrap-vue-3/commit/3c721260160970fe3898b196ae6365a67745828e) 
Though it may make more sense to include 'es' at the end, (since it can contain many classes), it is more standard to exclude the 'es'
chore(BImg): add some notes about TODOs
chore(useBooleanish): add note about future Vue code possibilities
fix(BTableContainer): rename prop responsiveClasses to responsiveClass
fix(BDropdownGroup): rename headerClasses prop to headerClass
chore(BAvatar): remove old note
**The PR …

revert(83f5e53): rename to remove 'es' at end

---

packages/bootstrap-vue-3/src/composables/useFormCheck.ts

Vue3 introduced the concept of Fragments, which allow placing multiple elements as roots of a component, but also they're used to group elements iterated through in a `v-for` directive.
For example, when we write
```vue
<template>
<b-form-radio-group>
<b-form-radio v-for="option in options" :value="option">
{{ option }}
</b-form-radio>
</b-form-radio-group>
</template>
<script>
export default {
computed: {
options() {
return [ 1, 2, 3 ];
}
}
}
</script>
```
it compiles (roughly) to:
```json
{
"type": "Symbol(Fragment)",
"children": [
{
"type": {
"__name": "BFormRadio"
}
},
{
"type": {
"__name": "BFormRadio"
}
},
{
"type": {
"__name": "BFormRadio"
}
}
]
}
```
So this PR makes the conversion of slots into elements recognise that, if we have fragments like this in the slots, we need to …

fix(composables): Spread out children from Fragment slots

---

.github/pull_request_template.md
packages/bootstrap-vue-3/src/components/BAvatar/BAvatar.vue
packages/bootstrap-vue-3/src/components/BFormTags/BFormTag.vue
packages/bootstrap-vue-3/src/components/BFormTextarea/BFormTextarea.vue
packages/bootstrap-vue-3/src/components/BInputGroup/BInputGroup.vue
packages/bootstrap-vue-3/src/components/BInputGroup/BInputGroupAppend.vue
packages/bootstrap-vue-3/src/components/BInputGroup/BInputGroupPrepend.vue
packages/bootstrap-vue-3/src/components/BInputGroup/BInputGroupText.vue
packages/bootstrap-vue-3/src/components/BInputGroup/input-group-addon.spec.ts
packages/bootstrap-vue-3/src/components/BInputGroup/input-group-append.spec.ts
packages/bootstrap-vue-3/src/components/BInputGroup/input-group-text.spec.ts
packages/bootstrap-vue-3/src/components/BInputGroup/input-group.prepend.spec.ts
packages/bootstrap-vue-3/src/components/BInputGroup/input-group.spec.ts
packages/bootstrap-vue-3/src/components/BModal.vue
packages/bootstrap-vue-3/src/components/BProgress/BProgress.vue
packages/bootstrap-vue-3/src/components/BProgress/progress.spec.ts
packages/bootstrap-vue-3/src/components/BTable/BTable.vue
packages/eslint-config-custom/index.cjs

[refactor(BInputGroup): change order of template](https://github.com/cdmoro/bootstrap-vue-3/commit/2fa30b1fbe59c43afe27c6bb7659d11bf3cd78ca) 
test: input-group.spec.ts
chore(eslint): introduce 'vue/html-self-closing' rule
docs: small change to pull_request_template
[refactor(BInputGroupAppend): move attrs](https://github.com/cdmoro/bootstrap-vue-3/commit/c3ba8e4fec28e019016f4d1db01795d12a2ebe25) 
refactor(BInputGroupPrepend): move attrs
feat(BInputGroupText): add optional text prop
refactor(BProgress): move attrs out of template
test: progress.spec.ts
test: input-group-addon.spec.ts
test: input-group-append.spec.ts
test: input-group-text.spec.ts
test: input-group-prepend.spec.ts

test: various tests and refactor and include html-self-closing rule

---

packages/bootstrap-vue-3/src/components/BTable/BTable.vue

fix(BTable): row.index is now correctly passed to the cell slot template
___
fixes https://github.com/cdmoro/bootstrap-vue-3/issues/637

fix(BTable): row.index is now correctly passed to the cell slot template

---

packages/bootstrap-vue-3/src/components/BDropdown/BDropdownItem.vue
packages/bootstrap-vue-3/src/components/BDropdown/BDropdownItemButton.vue

In [bootstrap vue](https://github.com/bootstrap-vue/bootstrap-vue/blob/fab4161c90ad6e178b16540f15928f52149cdba3/src/components/dropdown/dropdown-item.js#L64) it was handled to bind classes to `b-dropdown-item` and `b-dropdown-item-button`  and I have added it now.

feat(b-dropdown-item): :sparkles: Bind class attribute to the root

---

packages/bootstrap-vue-3/src/components/BTable/BTable.vue

Added slot "custom-foot" to BTable in order to improve compatibility with [bootstrap-vue](https://bootstrap-vue.org/docs/components/table#creating-a-custom-footer)

BTable: added slot "custom-foot"

---

packages/bootstrap-vue-3/src/components/BModal.vue

This issue mentioned in https://github.com/cdmoro/bootstrap-vue-3/pull/658
He was correct in the second comment https://github.com/cdmoro/bootstrap-vue-3/pull/658#issuecomment-1245293371 
The close event should be fired through vue's click handler, Events should never depend on Bootstrap's event callbacks in such matter since we can't fully control the events coming from Bootstrap
fix(BModal): fixed the modal's close button located in the header where the button click was not updating ``v-model`` value

BModal header's close button not updating v-model value

---

packages/bootstrap-vue-3/src/components/BTable/BTable.vue

feat(BTable): added ``sortIcon`` slot, the slot allows you to customize the table's sort icons by providing you some info about the applied sort
feat(BTable): added ``show-empty`` prop along with the ``#empty`` slot to customize the empty message
feat(BTable): added ``emptyText`` and ``emptyFilteredText`` props to customize the shown message when the table is empty and ``show-empty`` prop is set to true

BTable customizable sort icon, and show-empty prop

---

packages/bootstrap-vue-3/src/components/BModal.vue

PR for issue https://github.com/cdmoro/bootstrap-vue-3/issues/674
____
I have tried my best to make the events vue-based only but it was not working out smoothly. that's the best result I've got so far.
This PR will fix the issue and also make sure escape-key closing works fine with nested modals since bootstrap's modal does not really support multiple/nested modal instances
example of working code
```vue
<div>
<b-button @click="showModal = true">Show Modal</b-button>
<b-modal v-model="showModal" id="my-modal">
Hello From My Modal!
<b-button @click="showNestedModal = true">Show Modal</b-button>
<b-modal v-model="showNestedModal" id="my-modal">Hello From Nested Modal!</b-modal>
</b-modal>
</div>
```

A possible solution for BModal escape-key close event

---

packages/bootstrap-vue-3/src/components/BAlert.vue
packages/bootstrap-vue-3/src/components/BButton/BCloseButton.vue
packages/bootstrap-vue-3/src/components/BButton/_button.scss
packages/bootstrap-vue-3/src/components/BButton/close-button.spec.ts
packages/bootstrap-vue-3/src/components/BFormTags/BFormTag.vue
packages/bootstrap-vue-3/src/components/BModal.vue
packages/bootstrap-vue-3/src/components/BOffcanvas.vue
packages/bootstrap-vue-3/src/components/alert.spec.ts
packages/bootstrap-vue-3/src/components/container.spec.ts
packages/bootstrap-vue-3/src/components/offcanvas.spec.ts

feat(BAlert): slot dismissible overwrites close
refactor(BModal): slot header-close is either or on close icon
refactor(BOffcanvas): button with static class btn-close is refactored to use BCloseButton
refactor(BFormTag): button with static class btn-close is refactored to use BCloseButton
feat(BCloseButton): add in optional prop type to override type=button default
test(close-button): include test for optional prop type
test(offcanvas): refactor to include BCloseButton changes
test(container): include enableAutoUnmount
test(alert): refactor to include BCloseButtonChanges
chore(_button.scss): remove unused class after close button changes

refactor: buttons with class btn-close are remade to use BCloseButton.vue

---

apps/docs/docs/.vuepress/PluginComponentReference/client/components/component-doc.vue

Small fix regarding docs. 
- [x ] Bugfix :bug: - `fix(...)`
docs: scoped slots docs now work when clicked on

fix: scoped slots docs now work when clicked on

---

apps/docs/docs/components/ButtonToolbar.md
apps/docs/docs/components/Form.md
apps/docs/docs/components/FormTags.md
apps/docs/docs/components/InputGroup.md
apps/docs/docs/components/Overlay.md
apps/docs/docs/components/Table.md
apps/docs/docs/components/Tabs.md
apps/playground/src/components/Comps/TTableSimple.vue
packages/bootstrap-vue-3/src/components/BCard/BCardImg.vue
packages/bootstrap-vue-3/src/components/BDropdown/BDropdown.vue
packages/bootstrap-vue-3/src/components/BDropdown/dropdown.spec.ts

Dropdown **right** property was not working, because attaching the old utility CSS class: `dropdown-menu-right` instead of the new `dropdown-menu-end`.  Throughout the docs I also renamed the old utility CSS classes. 

Fix renamed bootstrap 5 utilities classes

---

packages/bootstrap-vue-3/src/components/BTable/BTable.vue
packages/bootstrap-vue-3/src/components/BTable/itemHelper.ts
packages/bootstrap-vue-3/src/types/components/BTable/BTable.d.ts
packages/bootstrap-vue-3/src/types/components/index.ts

Solves https://github.com/cdmoro/bootstrap-vue-3/issues/694,
Notes:
The compare function has fewer arguments than what BSV2's has
SortCompare function example:
```ts
const sortCompare: BTableSortCompare = (aRow, bRow, key, sortDesc): number => {
const a = aRow[key] // or use Lodash `_.get()`
const b = bRow[key]
if (
(typeof a === 'number' && typeof b === 'number') ||
(a instanceof Date && b instanceof Date)
) {
// If both compared fields are native numbers or both are native dates
return a < b ? (sortDesc ? -1 : 1) : a > b ? (sortDesc ? 1 : -1) : 0
} else {
// Otherwise stringify the field data and use String.prototype.localeCompare
return JSON.stringify(a).localeCompare(JSON.stringify(b))
}
}
```

BTable sort-compare prop but simpler

---

packages/bootstrap-vue-3/src/components/BInputGroup/BInputGroupAddon.vue
packages/bootstrap-vue-3/src/components/BInputGroup/BInputGroupAppend.vue
packages/bootstrap-vue-3/src/components/BInputGroup/BInputGroupPrepend.vue
packages/bootstrap-vue-3/src/components/BInputGroup/input-group-addon.spec.ts
packages/bootstrap-vue-3/src/components/BInputGroup/input-group-append.spec.ts
packages/bootstrap-vue-3/src/components/BInputGroup/input-group.prepend.spec.ts

This contains a breaking change of the removal of some props
feat(BInputGroupAppend)!: remove useless props
Prop id was pretty useless, and since the component doesn't need a dynamic wrapper, tag is removed. (The single root is removed since it's not needed in Vue 3)
feat(BInputGroupPrepend)!: remove useless props
fix(https://github.com/cdmoro/bootstrap-vue-3/issues/470): no rounded corners when using BInputGrooupPrepend or BInputGroupAppend

fix(#470): no rounded corners when using BInputGrooupPrepend or BInputGroupAppend

---

packages/bootstrap-vue-3/src/components/BModal.vue

When clicking a link inside the modal, the `overflow: hidden` style was not removed from the body element. 

fix(BModal): dispose modal before unmount

---

packages/bootstrap-vue-3/src/components/BFormTags/BFormTags.vue
packages/bootstrap-vue-3/src/components/BFormTags/form-tags.spec.ts

Add a tag named scoped slot to BFormTags for customizing only a single tag.

feat(BFormTags): Add tag scoped slot

---

packages/bootstrap-vue-3/src/components/BTable/BTable.vue

BTable with provider never hides the busy loader

fix(BTable): [#742] BTable with provider never hides the busy loader

---

packages/bootstrap-vue-3/src/components/BModal.vue
packages/bootstrap-vue-3/src/components/BTable/BTable.vue
packages/bootstrap-vue-3/src/components/BTable/_table.scss
packages/bootstrap-vue-3/src/constants/env.ts
packages/bootstrap-vue-3/src/utils/dom.ts

So, I did an oppise when creating the logic behind BTable -> Sort Icon styling where the sort icon elements are removed from the dom until the column's header is sorted, Which prevents a lot of styling possibilities for these icons.
Now the icon elements will be always rendered in the dom without appearing until the header is sorted.
This will allow having one global CSS code for all your website tables instead of forcing you to add slot-template inside each table to make simple customizations to the icons like this one

CSS possibilities correction for BTable sort-icon (Very important for UX)

---

packages/bootstrap-vue-3/src/components/BTable/BTable.vue
packages/bootstrap-vue-3/src/components/BTable/_table.scss
packages/bootstrap-vue-3/src/components/BTable/itemHelper.ts

fix(BTable): fixed filtering undefined table item values (more details: https://github.com/cdmoro/bootstrap-vue-3/issues/770).
fix(BTable): fixed ``filtered`` event being emitted when using pagination (more details: https://github.com/cdmoro/bootstrap-vue-3/issues/768).
fix(BTable): provided typescript hints for a stacked prop.
fix(BTable, BTableSimple): Added the needed CSS to make the ``stacked`` prop take effect from a specific screen-size breakpoint.
feature(BTable): added ``label-stacked`` prop to label the stacked rows with the field's label
code example:
```vue
<template>
<b-container fluid class="py-5">
<div class="row">
<div class="col-6">
<h4 class="mb-3">Stacked table</h4>
<b-table :items="items" :fields="fields" responsive stacked …
```

A few fixes to table componeted, new stacked label prop 

---

packages/bootstrap-vue-3/src/components/BModal.vue
packages/bootstrap-vue-3/src/styles/styles.scss

BModal is no longer showing up
For some reason adding CSS to a component's scoped style does not have any effect, The CSS is not being used when serving the library in a project (But works fine in dev env).
However, Moving the CSS to the global styles will fix issues where the modal doesn't show up and the backdrop doesn't appear correctly in some cases.
add this CSS to your application's global styles
```css
.modal {
display: block;
}
.modal .modal-dialog {
z-index: 1051;
}
```

BModal fix, Should be merged & published asap

---

packages/bootstrap-vue-3/src/directives/BPopover.ts

Allow html modifier in Popover directive
I am using `v-b-popover.html="'<p>text</p>'"` and it didn't render the HTML but showed the actual HTML tags. 

feat(Popover): Allow html modifier in directive

---

packages/bootstrap-vue-3/package.json
packages/bootstrap-vue-3/src/components/BFormSpinButton/BFormSpinButton.vue
pnpm-lock.yaml

Removes Bootstrap Icons until future @VividLemon and me can do something about it

Remove Icons from Package

---

packages/bootstrap-vue-3/src/components/BTabs/BTabs.vue
packages/bootstrap-vue-3/src/components/BTabs/tabs.spec.ts

Refs: #778
Fixes an issue where tabs content does not update when reactive content is passed. 

fix: Tabs Content will update with reactive components

---

packages/bootstrap-vue-3/src/components/BButton/BButtonGroup.vue
packages/bootstrap-vue-3/src/components/BButton/button-group.spec.ts

Fixes #828
```html
<b-card>
<div>
<b-button-group>
<b-button>Button 1</b-button>
<b-button>Button 2</b-button>
<b-button>Button 3</b-button>
</b-button-group>
</div>
<div class="mt-3">
<b-button-group size="sm">
<b-button>Left</b-button>
<b-button>Middle</b-button>
<b-button>Right</b-button>
</b-button-group>
</div>
<div class="mt-3">
<b-button-group size="lg">
<b-button>Left</b-button>
<b-button>Middle</b-button>
<b-button>Right</b-button>
</b-button-group>
</div>
</b-card>
```

fix(#828): BButtonGroup missing btn-group class when prop size

---

apps/playground/src/components/Comps/TTable.vue
packages/bootstrap-vue-3/src/components/BTable/BTable.vue
packages/bootstrap-vue-3/src/components/BTable/itemHelper.ts

Support a formatter function on b-table
partial implementation of #769
As the new playground shows, using a formatter function will now work.
The Type also defines a string as valid argument - but i'm not entirely certain what string content would cause what behavior.

add support for "formatter" on b-table

---

apps/playground/src/components/Comps/TTable.vue
packages/bootstrap-vue-3/src/components/BTable/itemHelper.ts
packages/bootstrap-vue-3/src/components/BTable/table.spec.ts
packages/bootstrap-vue-3/src/types/TableField.d.ts

Builds on top of #844 - adding support for the formatter for all types of values (it's actually more useful on non-string values).
It's also adding a test for the new behavior (also for #844).
This required a change to the type - as the formatter should accept "any" value (whatever the item type is).

improve "formatter" option for table

---

apps/docs/docs/getting-started/README.md

Fixing a small typo in the docs to correctly spell BootstrapVue.

docs(getting-started): correct spelling of BootstrapVue

---

packages/bootstrap-vue-next/src/components/BTabs/BTabs.vue

Add `role="presentation"` to the `li` within the B-Tabs component for improved accessibility.
Without this, Microsoft's [Accessibility Insights for Web](https://accessibilityinsights.io/docs/web/overview/) Chrome extension flags an error, as the default role for `li` (listitem) should only be in `ul` or `ol` elements that have no explicit role, or `role="list"`.

fix(BTabs): add role="presentation"

---

packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
packages/bootstrap-vue-next/src/components/BAccordion/accordion-item.spec.ts
packages/bootstrap-vue-next/src/types/components/BAccordion/BAccordionItem.ts

Add header-tag prop on BAccordionItem in order to be able to change default `h2` tag for the title.

feat(BAccordion): add header-tag prop on BAccordionItem

---

packages/bootstrap-vue-next/src/components/BButton/BButton.vue

This PR is a suggestion to resolve issue #973. It will change the `isToggle` computed property to be dependent on the type of `pressedBoolean` instead of its value.
#973

fix(BButton): isToggle computed property use type of pressedBoolean

---

packages/bootstrap-vue-next/src/components/BButton/button.spec.ts

#974 did not include updates in the tests for BButton, this PR will add the changes made to BButton `pressed` prop. This should resolve the failed checks in the PR.
Failed PR checks

fix(BButton): fix failing checks from updated pressed prop

---

.npmrc
apps/playground/package.json
apps/playground/src/Views/HomePage.vue
apps/playground/src/components/Comps/TBLink.vue
apps/playground/src/components/Comps/TCollapse.vue
apps/playground/src/components/Comps/TDropdown.vue
apps/playground/src/components/Comps/TModal.vue
apps/playground/src/components/Comps/TPopover.vue
apps/playground/src/main.ts
apps/playground/src/router/index.ts
packages/bootstrap-vue-next/package.json
packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
packages/bootstrap-vue-next/src/components/BAccordion/accordion-item.spec.ts
packages/bootstrap-vue-next/src/components/BCollapse.vue
packages/bootstrap-vue-next/src/components/BModal.vue
packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
packages/bootstrap-vue-next/src/components/BPopover.vue
packages/bootstrap-vue-next/src/components/BToast/plugin.ts
packages/bootstrap-vue-next/src/components/collapse.spec.ts
packages/bootstrap-vue-next/src/directives/BModal.ts
packages/bootstrap-vue-next/src/directives/BPopover.ts
packages/bootstrap-vue-next/src/directives/BToggle.ts
packages/bootstrap-vue-next/src/directives/BTooltip.ts
packages/bootstrap-vue-next/src/utils/floatingUi.ts
packages/bootstrap-vue-next/vite.config.ts
pnpm-lock.yaml

No more bootstrap.js!
SSR works! The docs can be build without <ClientOnly>! I belive nuxt works also!
tried to keep the changes to minimal on places.
changed the v-b-toggle to work with events, and now toggle, offcanvas and modal listen to "toggle" event.
As a test I remove bootstrap in playground and only added it's css in link tag in the index.html file.
In bootstrap-vue-next we only need few scss functions/variables/mixins from bootstrap npm package.

Collapse native vue, no more bs.js!

---

packages/bootstrap-vue-next/src/components/BButton/BButton.vue
packages/bootstrap-vue-next/src/components/BButton/button.spec.ts
packages/bootstrap-vue-next/src/components/BLink/BLink.vue
packages/bootstrap-vue-next/src/components/BLink/link.spec.ts
packages/bootstrap-vue-next/src/components/BListGroup/BListGroupItem.vue
pnpm-lock.yaml

BLink component ignores directly set active prop, when router link passes isActive prop, this causes invalid assignment of active class when nested routes is used.
See tests, or:
Create vue instance with vue-router and nested routes and two BLinks, one heading to default route target and with active prop set to false, and then second to its nested route. After navigation to second route, both BLinks has active class assigned, but the first BLink shouldn't have.

fix(BLink): prefer passed active prop over isActive slot prop from RouterLink

---

apps/docs/docs/components/FormInput.md
apps/docs/docs/reference/types.md
apps/playground/src/components/Comps/TFormInput.vue
packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue
packages/bootstrap-vue-next/src/types/InputType.ts

Adds missing input types to BFormInput, like datetime-local, so these are not converted to plain text fields then used. (They were also supported by bootstrap-vue 2)

fix(BFormInput): added missing input types to BFormInput

---

README.md

Several users have marked an issue for the Documentation site not being working. This turns out to be due to a fault in the static site generation tool, which is going to be replaced in due course.
In the interim other users have pointed out that there is a way for users to see the _current_ documentation without making a local copy of the repo. 
This PR updates the link in the home page to link to that link, which is also within the repo.

docs(home page): Update "Documentation" link to working site

---

apps/playground/src/components/Comps/TTable.vue
packages/bootstrap-vue-next/src/components/BTable/BTable.vue

Expose BTable refresh method as requested in #960.
Is this a good way to do it?
Do we currently support root events?

Expose BTable refresh method

---

packages/bootstrap-vue-next/src/utils/floatingUi.ts

If element is unmounted, the remove() messes vue:n dom handling. Run it in next coroutine.

Fix floating directives unmount error

---

apps/playground/src/components/Comps/TAccordion.vue
apps/playground/src/components/Comps/TCollapse.vue
packages/bootstrap-vue-next/src/components/BAccordion/BAccordion.vue
packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
packages/bootstrap-vue-next/src/components/BCollapse.vue
packages/bootstrap-vue-next/src/utils/keys.ts

As the title says.
fixes #994 
Adds v-modal to BAccordion that is the id of the open accordion. 
Add free booleanish to open multiple
Integrate more with BCollapse

AccordionItem closes when another is opened, add free boolean for opening multiple

---

packages/bootstrap-vue-next/src/components/BTabs/BTab.vue
packages/bootstrap-vue-next/src/components/BTabs/BTabs.vue

fixes #251 
split the tabs to two, watch for changes in slots.default and recreate the tabs only then. Otherwise we're creating the tabs object on each change and the ID:s change.
Then have computed for the local changes.

enable fade on tabs, redo tabs only when slot is changed.

---

apps/docs/docs/component-references/Collapse.json
apps/docs/docs/components/Collapse.md

I've updated the documentation page for the BCollapse component to include the latest information on how to show/hide content on the collapse toggle, and to advise users that relying on the `v-b-toggle` directive for this will no longer work from 0.8.0 onwards.
The original source for the information was from #1042. I've topped up the component reference with information about the default & footer slots as well.

docs(BCollapse): updated examples and information about collapse slots

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue

If perPage is set and currentPage is changed, prop items will be mutated.
Pagination uses splice to get perPages computedItems and removes them from original items.
This mutates data source.
As a solution, splice is replaced with slice, to geht perPage item range without mutating item prop array.
Reactive items
Reactive currentPage
If currentPage change, items array will be mutated.

fix: remove b-table item prop mutation by pagination

---

packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue

1) the accessibility aria-expanded="false" was always on 'false'
2) Add 'show' class when the menu is expended (like old version)
Run the playground and look for Dropdown

fix: add accessibility to b-dropdown and reset show class

---

packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue
packages/bootstrap-vue-next/src/components/BLink/BLink.vue
packages/bootstrap-vue-next/src/components/BNavbar/BNavbar.vue
packages/bootstrap-vue-next/src/utils/keys.ts

This is my attempt at fixing #1067  and my own issue:
I'm using BCollapse inside a sidebar on the left with a couple of BLinks. The BCollapse should stay open if a BLink is clicked. With 0.8.x the BCollapse now closes automatically.
I wasn't sure which properties to expose from the navbar so I chose tag as some kind of placeholder...
BLink & BDropdownItem now checks if they are inside a navbar and only auto collapse the surrounding BCollapse if so.
Feedback is always welcome :)
**The PR fulfills these …

fix(BCollapse): auto close only if inside a navbar

---

packages/bootstrap-vue-next/src/components/BButton/BButton.vue
packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue

allow define aria-label to b-button (and same using b-dropdown)
feat(BDropdown): allow define aria-label to b-button

feat(BDropdown): allow define aria-label to b-button

---

packages/bootstrap-vue-next/src/components/BNav/BNavItem.vue
packages/bootstrap-vue-next/src/components/BNav/nav-item.spec.ts

Adds `linkClasses` as property in `BNavItem` to pass classes to `BLink`. Solves issue #1183 reported as bug.
```html
<b-nav-item link-classes="shadow">
...
</b-nav-item>
```

feat(BNavItem): adds linkClasses property.

---

packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue

`b-offcanvas` ignores manually set property id. This PR adds manually set property `id` to the offcanvas node.
Solves issue #1180.
```html
<b-offcanvas id="main-menu">
...
</b-offcanvas>
<b-nav-item v-b-toggle.main-menu>
...
</b-nav-item>
```

fix(BOffcanvas): respect manually set property id.

---

packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue
packages/bootstrap-vue-next/src/components/BNav/nav-item-dropdown.spec.ts

Programmatically open, close and toggle `BNavItemDropdown` like in `BDropdown` component.
```html
<b-nav>
<b-nav-item-dropdown ref="mainDropdown">
<template #button-content>My Button</template>
<b-nav-item>Item 1</b-nav-item>
<b-nav-item>Item 2</b-nav-item>
</b-nav-item-dropdown>
</b-nav>
```
Control the dropdown e.g.:
```js
this.$refs.mainDropdown.open()
this.$refs.mainDropdown.close()
this.$refs.mainDropdown.toggle()
```
Solves #1184.

feat(BNavItemDropdown): adds open, close and toggle methods.

---

packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
packages/bootstrap-vue-next/src/components/BFormGroup/form-group.spec.ts

This fixes the types to allow the `state` property of `BFormGroup` / `b-form-group` to have a `Booleanish` or `null` value as written in the docs.
Fixes: #1167
See #1167

fix(BFormGroup): allow Booleanish and null for state prop

---

apps/docs/.vitepress/theme/Layout.vue
packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
packages/bootstrap-vue-next/src/components/BOffcanvas/offcanvas.spec.ts

Like described in the official [documentation of vue](https://vuejs.org/guide/scaling-up/ssr.html#teleports), SSR deployments should consider to use an own DOM node for teleports:
_Avoid targeting body when using Teleports and SSR together - usually, `<body>` will contain other server-rendered content which makes it impossible for Teleports to determine the correct starting location for hydration. Instead, prefer a dedicated container, e.g. `<div id="teleported"></div>` which contains only teleported content._
Every bootstrap-vue component, that uses teleport, cannot be configured with `:to=` property. Default is `body` and SSR deployments need to set teleport `:to=` to e.g. `#body-teleports`.
**This PR introduces `to` property for `BOffcanvas`.**
Solves issue #1178 for `BOffcanvas`. …

feat(BOffcanvas): adds teleport to property.

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue

Fixes `multi` select mode on Table rows for macOS users, which is currently hard coded to only work with the Control key. On Macs, the Control key is a modifier for right click, and cannot be used to select files, table rows, etc. Instead on Macs the Command key is used for most cases that would use the Control key on Windows. The event property name for the Command key is `metaKey`:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey
For reference, here is where the old BootstrapVue version uses `metaKey`:
https://github.com/bootstrap-vue/bootstrap-vue/blob/master/src/components/table/helpers/mixin-selectable.js#L229
I'm not certain how to demo the issue without using a Mac computer, however I've tested the change on both macOS and Windows and both now work as …

fix(BTable): support multi select mode for macOS users

---

packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue

Like in `bootstrap-vue` v2.23.1 and before, the value should also accept an empty string. Clicking on `All` radio button the value does not change from e.g. old value `b` to empty string. This PR fixes this bug.
```vue
<template>
<b-container>
<b-row>
<b-col>
<b-form-radio-group
id="radio-group-1"
v-model="groupedSelected"
:options="groupedOptions"
name="radio-options"
></b-form-radio-group>
</b-col>
</b-row>
</b-container>
</template>
import { ref } from 'vue'
const groupedOptions = [
{text: 'All', value: ''},
{text: 'Group A', value: 'a'},
{text: 'Group B', value: 'b'},
]
const groupedSelected = ref()
</script>
```

fix(BFormRadio): update value with empty string.

---

packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue

Expose hide and show to programmatically control `BOffcanvas`.
```vue
<template>
...
<b-offcanvas id="my-offcanvas" ref="offcanvas">
<b-link @click="hide">
Hide Offcanvas
</b-link>
</b-offcanvas>
<b-link v-b-toggle.my-offcanvas>
Show Offcanvas
</b-link>
...
</template>
import {ref} from 'vue'
import {BOffcanvas} from './components'
const offcanvas = ref(BOffcanvas)
const hide = (): void => {
offcanvas.value.hide()
}
</script>
```

feat(BOffcanvas): expose hide and show to programmatically control BOffcanvas.

---

apps/docs/src/docs/components/form-file.md
packages/bootstrap-vue-next/src/components/BFormFile/BFormFile.vue

Add `reset` method to the `BFormFile` component similar to [bootstrap-vue's reset method](https://bootstrap-vue.org/docs/components/form-file#clearing-the-file-selection)
* Allows to reset the input on the BFormFile component through a template ref
* Add documentation for previously added focus, blur exposed methods

feat: defineExpose reset on BFormFile input

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue
packages/bootstrap-vue-next/src/utils/object.ts

Show nested objects table rows also using a dot key. Look at issue #957 
Fixed #1307
Added ```busyLoadingText``` prop

BTable items nested object

---

packages/bootstrap-vue-next/src/components/BCarousel/BCarousel.vue

fixes #1303.
It adds `carousel-item` class to the slide component using the `afterEnter` event. Therefore, the component recovers the class removed by the transition.

fix(BCarousel): carousel-item class disappears after transition

---

apps/docs/src/data/components/button.data.ts
packages/bootstrap-vue-next/src/components/BButton/BButton.vue
packages/bootstrap-vue-next/src/components/BButton/_button.scss

resolves #1304
This PR fixes the Issue described in #1304 
This is my very first Pull request in OpenSource. Hope I did everything the way I should!
```
<template>
<BDropdown v-model='show1' text='Button text via Prop' class='m-1'>
<BDropdownItem href='#'>An item</BDropdownItem>
<BDropdownItem href='#'>Another item</BDropdownItem>
</BDropdown>
</template>
```
Now renders a valid button Code:
```
<button class="btn btn-md btn-secondary dropdown-toggle" type="button" id="__BVID__234593___BV_dropdown__" aria-expanded="false" aria-haspopup="menu">
<span class="btn-content">Button text via Prop</span>
</button>
```
- [X ] Bugfix :bug: - `fix(...)`
- [ X] Pull request title and all …

fix: Invalid button code in dropdown component

---

packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue

feat: Added missing support for top-row and bottom-row slots in BTableLite (and consequently BTable)
Enhancement for #1276

Top and bottom row slot support in BTable

---

apps/playground/src/components/Comps/TDropdown.vue
packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue
packages/bootstrap-vue-next/src/components/BDropdown/dropdown-item.spec.ts

Adds the aria-disabled attribute to b-drop-down-item to improve accessibility.
Also expands the playground page to include examples of b-drop-down-item with various different attributes.
Fixes #1350

fix(BDropdown): set aria-disabled attr when disabled

---

apps/docs/src/docs/components/alert.md
apps/docs/src/docs/components/form-input.md
apps/docs/src/docs/components/overlay.md
packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue

This PR fixes issue #1363 by exposing the `input` reference in `<BFormInput>`.
It will also fix some typos in the example code for using the `input` reference.
See #1363 and https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-input.html#input-methods for reproduction.
fix(BFormInput): expose `input` ref from BFormInput
docs: correct spelling of `HTMLElement` in code examples

fix: `input` reference of `<BFormInput>` is not exposed

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
packages/bootstrap-vue-next/src/composables/useTableItems.ts

This PR fixes various issues when using ```provider``` property:
- pagination 
- sorting 
- filtering
Properties ```no-provider-*``` true/false now work

BTable provider fixes

---

apps/playground/src/components/Comps/TPopover.vue
packages/bootstrap-vue-next/src/components/BPopover.vue
packages/bootstrap-vue-next/src/utils/floatingUi.ts

closes #1455 
fix(BPopover): remove function from BPopover target and Reference props and add MaybeRef to it.
I couldn't think why I added function there, and only one using it was the directives (which don't need to use it)

clear up Popover target & reference props

---

packages/bootstrap-vue-next/src/components/BModal.vue

When BModal has hide-header, aria-labelledby is still present.
See #1456 .

fix:BModal remove aria-labelledby when not present

---

packages/bootstrap-vue-next/src/components/BBadge/BBadge.vue
packages/bootstrap-vue-next/src/components/BBadge/badge.spec.ts

* As bootstrap 5.2+ supports text-bg-variant classes to set background colors and contrasting foreground colors automatically, use these to set the badge background and foreground color
* Remove functionality to manually set text-dark for contrasting foreground colors and remove relating test
* Remove setting link variant that conflicts with the new text-bg-variant class
n/a

fix(BBadge): use text-bg-variant classes for setting badge background and foreground color

---

packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue

BFormRadio value type must be like modelValue type
Without this PR if you need to select BRadioGroup with value null, typescript  says:
```
Vue: Type  null  is not assignable to type
string | number | boolean | Record<string, unknown> | undefined
````
Simple example with a BRadioGroup with custom default slot
```vue
<b-form-radio-group
v-model="radioValue"
>
<template #first>
<b-form-radio
:value="null"
>
All
</b-form-radio>
</template>
<b-form-radio
v-for="category in categoryOpts"
:key="category.id"
:value="category.id"
>
{{ category.description }}
</b-form-radio>
</b-form-radio-group>
```

BFormRadio value type like modelValue type

---

packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue

Fixed typo in BTableLite that allows ```head()``` slots use

fixed BTableLite head slot typo

---

packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue

When ```foot-clone``` is enabled header will be cloned to footer.
PR also allows footer slots ```foot()``` / ```foot({key})```

BTableLite foot-clone with foot() slots

---

apps/docs/src/data/components/modal.data.ts
apps/docs/src/docs/components/modal.md
packages/bootstrap-vue-next/src/components/BModal.vue
packages/bootstrap-vue-next/src/components/modal.spec.ts
packages/bootstrap-vue-next/src/composables/useSafeScrollLock.ts

Fix recent regression breaking body scroll locking when a modal is open and bodyScrolling isn't set to true.
Also removed unused 'show' prop, added some docs for scrollable and centered, and added some more unit tests. Docs and tests were mostly copied from bootstrap-vue.
Go to https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/modal.html, open a modal, and check the style attribute on document.body. Notice it doesn't exist, when it should be set to `overflow: hidden`

fix(BModal): Fix recent regression breaking body scroll locking

---

apps/docs/src/docs/components/navbar.md

1. The use of type="light|dark" has been replaced with data-bs-theme="light|dark" in order to modify the text color of the NavBar.  I've replaced all cases in the samples and updated the description.  This addresses #1507 and makes the samples readable again.
2. Changed the classes in the initial sample to make the comment stating that a portion of the navbar would be right aligned accurate.  This was a matter of changing me-auto to ms-auto to conform with bootstrap 5's utility classes.  This addresses #1510 
Fixes #1507 and #1510

docs: Navbar doc fixes 

---

packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
packages/bootstrap-vue-next/src/components/BPopover.vue
packages/bootstrap-vue-next/src/components/BTooltip.vue
packages/bootstrap-vue-next/src/directives/BTooltip.ts

closes #1503 
fix(BTooltip): close popover when opening dropdown
fix(BPopover): prop hide renamed to noHide, to be inline with other props.
fix(BPopover): expose hideFn renamed to hide

fix(BTooltip): close when opening dropdown, and other changes

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue

After upgrading to the latest version (0.14.8), we found that the `selectAllRows` function for BTable no longer works if the table uses a `provider` function rather than the static `items` prop. It did work previously (we were a ways behind before upgrading, around version 0.9.23). The PR switches back to using `computedItems.value` instead of `props.items` for the value assigned to `selectedItems.value` returning to how it was in earlier versions.
I reproduced the issue in a simple demo in `App.vue` in my `bootstrap-vue-next` fork. Applying the fix in this PR causes the selectAllRows function work work again.
```
<template>
<BContainer>
<BRow>
<BCol>
<h4 class="my-3">Table (Async Provider)</h4>
<BButton @click="testTable?.refresh()" class="me-2">Refresh</BButton>
<BButton …
```

fix(BTable): resolve selectAllRows no longer working with provider

---

packages/bootstrap-vue-next/src/components/BModal.vue
packages/bootstrap-vue-next/src/composables/useModalManager.ts

This PR introduces a small change to how the z-indices of active modals are calculated.
Currently there are cases ([issue 1516](https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1516)) where a newly opened modal will open behind an active modal.
The change to behaviour here is to calculate the z-index of a modal based on it's position in the stack of active modals. All modals have a z-index lower than or equal to 1055. The newer (high up on the stack) the modal is the close to 1055. The latest having a z-index of 1055. Inactive modals have a z-index of 1055 by default, the highest value. Meaning when they open they are on top by default until the z-index is adjusted.
There is a slightly different approach I tried which was just to calculate the z-index as `1055 + …

fix(BModal): Fix new modals stacking behind active modals

---

packages/bootstrap-vue-next/src/composables/useModalManager.ts

Fixes #1545 by ensuring the modal count is decremented in modalManager even when the transition doesn't have time to run (due to the element being removed immediately vs. hidden).
Sadly unable to write a unit test for this due to vitest not firing transition events.

fix(BModal): Ensure modal-open class is always removed (#1545)

---

apps/docs/src/data/components/gridSystem.data.ts

Update doc of BContainer component (https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1538):
- Remove `position` & `toast` props
- Update default values & add descriptions

docs(BContainer): update props

---

packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue

Currently it is not possible to pass variant or classes down to thead so the table's header just blends in with the rest of the table, this change simply passes the values of the existing properties to the place where they can take effect.

fix: Pass through table header/footer variant & classes

---

apps/docs/src/components/ComponentReference.vue
apps/docs/src/data/components/ComponentReference.ts
apps/docs/src/docs.md

- Update to accurately display the event and slot fields
- Support displaying multiple event args and slot scopes

docs: improve component reference

---

packages/bootstrap-vue-next/src/components/BPopover.vue
packages/bootstrap-vue-next/src/types/ComponentProps.ts
packages/bootstrap-vue-next/src/utils/floatingUi.ts

feat(BPopover): add peristent option to popover
fix(BPopover): default offset has changed in bootstrap css
closes #1615 

add peristent option to popover

---

packages/bootstrap-vue-next/src/directives/BToggle.ts
packages/bootstrap-vue-next/src/directives/toggle.spec.ts

Hello! v0.15, specifically #1532, introduced a regression in the BToggle directive that caused specifying ID as arg or href to be broken. This PR fixes that regression.
Also re-added toggle.spec.ts, copied as-is from v0.14.10. Those tests caught this regression and can prevent it from happening again.
The following were broken:
```html
<button v-b-toggle:test1>button</button><div id="test1"></div>
<a href="#test2" v-b-toggle>link</a><div id="test2"></div>
```

fix(BToggle): Passing ID as arg or href broken in v0.15

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue

feat(BTable): add prop sortCompareOptions

feat(BTable): add prop sortCompareLocale

---

packages/bootstrap-vue-next/src/components/BFormTags/_form-tags.scss

Relates to https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1668
I looked into what the textarea uses, and using the variable instead of the hard-coded value fixes it for the b-form-tags.

fix(BFormTags): dark mode compatibility

---

packages/bootstrap-vue-next/src/components/BTable/BTableSimple.vue

Add id attribute to BTableSimple component so it'll be transferred into the DOM
https://stackblitz.com/edit/github-yki5xm?file=src%2Fcomponents%2FComp.vue,src%2FApp.vue

BTable id attribute is not being transferred into the rendered DOM

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue

fix #1687 
emitting and listening to hover events on BTable
https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/53003820/d6631fb2-0724-4239-b073-9866e51cfc2e

fix(BTable): emitting and listening to hover events

---

apps/docs/src/data/components/formCheckbox.data.ts
apps/docs/src/docs/components/form-checkbox.md
packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue
packages/bootstrap-vue-next/src/components/BFormCheckbox/form-checkbox.spec.ts
packages/bootstrap-vue-next/src/components/BFormRadio/form-radio.spec.ts

This PR implements tri-state checkboxes by creating an indeterminate named model that tracks the indeterminate attribute on the control.  This addresses #1611.
I also implemented unit tests for BFormCheckbox that roughly map to the tests for BFormRadiobutton.  I, of course, added some testing around the indeterminate model, and while I was at it some tests around the primary model.
While writing the tests, I found and fixed a typo in ariaLabelledby (the 'b' in by was upper case).
A small replication or video walkthrough can help demonstrate the changes made. This is optional but can help observe the intended changes. A mentioned issue that contains a replication also works.
- [ x ] Bugfix :bug: - `fix(...)`
- [ x ] …

feat(BFormCheckBox): Implements tri-state checkbox

---

packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue
packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckboxGroup.vue
packages/bootstrap-vue-next/src/components/BFormCheckbox/form-checkbox.spec.ts
packages/bootstrap-vue-next/src/components/BFormFile/BFormFile.vue
packages/bootstrap-vue-next/src/components/BFormInput/BFormInput.vue
packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue
packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadioGroup.vue
packages/bootstrap-vue-next/src/components/BFormSelect/BFormSelect.vue
packages/bootstrap-vue-next/src/components/BFormTextarea/BFormTextarea.vue
packages/bootstrap-vue-next/src/composables/useFormInput.ts

Change @input for @update:modelValue event in BFormCheckbox, BFormCheckboxGroup, BFormRadio, BFormRadioGroup, BFormSelect, BFormTags and useFormInput
fix #1657

fix(): Remove @input in favor of @update:modelValue

---

packages/bootstrap-vue-next/src/components/BPagination/BPagination.vue
packages/bootstrap-vue-next/src/components/BPagination/pagination.spec.ts

Fix several issues with the BPagination
- Re-implement the missing first-page and last-page properties.  This pulled heavily from the work by @MewesK in #1686 and @VividLemon in #1723. 
- Fix the issue where page #2 and page # total-1 would disappear under some circumstances
- Slot scoped properties for the 'textual' (first, prev, next, last) slots are now implemented (these properties were documented in both this project and bsv-legacy)
- Fixed the hideEllipsis property to _always_ hide both ellipsis
- Fixed the aria labels for the prev, next and last buttons (they were all first).
- Changed the limit property from `number` to `Numberish`
- Added tests to validate that the # of page buttons shown are consistent taking into account the ellipsis buttons and firstNumber & lastNumber …

fix(BPagination): re-implemented the missing first-page and last-page

---

apps/docs/src/data/components/formCheckbox.data.ts
apps/docs/src/docs/components/form-checkbox.md

Fill out the docs for BFormCheckbox and BFormCheckboxGroup.
- Add the initial two examples from BSV legacy
- Add in the indeterminate checkbox use-case example
- Completely fill out the component reference data for both components
- Fix a number of small bugs in the docs
The thing I didn't fill out in the component reference is the buttonGroup booleanish value.  I need to understand how that works so I can document it, and I don't understand.  It appears to cause the rendering of the component to be skipped, overriding the value coming from the parent group, but I don't see how that works. …

docs(BFormCheckbox): Fill out docs and Component Reference

---

packages/nuxt/src/module.ts

resolves https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1758
see https://github.com/nuxt/nuxt/issues/25735
The issue is not that the plugin is not being called.
The problem is that Vite optimises the dependencies and so there are effectively two versions of bootstrap vue in your project, one registered and one not registered. (This is why it works when you remove the `node_modules` - you can instead just remove `node_modules/.cache` to reliably reproduce.)
(This is why the problem is only on first load.)
You can read more about this process [in the Vite docs](https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-include).
This resolves the issue by ensuring `bootstrap-vue-next` is optimised, though note that this will require users who use pnpm without …

fix(nuxt): optimize `bootstrap-vue-next`

---

apps/playground/src/components/Comps/TAvatar.vue
packages/bootstrap-vue-next/src/components/BAvatar/avatar.spec.ts
packages/bootstrap-vue-next/src/composables/useAvatarSize.ts
packages/bootstrap-vue-next/src/constants/regex.ts

Passing a string value that ends in `em` or`rem` to the `size` prop `BAvatar` converts them to `px` instead of their expected values.
The `BAvatar` component uses the `size` prop to change its size. The component applies styles based on the `size` prop. This prop does not properly parse string values that end in `em` and `rem` because of the `useAvatarSize` composable. This composable uses [VueUse's `useToNumber`](https://vueuse.org/shared/useToNumber/) method to determine if the `size` prop is a numeric value or not. [`useToNumber` source code](https://github.com/vueuse/vueuse/blob/4f84d63730e18d8408a9f05f72809f3de4a9315e/packages/shared/useToNumber/index.ts#L12) uses the [`parseFloat` ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat) method, …

fix(BAvatar): replace useToNumber in useAvatarSize composable

---

packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue
packages/bootstrap-vue-next/src/types/TableTypes.ts

Enable BTable ```tdAttr``` to be a function like old BV2

BTable tdAttr as function

---

apps/docs/.vitepress/theme/Layout.vue

Get Syntax Highlighting working again in the documentation.  This fixes #1738 
I'm explicitly pulling in the `vp-code.css` as well as several other files that seem appropriate.  It's unclear to me why https://github.com/vuejs/vitepress/pull/3237 caused this issue, as the file had been created and consumed by the default theme a couple of years ago.  In any case, this fixes the issue.  I haven't nailed down what each of the additional files does and if we're currently consuming them, but they seem like reasonable functionality.  We are using `custom-block.css` in `badge.md` and leaving out that file makes the tip section just disappear from the docs. So while I would normally go for the minimal fix it seems like including all of these files makes sense in this case.
Syntax highlighting is …

fix(docs): Enable Syntax Highlighting fixes #1738

---

packages/bootstrap-vue-next/src/components/BOverlay/BOverlay.vue

Replaced events for the BTransition component with @after-enter and @after-leave.
Errors of the type are occurring in the `BOverlay` component: 
` Uncaught (in promise) TypeError: Cannot read properties of null (reading 'Symbol(_leaveCb)') ` 
and 
` Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore') `.
This happens when the `showBoolean` state is rapidly changed in the child `Transition` block, after which everything inside `Transition` breaks until the page is fully reloaded. After investigating this case, I discovered that currently, in `Transition`, non-existent events `@on-after-enter` and `@on-after-leave` are being listened to, and this, along with the fact that inside `BTransition` there is a temporary slot node, i.e., `Transition` does not …

fix(events): update events for BTransition in component BOverlay

---

packages/bootstrap-vue-next/src/components/BTooltip.vue
packages/bootstrap-vue-next/src/types/ComponentProps.ts
packages/bootstrap-vue-next/src/utils/floatingUi.ts

in bsv2 the prop for tooltip is `noninteractive` which defaults to false. I think booleans which default to false aren't great for us. In bs5 tooltips aren't interactive at all. So I think this is a middle ground.

feat(BTooltip): add prop interactive

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue

BTable ```selectable``` works fine but...
using BTable ```provider``` attribute with pagination will loose the row selected class when page is changed.
with this PR when the ```primaryKey``` attribute (already present but unused) is set, the selection is checked by comparing the TableItem primaryKey attribute
Old BootstrapVue has primaryKey attribute:
"Name of a table field that contains a guaranteed unique value per row. Needed for tbody transition support, and also speeds up table rendering"
I think it can be used also for other things like selection which is a new feature

BTable check selection also using primaryKey attribute

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue

Referring to PR #1786 allows ```primaryKey``` attribute in dot string
Example: 
```vue
<BTable :items="items" selectable primary-key="product.id" />
```

BTable primaryKey dot string

---

apps/docs/src/docs/components/form-checkbox.md

Small changes to make the docs more consistent with BSV docs (the biggest one is just moving a section to line up).  Most of this is just adding "code" tags to identifiers/constants in the text.  The one 
N/A

docs(BFormCheckbox): Cleanup

---

packages/bootstrap-vue-next/src/components/BModal/BModal.vue
packages/bootstrap-vue-next/src/components/BModal/modal.spec.ts
packages/bootstrap-vue-next/src/types/ComponentProps.ts

As it's described on https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1776
add attrs and class props to the component
add unit test

BModal - Add attrs and class props to the component

---

packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
packages/bootstrap-vue-next/src/components/BOffcanvas/offcanvas.spec.ts

As it's described on https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1776
add attrs and class props to the component
add unit test

BOffcanvas - Add attrs and class props to the component

---

apps/docs/src/data/components/toast.data.ts
apps/docs/src/docs/components/toast.md

- Update the docs with the correct properties for the method show
- Add the description on the "Component Reference" section
Fix https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1769

BToast invalid docs

---

apps/docs/src/docs/components/collapse.md
packages/bootstrap-vue-next/src/components/BCollapse.vue
packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue
packages/bootstrap-vue-next/src/components/BLink/BLink.vue
packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue
packages/bootstrap-vue-next/src/components/BNav/nav-item-dropdown.spec.ts
packages/bootstrap-vue-next/src/utils/keys.ts

open/close -> show/hide

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
packages/bootstrap-vue-next/src/components/BTable/table.spec.ts

Add row-dbl-clicked event on BTable component
Fix #1795

fix(BTable): BTable rowDblClicked event not working

---

apps/docs/src/docs/components/form-group.md
apps/docs/src/docs/components/form-tags.md
apps/docs/src/docs/components/form.md
packages/bootstrap-vue-next/src/components/BFormTags/BFormTags.vue
packages/bootstrap-vue-next/src/components/BFormTags/form-tags.spec.ts

add limitTagText in the HTML
add BFormTags documentation
create some unit test for BFormTags
Fix #1804

[BFormTags]: limitTagsText props is not used in HTML

---

packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue

This PR adds to BOffcanvas 
- ```backdropVariant``` props types  'white' | 'transparent' to be the same as BOverlay
- ```backdropBlur``` prop to control BOverlay blur in BOverlay
- ```shadow``` props (like old BV) to control BOffcanvas shadow

BOffcanvas backdrop blur and shadow

---

CONTRIBUTING.md

As we get closer to v1, it would be great to have more people contributing to documentation and assessing parity with bootstrap-vue and bootstrap5.  This PR adds sections to contributing.md to encourage that.
n/a

docs: Add documentation and parity section to contributing.md

---

apps/docs/src/data/components/ComponentReference.ts
apps/docs/src/data/components/formCheckbox.data.ts
apps/docs/src/data/components/formRadio.data.ts
apps/docs/src/docs/components/form-checkbox.md
packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue
packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckboxGroup.vue
packages/bootstrap-vue-next/src/components/BFormCheckbox/form-checkbox.spec.ts
packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadio.vue
packages/bootstrap-vue-next/src/components/BFormRadio/BFormRadioGroup.vue
packages/bootstrap-vue-next/src/components/BFormRadio/form-radio.spec.ts
packages/bootstrap-vue-next/src/composables/useFormCheck.ts
packages/bootstrap-vue-next/src/utils/keys.ts

Implement the [reverse](https://getbootstrap.com/docs/5.3/forms/checks-radios/#reverse) and [without-label](https://getbootstrap.com/docs/5.3/forms/checks-radios/#without-labels) features of checkboxes and radio buttons.
Reverse is implemented as a property on BFormCheckbox and BFormCheckboxGroup
Without Labels is implemented by not including the form-checkbox class when there is no default slot
In addition:
- Implemented and tested the same properties in BFormRadio and BFormRadioGroup
- Updated the documentation for BFromCheckbox and BFGormCheckboxGroup
- Made scope option in the ComponentReference data (because it is)
- Removed input and change events from BFormCheckboxGroup - these events were removed from BFromCheckbox in #1696  so it doesn't seem like it makes sense to keep them in …

feat(BCheckbox)!: Implement reverse and without label

---

packages/bootstrap-vue-next/src/directives/BPopover.ts
packages/bootstrap-vue-next/src/directives/BTooltip.ts
packages/bootstrap-vue-next/src/utils/floatingUi.ts

The PR fixes #1232 (One App for each tooltip), by eliminating the need to create a new app for each tooltip or popover. I used the `render` function from Vue to achieve this. One issue I experienced with this method was it did not update when props changed. 
To get around this I had to remove the old rendered component, then re-render it on update
check #1232 
PS: this is my first open-source contribution, please be easy on me :))

fix(BPopover and Btooltip): Fixes bootstrap-vue-next#1232 - do not create a new app fro each tooltip or popover

---

packages/bootstrap-vue-next/src/components/BPopover.vue
packages/bootstrap-vue-next/src/components/popover.spec.ts

fix(BPopover): fix injection out of setup context.

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue

This PR allow dot syntax in BTable ```sortBy```
```vue
<template>
<BContainer>
<BRow>
<BCol>
<BTable :items="items" :sort-by="[{key: 'address.city', order: 'desc'}]" />
</BCol>
</BRow>
</BContainer>
</template>
const items = [
{
id: 1,
name: 'John',
address: {
city: 'Rome',
},
},
{
id: 2,
name: 'Aron',
address: {
city: 'Turin',
},
},
{
id: 3,
name: 'Zoe',
address: {
city: 'Turin',
},
},
{
id: 4,
name: 'Paul',
address: {
city: 'Milan',
},
},
]
</script>
```

BTable - allow dot in sortby key

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue
packages/bootstrap-vue-next/src/components/BTable/table-lite.spec.ts
packages/bootstrap-vue-next/src/components/BTable/table.spec.ts

For use cases when row items are defined as functional objects, it's convenient for the original object to be passed through to the scoped slots. The object still has to not contain loops and correctly transform through the JSON.parse(JSON.stringify()) loop, but it is returned to the client code intact.
The requirements for this to work are:
1. The table must contain a primary-key property
2. The object keys must not contain "." - I don't believe this is an issue, because the use case for this kind of pass-through is well-behaved typescript objects, which should have property names containing "."
If this is acceptable, I'll get documentation including the limitations (and probably some stuff around it) in as a follow-up PR.
Included in the test cases in the PR.
**What kind of change does …

fix(BTable): Pass through original records to slots when primary key is defined

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue
packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue
packages/bootstrap-vue-next/src/components/BTable/table-lite.spec.ts
packages/bootstrap-vue-next/src/components/BTable/table.spec.ts

…es instead
fix(BTable): selectedItems not clearing values properly fixes #1878
fix(BTable): selectedItems with range not displaying class
test(BTableLite): toggle details functionality
test(BTable): selectedItems functioanlity

fix(BTable): selectedItems not clearing values properly fixes #1878

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue

This PR partially solves #1875 
It allows BTable internal selection delete when ```primaryKey``` prop is provided

BTable delete selection when primary-key

---

apps/docs/src/data/components/formCheckbox.data.ts
apps/docs/src/docs/components/form-checkbox.md
apps/docs/src/docs/migration-guide.md
apps/docs/src/docs/types.md
packages/bootstrap-vue-next/src/types/exports/index.ts

This PR should get the documents up to date and confirm that they are [at parity](https://1drv.ms/x/s!AiUqzkjNYGL6ieBPpQpcR41wo1laZQ?e=DYykFl) with BSV and BS5
- Document 'Without Labels'
- Document all types
- Export `AriaInvalid`, which was used but not exported
- Start general migration docs to cover cases that are used in these components

docs(BCheckBox*): Small changes to get documentation to parity

---

apps/docs/src/docs/configurations/global-options.md

According to [source code of defaultsPlugin](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/8e73b177051d4403ca7a159e7c11707de15e638c/packages/bootstrap-vue-next/src/plugins/defaultsPlugin.ts#L6), we need to use `plugins` key to specify global properties of components.
I have spend some time to figure out that there is a typo in the docs.

docs(Global Options) update example code

---

packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
packages/bootstrap-vue-next/src/types/ComponentProps.ts

Allow specifying the width of the sidebar with a prop. This could be achieved with passing the `style` attribute, but it would be simpler for migrations if it could use the same props as `bootstrap-vue` (I think the aliases should be built in, too)
```vue
<template>
<BContainer>
<BButton @click="click">Show OffCanvas</BButton>
<BOffcanvas v-model="show" width="20em" />
</BContainer>
</template>
import {BContainer, BOffcanvas, BButton} from './components'
import {ref} from 'vue'
const show = ref(false)
const click = () => {
show.value = !show.value
}
</script>
```

feat(BOffcanvas): allow specifying a width

---

apps/docs/src/docs/types.md
packages/bootstrap-vue-next/src/components/BTable/BTable.vue
packages/bootstrap-vue-next/src/types/TableTypes.ts

Adds the ability to filter BTables by a formatter function; either with a `TableFieldFormatter<T>` function supplied to the `filterByFormatted` prop or by a similar function supplied to the corresponding `formatter` prop when `filterByFormatted` is set to `true`. The code is very similar to the implementation for `sortByFormatted` in the codebase. Solves #1413 .
```
<template>
<BContainer>
<BTable :items="items" :fields="fields" :filter="filter" :filterable="['gender']" />
</BContainer>
</template>
import {ref} from 'vue'
import type {TableItem} from './types'
const items = [
{name: 'John', age: 10, gender: 'm'},
{name: 'Abby', age: 20, gender: 'f'},
{name: 'Tom', age: 47, gender: 'm'},
{name: 'Jane', age: 26, gender: 'f'},
]
const fields = [
{key: 'name', label: …
```

feat(BTable): adds the ability to filter by formatter

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue

`aria-sort` for _th_ now gets changed back to 'none' when no longer sorting. This didn't work previously as, when clicking a field 3 times; going from sort 'asc' -> 'desc' -> no longer sorting, it removes the `order` key from sortByModel but the object still exists, still contains a key, so the previous check of `value === undefined` is not sufficient for returning `aria-sort` as 'none'. Hence the change, to check for 'desc', check for 'asc' then return 'none' if not. I will use this to help style nonsorted table headers. …

fix(BTable): fixed aria-sort for th gets changed back to 'none' when no longer sorting

---

apps/docs/.vitepress/theme/Layout.vue

When search was added to the docs in #1577 color mode was propagated to the search control by manually adding the 'dark' class to the root document. This the doc builds to emit a whole bunch of `document not defined` errors.
The fix is to use a more vue-like method of adding the `dark` class to the `VPNavBarSearch` component.  I also renamed the variable that holds the result of the call to `useColorMode` to `colorMode` from `dark` as that makes the code more readable.
Docs now build clean, so this fixes #1703.
`pnpm build` from the docs directory should not produce warnings.

docs: fix warnings by replacing direct DOM manipulation fixes #1703

---

apps/docs/src/data/components/formSelect.data.ts
apps/docs/src/docs/components/form-select.md
apps/docs/src/docs/migration-guide.md

Check `BFormSelect*` components and docs for parity, fix minor bugs in the docs, fill out the component data and update the migration guide.
I also updated the parity spreadsheet to reflect the status of these components.
N/A

docs(BFormSelect): Fix bugs in docs and fill out component data

---

apps/docs/src/data/components/formSelect.data.ts
apps/docs/src/docs/types.md
packages/bootstrap-vue-next/src/types/ComponentProps.ts
packages/bootstrap-vue-next/src/types/SelectTypes.ts
packages/bootstrap-vue-next/src/types/exports/index.ts

This is a follow-up for PR #1956 to create a `SelectValue` type and use it the same way that we use model types for `FormCheckbox` and `FormRadiobutton`
I also updated the documentation.
N/A

fix(BFormSelect): Create a SelectValue type for consistency

---

apps/docs/.vitepress/theme/Layout.vue

Code blocks are currently not respecting dark mode (the text in the code block is using the light-mode colors).
The current solution is to go back to manually setting/removing `class='dark'` on the `HTML` tag, but to set it up in the `onMounted` hook, which only runs on the client.
----
I'm keeping the notes below in case I (or someone else) wants to take a stab at a more elegant solution in the future.
@VividLemon - This fixes dark mode, but regresses the documentation warning fix, I've done a bunch of exploration and haven't found a better fix. If you've got a chance to take a look and point me in the right direction, that would be great; otherwise, I'll sleep on it and take another look later.
I broke this with #1703 - specifically the code that pulled out setting/clearing class="dark" …

docs: get dark mode working again

---

apps/docs/src/components/NotYetImplemented.vue
apps/docs/src/data/components/form.data.ts
apps/docs/src/docs/components/form.md
apps/docs/src/utils/common-props.ts

I went through the BSVN docs and component references for BForm and its helpers and updated them based on BS5 changes. The biggest changes were inline and floating labels.  I've also updated the parity report.
I'll be pushing a couple of small code changes against BFormFloatingLabel and BForm to get these up-to-date. Trying to keep code and docs separate where possible.
N/A

docs(BForm): Update docs and checked parity

---

.github/workflows/ci.yaml
.github/workflows/docs-deploy.yaml
.github/workflows/npm-publish-main.yaml
.github/workflows/npm-publish-nuxt.yaml
.github/workflows/release-main.yaml

We are encountering issues like this in CI:
https://github.com/bootstrap-vue-next/bootstrap-vue-next/actions/runs/9799205309/job/27060648641
The way to resolve this issue can be found here:
https://github.com/pnpm/action-setup/issues/135

ci: Increase pnpm/action-setup@v2 to @v4 to prevent ci failures

---

apps/docs/src/docs/types.md

The Types page appeared to have the AriaInvalid and Alignment types under the wrong headings. This should move them to the correct positions.

docs(types.md): move types under correct headings

---

apps/playground/src/components/Comps/TForm.vue
packages/bootstrap-vue-next/src/components/BForm/BForm.vue
packages/bootstrap-vue-next/src/components/BForm/BFormFloatingLabel.vue
packages/bootstrap-vue-next/src/components/BForm/BFormRow.vue
packages/bootstrap-vue-next/src/components/BForm/form-floating-label.spec.ts
packages/bootstrap-vue-next/src/components/BForm/form.spec.ts
packages/bootstrap-vue-next/src/types/ComponentProps.ts

- The `text` prop on `BFormFloatingLabel` used the value of that property as the fallback content of the `default` slot. This doesn't work, that slot has to contain one of select few form controls. Putting plain text there just generates ugliness.
- Make slots required where appropriate (`BForm`, `BFormFloatingLabel` and `BFormRow`)
[stackblitz](https://stackblitz.com/edit/github-llmgfm?file=src%2Fcomponents%2FComp.vue)
```
<template>
<Container>
<BRow
><BCol>
<BForm class="floating-label">
<BInput
id="floatingEmail"
type="email"
class="form-control"
placeholder="Email address"
label="Email address"
/>
<BInput
id="floatingPassword"
type="password"
placeholder="Password"
label="Password"
/>
</BForm> </BCol
></BRow>
<BRow
><BCol>
<BForm>
<BFormFloatingLabel
label="Email address" …
```

fix(BFormFloatingLabel): Clean up props

---

apps/docs/.vitepress/theme/Layout.vue
packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue

This fixes an issue caused by #1992 where the overlay in `BOffCanvas` was not behaving as expected (see repro).
Revert to using `BOverlay` rather than manually setting up an overlay in `BOffcanvas`
I didn't dig further to see how hard it would be to get this working with out using the `BOverlay` component, I'm not sure that would be useful (possibly slightly better performance?)
See the docs site against main:

fix(BOffcanvas): Fix regression in docs caused  by #1992

---

apps/docs/.vitepress/config.mts
apps/docs/package.json
package.json
pnpm-lock.yaml
turbo.json

The markdown tables in the docs are unformatted. The default theme has custom styles for tables. It seems preferable to use bootstrap table stylings. This means adding the `table` and `table-striped` classes to the tables. The only way I could find to do that was to use a markdown-it extension. This seems to work fairly well, but I'm happy to take another approach if someone has a better idea.
Also, it looks like `turbo` is set to `latest` in the main `package.json` - I _think_ that's what's causing the cascade of changes in the `lock.yaml` file. I believe that also forced the change of `pipeline` to `tasks` in the turbo.config  and required that the main package have a name. I'm happy to back all those things out if I can get some direction on how to do that (I'd try to set turboto 1.^, …

docs: get markdown table formatting working with bootstrap

---

packages/bootstrap-vue-next/src/components/BModal/BModal.vue

This is a response to the omission of correction in https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2008 .
Changed the initial value of withDefaults.

fix(BModal): Fix with defaults ok title

---

apps/playground/src/components/Comps/TFormGroup.vue
packages/bootstrap-vue-next/src/components/BFormGroup/BFormGroup.vue
packages/bootstrap-vue-next/src/components/BFormGroup/form-group.spec.ts

Rename prop labeSrOnly to labelVisuallyHiddes as per the BS5 change
Also fix the types for labelAlign* - the can only be strings not number or boolean

fix(BFormGroup): change labelSrOnly to labelVisuallyHidden as per BS5

---

apps/docs/src/data/components/modal.data.ts
apps/docs/src/data/components/offcanvas.data.ts
packages/bootstrap-vue-next/src/components/BModal/BModal.vue
packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
packages/bootstrap-vue-next/src/composables/useActivatedFocusTrap.ts
packages/bootstrap-vue-next/src/types/ComponentProps.ts

feat(BModal) add prop noTrap to disable focus trapping
fix(BOffcanvas): add focus trapping to offcanvas
fix(BModal): in coordination with prop noTrap and adding no focus trapping to opened offcanvas, fixes #1996 -> as trap has moved to offcanvas
docs: add noTrap

fix(BModal): use focus trap default of 'window.document.body' fixes 2016

---

apps/playground/src/components/Comps/TFormCheckbox.vue
packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue

Checkbox `state === false` was resolving to undefined (which is effectively the null state) if there was no parent. Instead of using the parent value for all `falsey` values, I'm checking that the direct prop is `true` or `false` and only falling back to the parent if it's not.
See #2017 

fix(BFormCheckbox): Handle contextual state === false correctly (Fixes #2017)

---

apps/docs/src/data/components/formCheckbox.data.ts
apps/docs/src/data/components/formInput.data.ts
apps/docs/src/docs/components/form-input.md
apps/docs/src/docs/migration-guide.md
apps/docs/src/utils/common-props.ts

Update the docs and component data for BFormInput to get them to parity with the code (including the couple of unimplemented features). I've also updated the parity report to reflect this work.
N/A

docs(BFormInput): Get the docs to parity with the code

---

apps/docs/src/data/components/modal.data.ts
packages/bootstrap-vue-next/src/components/BModal/BModal.vue

BModal - add `backdrop` and `esc` events #2054

feat: BModal - add `backdrop` and `esc` events #2054

---

apps/docs/src/docs/components/modal.md
apps/docs/src/docs/composables/useModalController.md
apps/docs/src/docs/migration-guide.md

`useModalController` is a reasonable replacement for `$bvModal.msgBoxOk` and `$bvModal.msgBoxConfirm`, but it took me a little while to figure out the mapping, so I thought that learning would be a decent addition to the migration guide.
This more fully documents the solution to #1279 and the message box part of #1068
Also fixed a small bug in the `useModalController` docs that contributed to my confusion.
N/A

docs(useModalController): Add migration info for msgBoxOk & Commit

---

apps/docs/src/docs/components/popover.md
apps/playground/src/components/Comps/TPopover.vue
packages/bootstrap-vue-next/src/components/BPopover.vue
packages/bootstrap-vue-next/src/types/ComponentProps.ts

Add `close-on-hide` prop to `BPopover` to have the popover close when it's hidden by the `hide` middleware
https://github.com/user-attachments/assets/87f3e709-7d76-49a0-82ca-693ab1e61498
I'll note that I'm not sure if the format of the docs is quite correct, especially the `boundary-padding`, it feels a bit hacky, but I'm not familiar with a better way.

feat(BPopover): Add close-on-hide prop to close the popover when it hides by clipping out of view

---

apps/docs/src/data/components/formInput.data.ts
apps/docs/src/data/components/formTextarea.data.ts
apps/docs/src/docs/components/form-input.md
apps/docs/src/docs/components/form-tags.md
apps/docs/src/docs/components/form-textarea.md
apps/docs/src/docs/migration-guide.md
apps/docs/src/utils/common-props.ts

Parity pass on `BFormTextArea`
Document the deprecation of the `lazy`, `number`, and `trim` properties on `BFormInput` and `BFormTextArea` and the replacement by `v-model` modifiers.
Also updated the parity spreadsheet.
N/A

doc(BFormTextArea,BFormInput): Parity pass + document deprecation of lazy, number and trim

---

packages/bootstrap-vue-next/src/components/BAvatar/BAvatar.vue
packages/bootstrap-vue-next/src/components/BAvatar/BAvatarGroup.vue
packages/bootstrap-vue-next/src/composables/useRadiusElementClasses.ts
packages/bootstrap-vue-next/src/utils/keys.ts
packages/bootstrap-vue-next/tests/composables/useRadiusElementClasses.spec.ts

- Added in an SVG so that the default Avatar shows the person-fill icon as in BSV
- Fixed the edge rounding to be in the correct order
- Make the default rounding if no rounded properties are set 'circle' - this makes it work the same way BSV did.
See examples in the docs. These are all issues that I found from broken examples in the `BAvatar` documenation

fix(BAvatar): Several fixes from parity pass

---

packages/bootstrap-vue-next/src/components/BForm/BForm.vue

I can't find any reason to override the submit event's default behavior on `BForm`. I think the best way to address #2124 is to remove the custom event handler and let the native event propagate. 
I might be missing something about how the event propagation in Vue3 works, but I tested with a simple form and the event is coming through the way I expect.
See issue

fix(BForm): Remove confusing prevent default on form submit - Addresses #2124

---

apps/docs/src/data/components/avatar.data.ts
apps/docs/src/data/components/badge.data.ts
apps/docs/src/docs/components/badge.md
apps/docs/src/docs/migration-guide.md
packages/bootstrap-vue-next/src/types/ComponentProps.ts

- Updated docs & fixed bugs in docs
- Filled out component reference
- Updated Parity Spreadsheet
- Removed orphaned text-indicator prop (this isn't implemented in BSV, my guess is that it was an artifact of an earlier implementation of BSVN).
N/A

docs(BBadge): Parity pass

---

apps/docs/src/components/NotYetImplemented.vue
apps/docs/src/data/components/button.data.ts
apps/docs/src/docs/components/button.md
apps/docs/src/docs/migration-guide.md

Parity pass for BButton and BCloseButton
- updated component reference
- cleaned up docs and added a section for the `loading` props
- filled out the parity spreadsheet 
- added the ability to specify additional details in `NotYetImplemented` component
-
N/A

doc(BButton): Fill out component reference and clean up docs

---

packages/bootstrap-vue-next/src/components/BLink/BLink.vue

The BLink component currently does not pass through the target prop if it is rendered as a RouterLink. Works for normal links with href.

fix: add target to BLink RouterLink component

---

apps/docs/.vitepress/config.mts
apps/docs/.vitepress/markdown-it-class.d.ts
apps/docs/.vitepress/plugins/demo-container.ts
apps/docs/package.json
apps/docs/src/docs/components/breadcrumb.md
apps/docs/src/docs/components/demo/BreadcrumbAsArray.vue
apps/docs/src/docs/components/demo/BreadcrumbManual.vue
apps/docs/src/docs/components/demo/BreadcrumbOverview.vue
apps/docs/src/docs/components/demo/BreadcrumbSlots.vue
pnpm-lock.yaml

This PR sets up a system to clean up how we implement demos/examples in our docs.
- I wrote a markdown-it plugin to override the snippet plugin syntax (<<< to take a DEMO marker, which will generate our entire <HighlightCard> demo section including the running demo and the syntax highlighted code with the single line + an external file.
- I added and configured `unplugin-vue-components` to clean up the import statements in both the demos and the *.md files.
- In addition, I used `unplugin-vue-components` to auto-register the demo components in markdown files, which removes the need to do any fancy footwork with adding import statements to the *.md files for those components.
Take a look at `breadcrumb.md` for an example of how this has cleaned up the markdown.
At this point, I believe the …

Demo file plugin

---

packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItemButton.vue
packages/bootstrap-vue-next/src/types/ComponentProps.ts

Currently, attributes passed to BDropdownItemButton are swallowed. But we want to add them to the list element like it was in BootstrapVue.

fix: pass attributes through in BDropdownItemButton

---

packages/bootstrap-vue-next/src/components/BPagination/BPagination.vue

This PR resolves #2146 
We don't really need to use reusable templates in BPagination after the refactor I did earlier this year. I almost pulled them out then, so I just pushed a bit more of the logic out to the script section and landed on a solution that just has a simple loop with a single if/else in the template.
See #2146

fix(BPagination): Get rid of bad binding on li

---

packages/bootstrap-vue-next/src/components/BPagination/BPagination.vue
packages/bootstrap-vue-next/src/components/BPagination/pagination.spec.ts

This PR addresses #2165 
I misunderstood the intention of the `hide-goto-end-buttons` flag. It should just hide the explicit `first` and `last` buttons, not the  first page or last page button (which are labeled with the page numbers). That is how BSV works and it seems reasonable so I've reimplemented it that way.
I also discovered an issue that was either because of the refactor I recently did or a change in how vue handles keys in a for loop. In either case, having a duplicate key in the array for the ellipsis causes some weird update problems (at lest in dev mode) so I removed that ambiguity while I was at it.
See #2165

fix(BPagination): hide-goto-end doesn't hide first-page or last-page

---

packages/bootstrap-vue-next/src/directives/BPopover.ts
packages/bootstrap-vue-next/src/directives/BToggle.ts
packages/bootstrap-vue-next/src/directives/BTooltip.ts
packages/bootstrap-vue-next/src/directives/toggle.spec.ts
packages/bootstrap-vue-next/src/utils/floatingUi.ts

closes #2164 
solved it in a different way in different directives:
toggle: it just delays the remove and add of event listener for 0ms so that the original event fires
tooltip/popover: check if directive bindings have changed before we destroy the old and create a new vue instance with the tooltip.

fix directives on element update during interaction

---

apps/docs/src/components/ComponentReference.vue
apps/docs/src/components/NotYetImplemented.vue
apps/docs/src/data/components/formTags.data.ts
apps/docs/src/docs/components/card.md
apps/docs/src/docs/migration-guide.md
apps/docs/src/types/index.ts
apps/docs/src/utils/common-props.ts
apps/docs/src/utils/link-props.ts

- Small tweak to the NYI component to make it a little less red
- Used NYI in all of the *.md files that previously had free-text notes
- Added an notYetImplemented flag to props and scoped slot args
N/A

docs: Use Not Yet Implemented Component consistently

---

apps/docs/.vitepress/config.mts
apps/docs/.vitepress/plugins/demo-container.ts
apps/docs/src/components/HighlightCard.vue
apps/docs/src/docs/demo/AlertAfter.vue
apps/docs/src/docs/demo/AlertBefore.vue
apps/docs/src/docs/demo/AvatarIcon.vue
apps/docs/src/docs/demo/ModalConfirm.vue
apps/docs/src/docs/demo/ModalMessageBox.vue
apps/docs/src/docs/demo/SyncAfter.vue
apps/docs/src/docs/demo/SyncBefore.vue
apps/docs/src/docs/migration-guide.md

- Refactor the migration guide to put code into separate files
- Add the idea of a code fragment in our `markdown.it` plug-in for where we're just displaying the sample code, not running the demo (useful for migration before/after among other things)
- Make HighlightCard recognize when there isn't a running component, and don't add in the first `BCardBody`, which was just an annoying amount of blank space.
- Generalize the configuration of the auto-resolver to grab *.vue files in any demo directory so samples can be in a demo directory directly adjacent to the *.md file in various places in our docs.
A small replication or video walkthrough can help demonstrate the changes made. This is optional, but can help observe the intended changes. A mentioned issue that contains a replication also …

docs: Migration Guide refactor

---

apps/docs/src/docs/components/avatar.md
apps/docs/src/docs/components/badge.md
apps/docs/src/docs/components/button.md
apps/docs/src/docs/reference/color-variants.md
apps/docs/src/docs/reference/demo/VariantInteractions.vue
apps/docs/src/utils/common-props.ts
packages/bootstrap-vue-next/src/composables/useColorVariantClasses.ts
packages/bootstrap-vue-next/tests/composables/useColorVariantClasses.spec.ts

This PR addresses #2122 among other things. Since the bootstrap 5 behavior makes `bg-variant` and `text-variant` override `variant` (it's actually `bg-*` and `text-*` classes overriding `text-bg-*` classes) - the most straightforward was to solve this problem is to just all of the variant props set their respective classes and let bootstrap sort it out.
See #2122

doc(variant): interaction between variant, bg-variant & text-variant

---

packages/bootstrap-vue-next/src/utils/floatingUi.ts

closes #2225 
Placeholder `<span>`-elements generated by `vBPopover`- and `vBTooltip`-directives consumed space in flex containers. By adding `position: absolute` the placeholder element it won't effect the user`s layout anymore.
```vue
<template>
<div style="margin: 10vw; border: 1px solid grey">
<div class="d-flex justify-content-between align-items-center">
Heading
<BButton v-b-tooltip="'test'" size="sm" class="btn-smaller">
Test
</BButton>
</div>
</div>
</template>
```
Before:
Now:

fix(vBPopover): add position absolute to floating directives

---

apps/docs/src/components/ComponentReference.vue
apps/docs/src/docs/components/breadcrumb.md
apps/docs/src/docs/components/card.md
apps/docs/src/docs/components/carousel.md
apps/docs/src/docs/components/image.md
apps/docs/src/docs/components/pagination.md
apps/docs/src/docs/migration-guide.md

It looks like `unplugin-vue-components` has a bug where it doesn't correctly handle `<script setup='ts'>`  in vitepress (possibly in SSR mode in general). I will continue to refine https://github.com/unplugin/unplugin-vue-components/issues/801 and see if I can get an upstream fix, but this workaround gets us up and running again.
All the docs that were depending on `unplugin-vue-component` now use `<script>` rather than `<script setup>` sections. Since all we're doing in these files is importing data for the component reference, this still seems like a big win over not using `unplugin-vue-component`.
I also started getting a circular reference error when using the tooltip composable, so I converted to the component.
Look at the breadcrumb or carousel documentation under `app\docs` after …

docs: Work around unplugin bug

---

apps/docs/src/docs/types.md
packages/bootstrap-vue-next/src/types/BreakpointProps.ts
packages/bootstrap-vue-next/src/types/ComponentProps.ts

Update types to more closely match what is allowed by bootstrap:
- Column Order values can only be 1-5, 'first' and 'last' now represented by `ColsOrderNumbers': https://getbootstrap.com/docs/5.3/layout/columns/#order-classes
- Column offsets can be number 0-12: https://getbootstrap.com/docs/5.3/layout/columns/#offsetting-columns
- Gutters can be 0-5: https://getbootstrap.com/docs/5.3/layout/gutters/#change-the-gutters
I found these while doing the parity pass on the grid system, I'll push up a separate PR for the documentation updates.
**What kind of change does this PR introduce?** (check at …

fix(grid): Correct some inconsistencies in breakpoint types

---

apps/docs/.vitepress/theme/Layout.vue

fix https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2241. `vitepress` has been ignoring this issue for way too long, so I decided to make this PR.

docs: fix tables are not being formatted

---

apps/docs/src/docs/migration-guide.md

As part of the parity pass, I went through and added notes for all not yet implemented or deprecated components. I errored towards marking things as NYI rather than deprecated. I don't think that any of the currently unimplemented components would necessarily block us from declaring a v1 (other than possibly the date/time related ones, which I believe @VividLemon is looking at now). Things like Jubotron, and Media, and PaginationNav can reasonably be worked around using straight bootstrap classes - if someone feels compelled to smooth things out by implementing BSVN components the wouldn't be breaking changes and could be added at any time, including after we declare the library production ready.
I'd be fine with drawing the line differently if @VividLemon or @xvaara has an opinion.
N/A …

docs(migration): Document unimplemented components

---

packages/bootstrap-vue-next/src/components/BTable/BTableLite.vue

Hi,
I recently tried to migrate a BTable that has a custom footer.
Sadly it's not possible to add a variant (or some styles) on the BTfoot component itself.
In following example, the `dark` variant would not be applied on the footer:
```vue
<BTable foot-variant="dark" ... >
<template v-slot:custom-foot="fields">
<BTr>
<BTh class="text-center align-middle text-nowrap">{{ value1 }}</BTh>
<BTh class="text-center align-middle text-nowrap">{{ value2 }}</BTh>
</BTr>
</template>
</BTable>
```
This little patch should be enough to fix the issue.

BTable : make it possible to style custom footers

---

apps/docs/.eslintrc.cjs

Fix lint error in docs by ignoring *.js fragment files in demo directories.

docs: fix lint error

---

apps/docs/.vitepress/theme/Layout.vue

- Fixed several 'new' lint errors in `Layout.vue` (possibly due to the recent upgrade of eslint)
- The on this page formatting was being broken by the teleport when shown as an offfcanvas. I just pulled out the `.table-of-contents` styling from the otp-sidebar - we're only using `table-of-contents` in the one place, so it seemed the cleanest solution (and I suspect if we decide to do a TOC embedded elsewhere, we'd want these stylings anyway),
View the docs in a small window.
Open the on this page overlay.

docs: Fix lint errors in Layout.vue + styling of otp

---

packages/bootstrap-vue-next/src/components/BPopover/BPopover.vue
packages/bootstrap-vue-next/src/composables/useShowHide.ts

We were only hiding the elements opacity, not hiding it display.

better fix for the hidden on reference out of view.

---

packages/bootstrap-vue-next/src/components/BCollapse/BCollapse.vue
packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
packages/bootstrap-vue-next/src/components/BModal/BModal.vue
packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
packages/bootstrap-vue-next/src/components/BPopover/BPopover.vue
packages/bootstrap-vue-next/src/components/BToast/BToast.vue

It seems vue transitions with prop appear behave differently in dev and production builds.

fix(useShowHide): fix transition triggering in production build

---

apps/docs/src/data/components/accordion.data.ts
apps/docs/src/data/components/carousel.data.ts
apps/docs/src/data/components/nav.data.ts

Fix type errors in a couple of our component references where the docs didn't match the code. Also removed a bit of redundancy in the docs in `accordian.data.ts`.
@VividLemon, @xvaara I'm also seeing this error in showhide-props.ts:
```
Property 'showHide' does not exist on type 'BvnComponentProps'.ts(2339)
```
`showHide`  doesn't appear to be declared in `bootstrap-vue-next.mjs`, but it is declared in `BoostrapVueOptions.ts` - I think that's what's being used to build the exports, but I can't follow the thread of how things are being built to figure out what is going on. I'm doing a `pnpm import`, is there something else I need to do to rebuild the exports from bsvn for local consumption by the docs?
A small replication or video walkthrough can help demonstrate the changes made. This is …

docs: fix type errors from missing props

---

apps/docs/src/components/ShowHideProps.vue
apps/docs/src/data/components/collapse.data.ts
apps/docs/src/data/components/modal.data.ts
apps/docs/src/data/components/pagination.data.ts
apps/docs/src/docs/migration-guide.md
apps/docs/src/utils/common-props.ts
apps/docs/src/utils/dropdown-common.ts
apps/docs/src/utils/showhide-props.ts

This is an attempt to encapsulate the prop changes in #1821. I will also get to the emit changes, but they were more straightforward so I'll tack them separately.
@xvaara In the process of gong through the code for #1821 I found a number of things that I either don't understand or are internally inconsistent (as well as the bug I filed yesterday #2385)
I'm going to list them here for now, but happy to pull them out as a bug or bugs if you agree they are issues:
- Is there a reason that transProps, noAnimation, and noFade aren't implemented on BAccordianItem and BAccordian? They're commented out and it feels like the should be implemented.
- BAlert and BCarousel both have `fade` rather than `noFade` - for carousel, this makes a lot of sense since this is referring to the transition within …

docs: migration guide for changes to show/hide related props

---

packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
packages/bootstrap-vue-next/src/components/BCollapse/BCollapse.vue
packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
packages/bootstrap-vue-next/src/components/BModal/BModal.vue
packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue
packages/bootstrap-vue-next/src/components/BOffcanvas/BOffcanvas.vue
packages/bootstrap-vue-next/src/components/BPopover/BPopover.vue
packages/bootstrap-vue-next/src/components/BToast/BToast.vue
packages/bootstrap-vue-next/src/composables/useShowHide.ts

fixes:
> * `toggle-prevented` event is  missing on `BCollapse`, `BNavItemDropdown`
> * `*-prevented` should have value arg of BvTriggerableEvent
> * `BOffCanvas`, `BPopover`, and `BToast` don't declare events `toggle` or `toggle-prevented`, but they expose `toggle`, so I think they will emit those events?

fix(useShowHide): add all the emits

---

apps/docs/src/data/components/form.data.ts
apps/docs/src/data/components/formSelect.data.ts
apps/docs/src/docs/demo/CheckboxGroupMigration.vue
apps/docs/src/docs/migration-guide.md
apps/docs/src/utils/common-props.ts

- Documents the deprecation of the `[*-]html` props to the migration guide and the justification for doing so - @VividLemon please feel free to correct me if I am misrepresenting this.
- Clean up some dead entries in `common-props.ts`
- Add the `option` slot to the component definitions that didn't have it.
- This should get the migration guide and docs to fully reflect #1930
- The parity report is updated as well
N/A

docs(migration): add html prop deprecation to the migration guide

---

apps/docs/src/components/ComponentReference.vue
apps/docs/src/components/StyleExtension.vue
apps/docs/src/components/TableOfContentsNav.vue
apps/docs/src/data/components/avatar.data.ts
apps/docs/src/data/components/button.data.ts
apps/docs/src/data/components/buttonGroup.data.ts
apps/docs/src/data/components/buttonToolbar.data.ts
apps/docs/src/data/components/card.data.ts
apps/docs/src/data/components/carousel.data.ts
apps/docs/src/data/components/form.data.ts
apps/docs/src/data/components/formRadio.data.ts
apps/docs/src/data/components/formSelect.data.ts
apps/docs/src/data/components/formSpinbutton.data.ts
apps/docs/src/data/components/formTags.data.ts
apps/docs/src/data/components/formTextarea.data.ts
apps/docs/src/data/components/gridSystem.data.ts
apps/docs/src/data/components/image.data.ts
apps/docs/src/data/components/link.data.ts
apps/docs/src/data/components/nav.data.ts
apps/docs/src/data/components/offcanvas.data.ts
apps/docs/src/data/components/overlay.data.ts
apps/docs/src/data/components/placeholder.data.ts
apps/docs/src/data/components/popover.data.ts
apps/docs/src/data/components/spinner.data.ts
apps/docs/src/data/components/table.data.ts
apps/docs/src/data/components/tabs.data.ts
apps/docs/src/docs/components/tabs.md
apps/docs/src/docs/configurations/customizing-styles.md
apps/docs/src/docs/configurations/global-options.md
apps/docs/src/types/index.ts

This documents the CSS selectors that can be used to add styles to each component, as discussed [here](https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/2344#issuecomment-2481806547)
This ended up having more corner cases than I hoped, but if I'm reading the code correctly, I believe I've documented them all. The one component that I couldn't determine a CSS selector to uniquely identify was BSkelotonWrapper. I don't think that matters, though.
N/A

docs: document css selectors for customizing styles on components

---

apps/docs/src/docs/composables/useModal.md

docs: fix example sending click event to expected string param

---

apps/docs/.gitignore
apps/docs/package.json
apps/docs/src/data/components/tabs.data.ts
apps/docs/src/docs/components/demo/BreadcrumbManual.vue
apps/docs/src/docs/components/demo/CardBorderedVariants.vue
apps/docs/src/docs/demo/SyncAfter.vue
apps/docs/src/docs/demo/SyncBefore.vue
package.json
turbo.json

See #2418 
This PR sets up a type-check command for docs and cleans up the errors in component reference data and samples.
I'll chip away at the other errors as time permits
N/A

docs: Enable optional type-checking and clean up several issues

---

apps/docs/src/docs/types.md
packages/bootstrap-vue-next/src/types/RadiusElement.ts

I believe that `RadiusElement` should include a `md` value. My guess it that it was left out because in most cases this is the default. But when going through the `BAvatar` examples with linting enabled, we have cases where we want to explicitly set one edge to 'md' when the rest of the avatar defaults to 'circle'. If there is a reason to have a type that doesn't include 'md' we can split it out, but I'm not seeing one right now.
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/avatar.html#rounding
```vue
<BAvatar rounded-start="md" />
<BAvatar rounded-end="md" />
```

fix(RadiusElement): Add 'md' value

---

apps/docs/src/components/OpenCollectiveMemberDisplay.vue
apps/docs/src/components/OpenCollectiveMemberDisplayAvatarCard.vue
apps/docs/src/data/opencollective.data.ts
apps/docs/src/types/index.ts

General clean-up of types in the OpenCollective components, mostly to do with grouping resulting in unknown types and how to deal with the possibility of null members in the resulting groups.
The other is that for some reason, while [vitepress build time data loading](https://vitepress.dev/guide/data-loading#build-time-data-loading) is working, whatever magic they are using to lie to typescript to tell it that the `*.data.ts` file contains a named export called `data` isn't working. I wasn't able to find an existing but on vitepress about this. However, I was able to work around it by stubbing the `data` export. This fixes typescript, and doesn't break the data loading - would be delighted with a better solution if anyone has one.
```
Module '"../data/opencollective.data"' has no exported …
```

docs: Fix type errors in  OpenCollective components

---

packages/bootstrap-vue-next/src/components/BTable/BTable.vue

This pull request exposes the items of the `BTable` component, like in `bootstrap-vue`. The main motivation behind this is compatibility. The variable used to be named `filteredItems` in `bootstrap-vue` thus could be accessed in a ref like `this.$refs.table.filteredItems` and allowed for custom entry counters and such to be made.

feat(BTable): expose table items

---

apps/docs/src/data/components/table.data.ts
packages/bootstrap-vue-next/src/components/BTable/BTable.vue
packages/bootstrap-vue-next/src/types/ComponentProps.ts

This PR aims to bring over the ability to pass a custom filter function to the `BTable` component as seen in `bootstrap-vue`. This gives developers more control over how exactly they want to filter their data inside tables.
Hard to properly convey in a video, but here is a small replication of what this could do. Code is displayed underneath the table.
https://github.com/user-attachments/assets/232fbd06-ed5b-4087-9f37-17081af03b2c

feat(BTable): custom filter functions

---

apps/docs/.vitepress/theme/Layout.vue
apps/docs/src/components/PageContents.vue
apps/docs/src/components/PageContentsItem.vue
apps/docs/src/data/components/nav.data.ts
packages/bootstrap-vue-next/src/components/BNav/BNavItem.vue

This is another incremental step towards getting the "On the Page" contents working like in the BSV documentation.
- I've converted the raw `<ul>` `<li>` styling to use <BNav> and <BNavItem> and update the CSS to work correctly.
- In order to allow for nested navs I've added a slot after the link in the <BNavItem>
- With this is place we should be able to start using ScrollSpy to keep the nav and the body in sync (but an initial attempt failed, so I'll need to dig into ScrollSpy a bit deeper before I get that working)
See the docs On this Page sidebar

docs: use BNav for "on this page" contents

---

apps/docs/src/components/NotYetDocumented.vue
apps/docs/src/docs/migration-guide.md

Based on the feedback from #2486 it seems that the migration guide looks deceptively complete. To mitigate this, I've added a note in the migration guide components and directives that I haven't completed the parity pass on to let folks know that they shouldn't depend on the migration guide to be complete for the specific component or directive. In the process I added placeholders for components and directives that didn't previously have entries in the guide.
N/A

docs: Add placeholders to components and directives that haven't been completed

---

apps/docs/src/docs/components/demo/OptionsArray.ts
apps/docs/src/docs/components/demo/OptionsGroups.ts
apps/docs/src/docs/components/demo/OptionsObjectArray.ts
apps/docs/src/docs/components/demo/OptionsObjectArrayNormalized.ts
apps/docs/src/docs/components/demo/OptionsObjectArrayRaw.ts
apps/docs/src/docs/components/demo/TableComplete.vue
apps/docs/src/docs/components/demo/TableSimpleOverview.vue
apps/docs/src/docs/components/demo/TableSimpleStacked.vue
apps/docs/src/docs/components/demo/TableSimpleSticky.vue
apps/docs/src/docs/components/demo/TableSort.vue
apps/docs/src/docs/components/demo/TableSortBy.ts
apps/docs/src/docs/components/demo/TableSortBy.vue
apps/docs/src/docs/components/demo/TableSortByMulti.vue
apps/docs/src/docs/components/table.md
apps/docs/src/docs/migration-guide.md

- Refactor existing BTable examples into their own files
- Fix issues with the examples found during the refactoring
- Re-order the exiting BTable docs to match the BSV order
- Fix up BTableSimple documentation to refer to BSVN and BS5
- Small additions to migration guide
This is my initial run at the docs/parity pass on BTable. It's big enough that will be doing it in multiple phases.
N/A

docs(BTable): Refactor and clean up examples

---

apps/docs/.vitepress/theme/Layout.vue
apps/docs/.vitepress/theme/index.ts
apps/docs/package.json
pnpm-lock.yaml

Vitepress is now exporting `VPNavBarSearch` which lets us import it cleanly. Also fixed a no-explicit-any error in our doc's index.ts
N/A

docs: Fix typescript errors in vitepress by correctly importing search component

---

packages/bootstrap-vue-next/src/types/ComponentProps.ts
packages/bootstrap-vue-next/src/types/TableTypes.ts
packages/bootstrap-vue-next/src/types/index.ts

- Export several types that are needed to implement the examples in the docs
- Remove `headRowVarian`t and `headVariant` which were commented out in BTable, since they're implemented in BTableLite
- Remove the `sortDirectionProp` from `BTable`, since it is superseded by `sortBy`
- Remove `sortKey` from `TableField` since its functionality is superseded by `sortBy`

fix(BTable): Export additional types

---

apps/docs/src/docs/components/demo/TableCustomData.vue
apps/docs/src/docs/components/demo/TableFieldObjects.vue
apps/docs/src/docs/components/demo/TableFormatter.vue
apps/docs/src/docs/components/demo/TableRawHtml.vue
apps/docs/src/docs/components/demo/TableSortBy.vue
apps/docs/src/docs/components/demo/TableSortByMulti.vue
apps/docs/src/docs/components/table.md
apps/docs/src/docs/migration-guide.md

- Port the docs from BSV for custom data rendering of BTables
- Update the examples
- Update migration guide
- Address #2510 in the migration guide
N/A

docs(BTable): Document custom data rendering

---

apps/docs/src/components/OpenCollectiveMemberDisplayAvatarCard.vue

When building the docs locally, it pulled in a new contributor who had contributed $10, but the API isn't specifying the currency for some reason:
```
"MemberId": 0000,
"createdAt": "2025-02-01 13:18",
"type": "USER",
"role": "FOLLOWER",
"isActive": true,
"totalAmountDonated": 10,
"currency": "USD",
"lastTransactionAt": "2025-02-01 13:24",
"lastTransactionAmount": 10,
"profile": "https://opencollective.com/xxxxx",
"name": "XXXX XXXX",
"company": null,
"description": null,
"image": "https://opencollective-production.s3.us-west-1.amazonaws.com/deadf960-e768-11ea-9f8b-49726fcd5851.jpg",
"email": null,
"newsletterOptIn": null,
"twitter": null,
"github": "https://github.com/xxxx",
"website": null
```
Defaulting to `USD` in this case seems reasonable.
Build and run the docs
**What kind of …

fix(OpenCollective): Make AvatarCard currency default to USD if not specified

---

apps/docs/.vitepress/theme/Layout.vue
apps/docs/src/docs/components/demo/LinkColors.vue
apps/docs/src/docs/components/demo/LinkDisabled.css
apps/docs/src/docs/components/demo/LinkDisabled.vue
apps/docs/src/docs/components/demo/LinkExternal.vue
apps/docs/src/docs/components/demo/LinkHoverVariants.vue
apps/docs/src/docs/components/demo/LinkOpacity.vue
apps/docs/src/docs/components/demo/LinkOpacityHover.vue
apps/docs/src/docs/components/demo/LinkSimple.vue
apps/docs/src/docs/components/demo/LinkStyles.vue
apps/docs/src/docs/components/demo/LinkUnderlineColors.vue
apps/docs/src/docs/components/demo/LinkUnderlineOffsets.vue
apps/docs/src/docs/components/demo/LinkUnderlineOpacity.vue
apps/docs/src/docs/components/input-group.md
apps/docs/src/docs/components/link.md
apps/docs/src/docs/types.md
packages/bootstrap-vue-next/src/types/ComponentProps.ts
packages/bootstrap-vue-next/src/types/LinkDecorators.ts
packages/bootstrap-vue-next/src/types/index.ts

- Create and export types used by examples (and possibly useful elsewhere) - addresses #2537
- `LinkOpacity`
- `UnderlineOpacity`
- `UnderlineOffset`
- Add the above types to `types.md`
- Refactor the examples for BLink into their own files
- Fix linting/typescript issues uncovered by the refactor
- Add some space below custom notes

fix(BLink): Create and export Opacity and Offset types

---

apps/docs/package.json
apps/docs/src/docs/components/demo/FormSpinbuttonEvents.vue

Fix the last type check bug that crept in with example refactoring
Enable type checking with the build
This should make the build fail and keep new type check bugs from creeping in, fully addressing #2418 

docs: Enable type checking - addresses #2418

---

packages/bootstrap-vue-next/src/components/BAccordion/BAccordionItem.vue
packages/bootstrap-vue-next/src/components/BDropdown/BDropdownDivider.vue
packages/bootstrap-vue-next/src/components/BDropdown/BDropdownForm.vue
packages/bootstrap-vue-next/src/components/BDropdown/BDropdownHeader.vue
packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItem.vue
packages/bootstrap-vue-next/src/components/BDropdown/BDropdownItemButton.vue
packages/bootstrap-vue-next/src/components/BDropdown/BDropdownText.vue
packages/bootstrap-vue-next/src/components/BFormCheckbox/BFormCheckbox.vue
packages/bootstrap-vue-next/src/components/BNav/BNavForm.vue
packages/bootstrap-vue-next/src/components/BTabs/BTab.vue

This is a direct copy of @VividLemon's changes that remove the use of the spread operator on the results of useAttrs, which should resolve #2541 
See the bug

fix: make attributes reactive in Accordion, Tab, Dropdown*, etc.

---

apps/docs/src/docs/types.md
packages/bootstrap-vue-next/src/types/LinkDecorators.ts

I missed this when adding explicit types for the link properties and now that I've got type checking on the docs build working, this prevented me from doing an `pnpm install` on main.
N/A

fix(BLink): Allow  "0" as a value for UnderlineLinkOpacity

---

apps/docs/src/data/components/carousel.data.ts
apps/docs/src/docs/components/dropdown.md
apps/docs/src/docs/migration-guide.md
apps/docs/src/utils/dropdown-common.ts
apps/playground/src/components/Comps/TDropdown.vue
apps/playground/src/components/Comps/TNav.vue
packages/bootstrap-vue-next/src/components/BCarousel/BCarousel.vue
packages/bootstrap-vue-next/src/components/BDropdown/BDropdown.vue
packages/bootstrap-vue-next/src/components/BDropdown/dropdown.spec.ts
packages/bootstrap-vue-next/src/components/BNav/BNavItemDropdown.vue

Addresses #2571 
- replace the `click` event with `split-click` when the dropdown is in split mode. This prevent it from hiding the native click event and allows the user to access the native event to stop propagation
- replace the `click:prev` and `click:next` events on `BCarousel` with `prev-click` and `next-click` for consistency
- make this work for NavItemdropdown as well
- remove the documentation for `click`
- update the migration guide
- Add test cases to `TDropdown` and `TNav`
- fix up the main documentation for `BDropdown`
See #2571 

fix(BDdropdown)!: Replace click event on split button with split-click

---

apps/docs/src/docs/components/demo/TableSortBy.vue
apps/docs/src/docs/components/demo/TableSortCompareCustom.ts
apps/docs/src/docs/components/demo/TableSortCompareDefault.ts
apps/docs/src/docs/components/table.md
apps/docs/src/docs/migration-guide.md
apps/docs/src/docs/types.md

- Attempt to clarify the use of `sortBy` model.
- Add a deprecation warning to `v-model` binding section
- Add documentation for sort compare functions
- Updater migration guide

docs:(BTable): Extend documentation and migration guide for sorting

---

apps/docs/.vitepress/theme/Layout.vue

Replace `rem` with `em` in svg height attribute for Safari compatibility.
Related to #2611

fix(svg): use em instead of rem for height to avoid Safari error

---

apps/docs/src/docs/components/spinner.md

Fixes spinner docs not working with script setup after compilation.
Related to #2606

docs(BSpinner): resolve hydration mismatch

---

apps/docs/.vitepress/theme/Layout.vue
apps/docs/src/components/PageContents.vue
packages/bootstrap-vue-next/src/App.vue

Use the `useScrollSpy` composable to track the position of the main document in the "On this page" contents.
See the docs

docs(otp): Track on this page with scrollspy

---

apps/docs/src/docs/components/demo/TableProvider.vue
apps/docs/src/docs/components/demo/TableProviderAsync.vue
apps/docs/src/docs/components/table.md
packages/bootstrap-vue-next/src/components/BTable/BTable.vue

This addresses #2638
- correct multi-sort to not update sortby in place - this corrects an issue where the watch of sortBy was short-circuiting because oldVal and newVal were equal
- do a deep compare of the values coming into proiverPropsWatch, since sortBy may change only a single value in the object in the array - technically the first fix covers this, since the existing code did an object reference, but this seems more robust
- create a demo of using an items provider function as a stop-gap until I have time to complete that part of the documentation
See the sample

fix(BTable): correct multi-sort to not update sortby in place

---

apps/docs/src/data/components/button.data.ts
apps/docs/src/docs/reference/color-variants.md
packages/bootstrap-vue-next/src/components/BButton/BButton.vue
packages/bootstrap-vue-next/src/types/ComponentProps.ts

When I was documenting and fixing up `useColorVariantClasses`, I missed the fact that BButton didn't actually consume that composible. This fixes that oversight.
Fixes #2637
```
<template>
<BRow
><BCol>Set 'variant': <BButton variant="success"> testing </BButton></BCol></BRow
>
<BRow
><BCol>Set 'bg-variant': <BButton bg-variant="info"> testing </BButton></BCol></BRow
>
<BRow
><BCol
>Set 'text-variant' (background is 'secondary' since 'variant' defaults to 'secondary'):
<BButton text-variant="info"> testing </BButton></BCol
></BRow
>
<BRow
><BCol
>Set 'text-variant' and 'bg-variant':
<BButton text-variant="primary" bg-variant="danger"> testing </BButton></BCol
></BRow
>
<BRow
><BCol
>Set all three - 'variant' is overridden by 'bg-variant' and 'text-variant':
<BButton text-variant="primary" …
```

fix(BButton): Consume useColorVariantClasses

---

apps/docs/src/data/components/button.data.ts
apps/docs/src/docs/components/button.md
apps/docs/src/docs/reference/color-variants.md
packages/bootstrap-vue-next/src/components/BButton/BButton.vue
packages/bootstrap-vue-next/src/types/ComponentProps.ts

This reverts commit 379fd9acc185f87d806d62e4be4c8045a59da485.
As noted in #2653, the change in #2640 caused more issues than it fixed. I believe that it is because useColorVariant uses the variant property to set `text-bg-*` which overrides the `btn-variant-*` class in the .css.
I'd like to revert this change outright + remove the confusing docs.
Longer term we could consider implementing `bg-variant` and `text-variant` on `BButton` and possibly other components that support them, but for the short term a perfectly viable solution is to treat these as utility classes and have the user set them manually. @hackel - can you confirm that this would work-around the issue that you filed #2637 for?
See #2653
**The PR fulfills …

Revert "fix(BButton): Consume useColorVariantClasses (#2640)"
